.vscode/launch.json
On past projects, we've shared a vscode config for doing things like running tests in the vscode debugger.  If folks would prefer to keep their config individually and locally, we can just close this.
@jim did the heavy lifting to get the debugger working on this project (for tests in /app-web).
=> Add config to debug tests in vscode

services/postgres/serverless.yml
Because Aurora turns itself off if there is no traffic to it, we have long cold-start times for our application in val and prod. This creates a bad user experience as a fresh user to the application when the database is off has to wait 30 seconds or more before the application can handle requests.
We've decided to keep a minimal configuration online in val and prod so there are no more cold start times.
https://qmacbis.atlassian.net/browse/OY2-14082
=> Conditionally keep Aurora online

.github/workflows/deploy.yml
This returns the ref back to `main` for deploy-branch GHA runs.
=> Point deploy-branch to main

dev_tool/src/local/api.ts
Now that ctkey is working for `serverless` commands, when running `./dev local` the command that is being run uses the ctkey wrapped command. This doesn't work when we don't want to actually connect to AWS. 
This fix runs `npx serverless ...` so that the command being run by `./dev local` uses the regular serverless environment and skips ct-key.
=> Prepend npx to serverless local command

services/app-web/src/pages/Dashboard/Dashboard.module.scss
Bugfix for spacing on the submission table on the dashboard. This is relevant when the table is empty or has few entries
Photo of the bug
=> fix: Remove margin auto CSS on dashboard container

README.md
Adding some notes on how to verify ctkey setup with serverless.  The `which serverless` expected result is tied to work in #590.
=> Readme edits: add more detail about how to verify ctkey setup

services/app-web/src/components/FileUpload/FileUpload.tsx, services/app-web/src/components/Form/FieldCheckbox/FieldCheckbox.tsx, services/app-web/src/components/Form/FieldRadio/FieldRadio.tsx, services/app-web/src/pages/StateSubmission/Contacts/Contacts.test.tsx, services/app-web/src/pages/StateSubmission/Contacts/Contacts.tsx, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.test.tsx, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.tsx, services/app-web/src/pages/StateSubmission/Documents/Documents.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.test.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.test.tsx, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx, tests/cypress/support/stateSubmissionFormCommands.ts
- Required notes should be read in relation to form fields
- State user knows accepted file formats on doc upload
https://qmacbis.atlassian.net/browse/OY2-13570
https://qmacbis.atlassian.net/browse/OY2-13574
- displays correct form guidance - on SubmissionType, ContractDetails, RateDetails pages
- displays correct form guidance for contract only submission and displays correct form guidance for contract and rates submission - on Contacts page
- Make sure required fields are announced as required by screenreader (voiceover and JAWS)
=> fix: Required notes should be read for form fields, acceptable file types should be read for file upload

services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.tsx, tests/cypress/integration/stateWorkflow/dashboard/dashboard.spec.ts
Our date ranges on the summary pages get read strangely by Voiceover. This is a change to address that. 
We display date ranges (like contract effectiveness dates) on pages like this:
12/03/2021 - 08/14/2022
Voiceover has a real bug with this where it reads the 08 as “two thousand eight” for some reason. JAWS did not. But both of them read them very literally. “twelve slash zero three slash twenty twenty one dash…”
[This guidance](https://www.gov.uk/guidance/content-design/writing-for-gov-uk#date-ranges) from gov.uk specifies using “to” instead of a dash, and that was enough to get VO to behave. It also suggests writing out months explicitly. So then I tried this:
Dec 3 2021 to Aug 14 2022
and VO read it like a person would. “December third two thousand twenty one to…”
I’m definitely …
=> Change date rage separator to 'to'

services/app-web/src/pages/Dashboard/Dashboard.module.scss
Tags on the dashboard are wrapping strangely with longer program names. 
I've added `display: inline-block` to the tag layout to allow for the tags to wrap to new lines when they are longer.
=> Fixing wrapping tag layout on dashboard

services/app-web/src/s3/s3Amplify.ts, services/uploads/serverless.yml
[Ticket 13893](https://qmacbis.atlassian.net/browse/OY2-13893)
During a walkthrough, we saw multiple file upload scan failures and decided to investigate.
In pairing on this with @mojotalantikite and @haworku, we discovered two issues:
1. Large files were being uploaded in parts, and multipart upload *requires a different trigger* in the lambda
2. Scans of larger files were taking longer than our three polling retries allowed.
No tests; just some config changes.
Upload large files, and several files at the same time.  Should work.
=> Fix upload "scan" failures

services/uploads/serverless.yml
There was a typo in the s3 event type for the AV scanning fix that landed earlier. This collapses the rule into a single wildcard -- all objects created in the uploads bucket will trigger an AV scan. The list of event notification types can be found in the [AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-how-to-event-types-and-destinations.html).
=> Fix s3 event trigger for AV scan

services/app-api/emailer/templates.ts, services/app-api/resolvers/submitDraftSubmission.test.ts
State and CMS user should know that emails are from a system in testing 
Struggling with string matching (particularly with spacing and new lines) in our current unit tests for CMS email. Will come back through in another PR and fix tests. We want to get this in for today's parallel path test. 
https://qmacbis.atlassian.net/browse/OY2-15262
Check state and CMS emails. Text should be red.
=> Add note text to emails "not official"

services/app-api/emailer/templates.ts, services/app-api/resolvers/submitDraftSubmission.test.ts
- make it BOLD
- get tests back in there without all fighting all the whitespace. Test smaller chunks of text.
follow up from #741 
Added a new set of tests to make sure all state contacts are included in to addresses for state email.  Otherwise just added more assertions to existing tests to hopefully make it less breakable but still have a test that will fail if the wrong email template is prepared.
=> Clean up email tests and make red text bold

services/app-web/package.json, services/app-web/src/components/DynamicStepIndicator/DynamicStepIndicator.test.tsx, services/app-web/src/components/DynamicStepIndicator/DynamicStepIndicator.tsx, tests/cypress/integration/stateWorkflow/stateSubmissionForm/contacts.spec.ts, tests/cypress/integration/stateWorkflow/stateSubmissionForm/contractDetails.spec.ts, tests/cypress/integration/stateWorkflow/stateSubmissionForm/documents.spec.ts, tests/cypress/integration/stateWorkflow/stateSubmissionForm/newSubmission.spec.ts, tests/cypress/integration/stateWorkflow/stateSubmissionForm/rateDetails.spec.ts, tests/cypress/integration/stateWorkflow/stateSubmissionForm/reviewAndSubmit.spec.ts, tests/cypress/integration/stateWorkflow/stateSubmissionForm/submissionType.spec.ts, tests/cypress/support/stateSubmissionFormCommands.ts, yarn.lock
Closes [13565](https://qmacbis.atlassian.net/browse/OY2-13565)
Small change to use react-uswds's new capability to specify the header level in a step indicator to make sure that our headers progress sequentially.
Added one line to a unit test to check that the passed-in level is what's in the DOM.
Should look and work exactly the same, but the DOM should have an h2 in the header, and screen readers should not be confused by the app headers.
=> OY2-13565 make step header h2

services/app-web/src/pages/Help/Help.module.scss, services/app-web/src/pages/Help/Help.tsx, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.tsx, services/app-web/src/pages/StateSubmission/Documents/Documents.test.tsx, services/app-web/src/pages/StateSubmission/Documents/Documents.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx, services/app-web/src/pages/StateSubmission/StateSubmissionForm.test.tsx
Adding the documents definitions and requirements table to the help page along with links on contract details, rate details, and supporting documents pages.
=> Add documents definitions and requirements table

services/app-web/src/components/FileUpload/FileItem/FileItem.tsx, services/app-web/src/components/FileUpload/FileItemList/__snapshots__/FileItemsList.test.tsx.snap, services/app-web/src/components/FileUpload/FileUpload.tsx
This PR adds some text to the file upload component that describes how many files have been selected. This text updates automatically, and whenever a new file is added or one is removed, it is auto-focused. This will cause it to be announced by JAWS.
This PR also includes some additional markup to add ARIA roles to the progress display used during file uploads. That work will likely continue.
For more details, see commit messages 😄 
This PR supersedes #716, which took a different approach to addressing this issue. 
https://user-images.githubusercontent.com/3331/148585769-5d6a1bcb-cbe0-492e-acb8-909091ca6fdb.mov
As you make changes to the file list, the number of file should always be announced.
=> Announce selected file count (#10541)

.github/workflows/promote.yml
Looks like GHA will not tell you if you have an output dependency on a previous run, but that job was not listed in "needs". This should fix promote deploys to val and prod.
=> Depend on unit-tests output for promotes

services/app-web/src/s3/s3Amplify.ts
Uploading files with commas in their names was failing in Chrome.  Some googling led me to the `content-disposition` header, and I'm just wrapping the file name in quotes, which resolves the issue.
Closes [15489](https://qmacbis.atlassian.net/browse/OY2-15489)
No changes
Meghan confirmed this works on the deployed branch, but feel free to try it out for yourself.
=> Fix bug in uploading files with commas in name

services/app-api/resolvers/fetchStateSubmission.test.ts, services/app-api/resolvers/updateDraftSubmission.test.ts, services/app-api/testHelpers/gqlHelpers.ts, services/app-graphql/src/mutations/createDraftSubmission.graphql, services/app-graphql/src/mutations/submitDraftSubmission.graphql, services/app-graphql/src/mutations/updateDraftSubmission.graphql, services/app-graphql/src/queries/fetchDraftSubmission.graphql, services/app-graphql/src/queries/fetchStateSubmission.graphql, services/app-graphql/src/schema.graphql, services/app-proto/src/state_submission.proto, services/app-web/src/common-code/domain-models/DraftSubmissionType.d.ts, services/app-web/src/common-code/domain-models/index.ts, services/app-web/src/common-code/proto/stateSubmission/draftSubmissionSchema.ts, services/app-web/src/common-code/proto/stateSubmission/stateSubmissionEncoding.test.ts, services/app-web/src/common-code/proto/stateSubmission/toDomain.ts, services/app-web/src/common-code/proto/stateSubmission/toProtoBuffer.ts, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.test.tsx, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.tsx, services/app-web/src/pages/StateSubmission/Documents/Documents.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.test.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx, services/app-web/src/pages/StateSubmission/StateSubmissionForm.test.tsx, services/app-web/src/testHelpers/apolloHelpers.tsx
This is the backend work for the document categorization epic 
https://qmacbis.atlassian.net/browse/OY2-5476
No need test cases added but existing tests edited to handle documents that have `documentCategories`.
The app should work as before. Silently contract documents are put in the 'CONTRACT' category, rates into 'RATES', and for now supporting documents have an empty array of categories. Eventually this work will be hooked into the frontend via the supporting docs table.
=> Add documentCategories to api

services/app-web/src/components/FileUpload/FileItem/FileItem.tsx, services/app-web/src/components/FileUpload/FileItemList/FileItemsList.tsx, services/app-web/src/components/FileUpload/FileItemList/__snapshots__/FileItemsList.test.tsx.snap, services/app-web/src/components/Form/ErrorSummary/ErrorSummary.stories.tsx, services/app-web/src/components/Form/ErrorSummary/ErrorSummary.tsx, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.tsx, services/app-web/src/pages/StateSubmission/Documents/Documents.test.tsx, services/app-web/src/pages/StateSubmission/Documents/Documents.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx
Within forms that allow uploads:
* Clicking on the error messages for validation errors within the file list (duplicate files or upload/scan errors) will now focus the file list
* Errors related to files not being selected will continue to focus the file input when clicked
I attempted to implement this by passing `React.Ref`s down into the `ErrorSummary`, but in the end the behavior was flakey, there was a lot more code, and ultimately I fell back to the approach used here.
https://qmacbis.atlassian.net/browse/OY2-13946
I didn't add unit tests for this functionality due to the limitations with JSDOM and Jest that we uncovered in an earlier story. I did add a new story to Storybook, though, that shows the functionality.
* Trigger file errors and verify that the file list is focused when …
=> Focus file list when there are file errors (#13946)

services/app-web/src/components/FileUpload/FileUpload.test.tsx
We had a failed promote due to what could be a flakey unit test. It's a new test added several days ago.
Trying to add additional assertions (similar to whats used elsewhere in the file) to ensure scanning is over before we check that error summary has updated.
Example of failed test in CI promote:
https://github.com/CMSgov/managed-care-review/runs/4820930269?check_suite_focus=true
=> Refactor flakey file upload test

services/app-web/src/components/FileUpload/FileUpload.test.tsx, tests/cypress/integration/stateWorkflow/stateSubmissionForm/documents.spec.ts
Move the tests of our new accessibility file upload summary  - (X complete, X error, X pending) text that updates as files scan and complete -  into Cypress. Jest tests are flaking and only randomly for unclear reasons. This is blocking our promote workflow. https://github.com/CMSgov/managed-care-review/actions/runs/1714316813 
Let's test this same behavior with Cypress instead.
=> Refactor flakey FileUpload unit test

services/app-web/src/components/FileUpload/FileItem/FileItem.test.tsx, services/app-web/src/components/FileUpload/FileItem/FileItem.tsx, services/app-web/src/components/FileUpload/FileItemList/FileItemsList.test.tsx, services/app-web/src/components/FileUpload/FileItemList/__snapshots__/FileItemsList.test.tsx.snap, services/app-web/src/components/FileUpload/FileUpload.test.tsx, services/app-web/src/pages/StateSubmission/Documents/Documents.test.tsx
https://qmacbis.atlassian.net/browse/OY2-15635
- add aria- attributes to file items
- Test in JAWS - the remove button should now announce "Remove FILE_NAME document"
=> Add aria label for file remove and retry buttons that includes file name

services/app-web/src/common-code/formatters/pluralizer.test.ts, services/app-web/src/common-code/formatters/pluralizer.ts, services/app-web/src/components/FileUpload/FileUpload.module.scss, services/app-web/src/components/FileUpload/FileUpload.tsx, services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.tsx, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.tsx, services/app-web/src/pages/StateSubmission/Documents/Documents.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx
Copy change: Add copy on accepted file formats when uploading documents
Copy change: Use "Contract amendment effective dates"  for contract amendment submissions + change "Effective dates of rate amendment" to "Rate amendment effective dates"
https://qmacbis.atlassian.net/browse/OY2-15638
https://qmacbis.atlassian.net/browse/OY2-15523
`ContractDetailsSummarySection.test.tsx` (component used both on review and submit and submission summary
- displays correct text content for a contract amendment
- displays correct text content for a base contract
Tickets have a good description of whats changed here
=> Copy change: display accepted file formats and adjust submission summary copy for "effective dates"

.envrc, .github/workflows/promote.yml, README.md
This moves the sourcing of our `./scripts` directory for `ctkey-wrapper` out of our regular `.envrc`  setup. This sourcing was causing issues for some team members that weren't wanting or needing access to AWS via CloudTamer.
Instead devs that wish to use it should source it in their `.envrc.local`. I've updated the docs.
https://qmacbis.atlassian.net/browse/OY2-15319
=> Move ./scripts sourcing to .envrc.local

.github/workflows/promote.yml
This changes the failure on promote alert to Red. {{ job.status }} was (is) always success.
https://qmacbis.atlassian.net/browse/OY2-14660
=> Fix Slack Alert Color

services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx
Add `aria-describedby` to submission description so that SR's will read the help text associated with the textarea.
I also made a copy change to the hint text based on the feedback and iteration we had after our Nov. PP test.
=> Add aria-describedby to submission description

scripts/destroy_stage.ts
I noticed that the new destroy script can actually go too fast and get us rate limited by AWS. This slows it down to wait on each destroy before moving on.
It's a lot slower, but I don't think we care that much -- this is just a background task that cleans up the AWS dev environment. As long as we're cleaned up (and alerted on failures) I think we're good.
https://qmacbis.atlassian.net/browse/OY2-14896
=> Make destroy slower to avoid AWS rate limiting

.github/workflows/promote.yml
This adds a Slack notification if our val or prod tasks during promote are ever 'skipped', which in our case indicates something is wrong since we always want to promote to each environment. Skips should only ever happen with our "skipping" action in dev PR branches.
https://qmacbis.atlassian.net/browse/OY2-15466
=> Alert if Promote has 'skipped' results

services/app-api/emailer/templates.test.ts, services/app-api/emailer/templates.ts, services/app-api/resolvers/submitDraftSubmission.test.ts, services/app-api/testHelpers/emailerHelpers.ts, services/app-api/testHelpers/gqlHelpers.ts
Update CMS submission email to include key dates
https://qmacbis.atlassian.net/browse/OY2-15321
- I added `templates.test.ts` which includes several new unit tests that cover all of the current logic in our email templates (including new dates work).
-  Simplified `submitDraftSubmission.test.ts` accordingly.
- Added `emailerHelpers.ts`
- Exported the `defaultContext` used in our gql handlers for tests - that way the tests can determine who is the "current user"
Make a submission, then check shared email to ensure CMS email includes new dates fields
=> Update CMS submission email to include key dates

services/app-api/emailer/emailer.ts, services/app-api/emailer/index.ts, services/app-api/emailer/templates.test.ts, services/app-api/emailer/templates.ts, services/app-api/testHelpers/emailerHelpers.ts
Fixed a styling a bug where when rating period wasn't included on emails we were still displaying an extra line break `<br>`. 
Also
- added more styling and text changes I found in the updated [Figma copy](https://www.figma.com/file/a0PPSr65q1G798zV4bhzzO/State-submission-form?node-id=5804%3A49022) for CMS email
-  simplify the relationship between `bodyText` and `bodyHTML` by making a convertor. 
-  did requested renaming of templater functions @macrael 👍 
follow on for https://qmacbis.atlassian.net/browse/OY2-15321
BEFORE: what the bug looked like for any submission that doesn't have rates
AFTER: now with bugfix and styling changes
=> Add email styling tweaks

services/app-api/resolvers/updateDraftSubmission.test.ts, tests/cypress/integration/stateWorkflow/dashboard/dashboard.spec.ts
We have a test that is failing from time to time, seems like it might be related to postgres spinning up? We definitely think it’s only started happening post postgres. 
I vaguely remember seeing this in deploy.yml CI runs, but recently it’s only been happening on Promote. 
https://qmacbis.atlassian.net/browse/OY2-14070
I’ve doubled the timeout of this test, it is a bit suspicious that this particular test has a 2 second delay in it, so maybe we’re just hitting the timeout naturally.
=> Double timeout for flaky api test to 10 seconds

services/uploads/serverless.yml
ClamAV has been unable to download new virus definitions for two days b/c it was EOL’d. Updating to the latest LTS release should make things work again.
In all environmnents deployed on or after Feb 1, the virus definitions have never been downloaded and virus scanning always fails.
We depend on https://github.com/CMSgov/lambda-clamav-layer/ so I made a new release there with the more recent version of ClamAV.
If you can log into this review app and upload a file successfully then the fix worked.
=> Update ClamAV layer to latest version 0.6 (ClamAV v0.103.3)

services/uploads/serverless.yml, services/uploads/src/clamav.js, services/uploads/src/constants.js
In a continuing effor to solve our [issues stemming from our version of ClamAV getting outdated](https://docs.google.com/document/d/1V3OUC9ryF24YY-kQccUhMfKH4JRWXVAp7vhPH2ckW5M/edit#heading=h.oxwb3xfooa6j), this PR restores everything to working order. 
The command `freshclam` is used to download the latest version of the virus definition files. When we updated to the latest version of clamAV, that command started to behave differently. Before it always downloaded the antivirus files in a compressed format, so our service was hard coded to upload and download those files only. After updating, freshclam started to download the daily list in an uncompressed format. (though, confusingly and as of yet unexplained, it still downloaded in the compressed format the first time it ran)
I made two …
=> Modify avDownloadDefinitions to upload and download all clamAV files, not just the 3 named ones

services/app-api/postgres/findAllSubmissions.ts, services/app-api/postgres/findDraftSubmission.ts, services/app-api/postgres/findStateSubmission.ts, services/app-api/postgres/insertDraftSubmission.ts, services/app-api/postgres/storeError.test.ts, services/app-api/postgres/submissionWithRevisionsHelpers.ts, services/app-api/postgres/updateDraftSubmission.ts, services/app-api/prisma/migrations/20220208221835_add_revisions_table/migration.sql, services/app-api/prisma/migrations/20220209210827_remove_proto_from_state_submission/migration.sql, services/app-api/prisma/schema.prisma
Add “revisions” table to postgres
https://qmacbis.atlassian.net/browse/OY2-14193
- All app-api tests pass unchanged
- Revisions table has the proper information in Postico
- Revisions table has proper relationship with StateSubmission table (used SQL query to confirm)
=> Add revisions table

.github/workflows/deploy-app-to-env.yml
One of our [promotes](https://github.com/CMSgov/managed-care-review/runs/5149243994?check_suite_focus=true) hit an OOM while building `app-web` in prod. This is to bump the [`max_old_space_size`](https://nodejs.org/api/cli.html#cli_max_old_space_size_size_in_megabytes) to help avoid OOMing and spend less time in GC.
=> Bump max_old_space_size for Node OOM

.github/workflows/promote.yml
We just got two alerts on a promote failure, and it looks like it's because in #777 we added the condition to alert on a cypress val or prod 'skipped' state. This will happen whenever cypress-dev fails, in addition to other cases of earlier failure.
This removes the redundant case of when cypress alerts on failure in dev or val.
=> Remove double alerts on promote fail

.github/workflows/deploy.yml, .github/workflows/promote.yml
Code Climate is currently having an outage, which is causing CI to fail. This makes it so Code Climate stats publishing doesn't block CI runs from completing.
https://qmacbis.atlassian.net/browse/OY2-16793
=> Do not depend on Code Climate publishing success in CI

services/app-web/src/pages/Landing/Landing.tsx
Changes made to homepage:
- Added "Contracts may be fully executed or unexecuted by some or all parties" to the before you begin section
- Added "CHIP-only submissions" to list of what we don't accept yet
- Reworded "draft documents" to "documents for pre-approval"
=> Update copy on homepage to include unexecuted contracts

services/app-web/src/pages/StateSubmission/updateSubmissionTransform.ts
Showstopper bug found by Josh, we missed a spot in converting dates to work correctly with our weird handoff between our domain models and the old updateDraftSubmission inputs.
https://qmacbis.atlassian.net/browse/OY2-17270
We should be able to submit a rate amendment (with rate start/end dates) on this branch.
=> Fix rate amendment dates so we can continue past the Contacts page

docs/ADRs/016-use-launch-darkly-for-feature-flags.md
An ADR that describes the motivation for feature flags, comparing: 
-   do nothing
-   mange them ourselves
-   use AWS 
-   use launch darkly 
https://qmacbis.atlassian.net/browse/OY2-12254
I might have gotten a little wordy here, welcome edits for brevity also 😆
=> Add ADR on feature flags

cypress.json, services/app-web/src/pages/StateSubmission/StateSubmissionForm.tsx, tests/cypress/integration/cmsWorkflow/unlockResubmit.spec.ts, tests/cypress/integration/cmsWorkflow/viewSubmission.spec.ts, tests/cypress/integration/stateWorkflow/dashboard/dashboard.spec.ts, tests/cypress/integration/stateWorkflow/stateSubmissionForm/contacts.spec.ts, tests/cypress/integration/stateWorkflow/stateSubmissionForm/contractDetails.spec.ts, tests/cypress/integration/stateWorkflow/stateSubmissionForm/documents.spec.ts, tests/cypress/integration/stateWorkflow/stateSubmissionForm/newSubmission.spec.ts, tests/cypress/integration/stateWorkflow/stateSubmissionForm/rateDetails.spec.ts, tests/cypress/integration/stateWorkflow/stateSubmissionForm/reviewAndSubmit.spec.ts, tests/cypress/integration/stateWorkflow/stateSubmissionForm/submissionType.spec.ts, tests/cypress/support/commands.ts, tests/cypress/support/index.ts, tests/cypress/support/loginCommands.ts, tests/cypress/support/stateSubmissionFormCommands.ts
Address renewed Cypress flakes since adding unlock epic and monitoring work
- remove generic references to `gqlRequest` and replace with named aliases for each our queries and mutations. Look for `aliasQuery` and `aliasMutation` references.
-  This follows cypress best practice for gql which we first tried out with login helper https://docs.cypress.io/guides/testing-strategies/working-with-graphql#Modifying-a-Query-or-Mutation-Response 
- Remove generic `cy.wait` whenever possible as per https://docs.cypress.io/guides/references/best-practices#Unnecessary-Waiting
- I reworked the contract details test because I saw flaky behavior even locally when switch the submission type from contract only to contract rates and then trying to submit
https://qmacbis.atlassian.net/browse/OY2-17246
=> [OY2-17246] Cypress flakes debugging

services/app-web/src/dateHelpers/gqlDate.ts, services/app-web/src/gqlHelpers/submissionWithRevisions.ts, services/app-web/src/pages/StateSubmission/updateSubmissionTransform.ts
Josh found another pair of date bugs on Val, this addresses them.
Ultimately, I think that this was a typing failure around dates specifically. I think, but haven’t confirmed in depth, that GraphQL uses `any` for our custom types of which Date and DateTime are two. I suspect we could configure the code generator to have a specific type instead, which I think would have caught this bug. 
We fixed some errors we were seeing with our current Domain Model -> GQL conversion but we fixed them on the wrong end. We converted to the GraphQL standard (a string “2022-02-01”) when creating the body of the updateDraftSubmission request. This request was erroring at the API layer because we were sending a Date() instead of a string. 
However, actually, all of our code in the form itself also expects a …
=> Fix date off-by-one and pre-filled today bugs

services/app-web/src/pages/StateSubmission/Contacts/Contacts.test.tsx, tests/cypress/integration/stateWorkflow/stateSubmissionForm/contacts.spec.ts
Adjust contacts page Cypress tests, add to jest tests.  This seems to be a specific test spec that keeps flaking and isn't addressed by other attempts.
Follow up to #862 
- I  moved the testing logic for adding and removing contacts while editing Contacts information down from Cypress (where it was flaky, probably due to re-renders) into jest. This logic is just on the same page anyway, its better suited for React component testing
- I kept two Cypress tests - one testing contract only (no actuary contacts) and one testing contract and rates
=> Adjust contacts page tests

services/app-api/resolvers/unlockStateSubmission.test.ts, services/app-graphql/src/schema.graphql, services/app-web/src/components/ChangeHistory/ChangeHistory.module.scss, services/app-web/src/components/ChangeHistory/ChangeHistory.stories.tsx, services/app-web/src/components/ChangeHistory/ChangeHistory.test.tsx, services/app-web/src/components/ChangeHistory/ChangeHistory.tsx, services/app-web/src/components/SectionHeader/SectionHeader.module.scss, services/app-web/src/components/SectionHeader/SectionHeader.test.tsx, services/app-web/src/components/SectionHeader/SectionHeader.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx, tests/cypress/integration/stateWorkflow/dashboard/dashboard.spec.ts
Closes [#13875](https://qmacbis.atlassian.net/browse/OY2-13875)
Adds a history of unlocks and submissions to the bottom of the submission summary page, formatted as a list of accordions.
Accordions are there, open and close, have correct content.
Also had to add a test to Section Header, because I had to tweak it to allow rending without a bottom border on the title header.
Color contrast error on the accordion rows.  Not sure how we can override the uswds default, and googling isn't turning up any satisfying answers.  @haworku ?
How do _you_ expect VoiceOver to work here?  I'd like more guidance from VO about the fact that I'm on something like an accordion and can click down into the expanded content, but we're following the [guidance from …
=> OY2-13875: Add change history to submission summary page

services/app-web/src/pages/StateSubmission/ReviewSubmit/ReviewSubmit.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/ReviewSubmit.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx
Fix to address delay after modal closes and redirect when resubmitting a submission. 
**Note: **Also add code to close Unlock Modal on error. Does not seem to make sense to keep modal open and not see the error banner, but let me know otherwise.
[OY2-12183](https://qmacbis.atlassian.net/browse/OY2-12183?focusedCommentId=108213)
=>  Fix delay when modal closes to redirect when resubmitting

services/app-web/src/common-code/data-helpers/makeDocumentDateLookupTable.test.ts, services/app-web/src/common-code/data-helpers/makeDocumentDateLookupTable.ts, services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/UploadedDocumentsTable/UploadedDocumentsTable.module.scss, services/app-web/src/components/SubmissionSummarySection/UploadedDocumentsTable/UploadedDocumentsTable.test.tsx, services/app-web/src/components/SubmissionSummarySection/UploadedDocumentsTable/UploadedDocumentsTable.tsx, services/app-web/src/pages/SubmissionRevisionSummary/SubmissionRevisionSummary.test.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx, services/app-web/src/styles/theme/_color.scss
Closes[392](https://qmacbis.atlassian.net/browse/MR-392)
Adds a NEW tag to newly uploaded docs, provided the user is a CMS user.
Should see NEW when a doc is newer than the second submission (the first submission is the current one; the doc will be part of the current submission).
Should NOT see NEW if it's not a CMS user.
Updated the lookup table, which now has the date of the second submission.
Not much.  Should see that tag if you're logged in as a CMS user and a doc has been uploaded since the last submission, and not if not.
=> MR-392: Add a NEW tag to newly uploaded documents

services/app-web/src/components/Banner/PreviousSubmissionBanner/PreviousSubmissionBanner.tsx, services/app-web/src/components/Banner/SubmissionUnlockedBanner/SubmissionUnlockedBanner.test.tsx, services/app-web/src/components/Banner/SubmissionUnlockedBanner/SubmissionUnlockedBanner.tsx, services/app-web/src/components/Banner/SubmissionUpdatedBanner/SubmissionUpdatedBanner.tsx, services/app-web/src/components/Banner/index.ts, services/app-web/src/components/index.ts, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.module.scss, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.test.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx, services/app-web/src/testHelpers/apolloHelpers.tsx, tests/cypress/integration/cmsWorkflow/unlockResubmit.spec.ts, tests/cypress/integration/stateWorkflow/stateSubmissionForm/newSubmission.spec.ts, tests/cypress/integration/stateWorkflow/stateSubmissionForm/submissionType.spec.ts, tests/cypress/support/index.ts, tests/cypress/support/submissionCommands.ts
[MR-226](https://qmacbis.atlassian.net/browse/MR-226)
Display banner to users indicating the submission has been updated.
**NOTE: ** 
- Also updated unlocked banner timezone to default to ET.
- <strike>Also testing a fix for flaky test when clicking `Cancel` button on state submission form.</strike>
####
Screenshots
- SubmissionSummary.test.tsx
- renders submission updated banner
- unlockResubmit.spec.ts
- Navigate to resubmitted submission and check for submission updated banner after resubmission
=> MR-226: User sees banner message that a submission has been updated

services/app-web/src/pages/StateSubmission/StateSubmissionForm.tsx, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.test.tsx, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx
This is part of the ticket for adding the updateSubmission2 endpoint. This decouples all of the subtasks on that ticket so that they can be done independently. With this separate update function, we can update each of the pages of the form to operate on DraftSubmissionType (soon to be HealthPlanFormData) instead of the GQL types. And the new API can be written that accepts a revision, paving the way for us to get rid of the form data types from GQL.
- can’t find it right now b/c JIRA is being changed
* I got all tests passing, surprisingly little just for the SubmissionType component. I suspect the other form pages will require more changes. 
* The only page that was changed was the submissionType page, and specifically I changed updating it, no creating a new submission.
=> Add update function for DraftSubmissionType, decoupling the rest of the update work

services/app-api/.eslintrc, services/app-api/postgres/insertDraftSubmission.test.ts, services/app-api/postgres/insertDraftSubmission.ts, services/app-api/postgres/postgresStore.ts, services/app-api/postgres/updateFormData.ts, services/app-api/resolvers/configureResolvers.ts, services/app-api/resolvers/createSubmission2.test.ts, services/app-api/resolvers/createSubmission2.ts, services/app-api/resolvers/updateHealthPlanFormData.test.ts, services/app-api/resolvers/updateHealthPlanFormData.ts, services/app-api/testHelpers/gqlHelpers.ts, services/app-api/testHelpers/healthPlanPackageHelpers.ts, services/app-api/testHelpers/storeHelpers.ts, services/app-graphql/src/mutations/createSubmission2.graphql, services/app-graphql/src/mutations/updateHealthPlanFormData.graphql, services/app-graphql/src/schema.graphql, services/app-web/.eslintrc, services/app-web/src/components/Header/Header.test.tsx, services/app-web/src/components/Header/Header.tsx, services/app-web/src/contexts/AuthContext.tsx, services/app-web/src/pages/StateSubmission/New/NewStateSubmissionForm.test.tsx, services/app-web/src/pages/StateSubmission/StateSubmissionForm.tsx, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx, tests/cypress/integration/cmsWorkflow/unlockResubmit.spec.ts, tests/cypress/integration/stateWorkflow/stateSubmissionForm/submissionType.spec.ts, tests/cypress/support/index.ts, tests/cypress/support/stateSubmissionFormCommands.ts
This is the api side of the work for moving away from the updateDraftSubmission endpoint
https://qmacbis.atlassian.net/browse/MR-858
https://qmacbis.atlassian.net/browse/MR-856
I added tests for all the errors we can see in the API, I think. 
I haven’t touched the frontend code yet, I am worried I broke something.
=> [MR-858] Add updateHealthPlanFormData mutation to API

services/app-web/src/components/SubmissionSummarySection/SubmissionTypeSummarySection/SubmissionTypeSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/SubmissionTypeSummarySection/SubmissionTypeSummarySection.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx, tests/cypress/integration/stateWorkflow/dashboard/dashboard.spec.ts, tests/cypress/integration/stateWorkflow/stateSubmissionForm/reviewAndSubmit.spec.ts
[MR-2082](https://qmacbis.atlassian.net/browse/MR-2082)
Update dates on submission summary page and previous submission versions
- Remove `Submitted` field from previous submission page
- Changes `Submitted` field to display initial submission date
- Remove `Last Updated` field from submission summary
- Removed tests for `Last Updated` field.
=> MR-2082: Update dates on submission summary page and previous submission versions

services/app-api/emailer/templates.ts
Fix spacing in unlock emails.
**Before**
**After**
=> Fix spacing in unlock emails

.github/workflows/deploy-app-to-env.yml, .github/workflows/deploy.yml, .github/workflows/promote.yml, .vscode/settings.json, services/app-api/handlers/health_check.ts, services/app-api/package.json, yarn.lock
This adds LD to the `/health` api endpoint. It includes the appropriate secrets for each environment and is mainly for us to test enabling/disabling something via LD.
https://qmacbis.atlassian.net/browse/MR-402
=> Add LaunchDarkly to /health API endpoint

.github/workflows/deploy.yml, services/app-web/package.json, yarn.lock
This fixes an issue that cropped up on that latest promote, where an old OTEL package we don't use was still in `package.json` for `app-web`, causing a 404 on `yarn install` in promote. 
This also moves the `deploy` script to use `main` from the Launch Darkly PR merge.
=> Fix deploy and promote

services/storybook/serverless.yml, services/ui/serverless.yml, services/uploads/serverless.yml
This is a follow on for the s3 bucket security hub findings we have in our environment. This adds a rule that denies unencrypted traffic from our buckets (not that we have any anyways).
https://qmacbis.atlassian.net/browse/MR-2066
=> Add more encryption policies

services/app-api/serverless.yml
This threads in the LD SDK key into one last place. There are separate ones for dev/val/prod added to CI already.
=> Add LD_SDK_KEY env variable to app-api serverless

services/app-web/src/components/ChangeHistory/ChangeHistory.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/ReviewSubmit.tsx, services/app-web/src/pages/StateSubmission/StateSubmissionForm.tsx, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx, tests/cypress/support/stateSubmissionFormCommands.ts
After renaming everything, I have cleaned up some of our apollo cache usage to be consistent.
Apollo uses its cache by default to respond to requests if there is data in the cache that matches the query. So, for instance, in our app, moving between different pages of the app doesn’t cause new requests to fetch the HealthPlanPackage every time because useFetchHPPQuery() knows that it is asking for a single record with the given ID and that already exists in the cache. 
That’s quite straightforward for queries, if we’ve queried it before its in the cache and won’t be re-queried, but mutations can modify the actual state of things, so how does that work?
By default, if your mutation return all of the mutated objects, they are inserted into the cache automatically. So, now, with our update, …
=> Fix apollo cache usage

.github/dependabot.yml
Back when our CI was slower and we weren't using lerna with yarn workspaces, dependabot was causing a lot of noise for us. We decided to limit how often dependabot was checking for updates and limited it to 4 open slots in our PRs. 
We're in a better place now, so this has dependabot checking daily. We can tweak it again if it becomes too noisy.
=> Add more dependabot

.github/workflows/deploy.yml, .github/workflows/promote.yml
This moves the ref on `deploy-app` back to main. 
It also fixes an issue with the upload artifact not being run on promote.
=> Move ref back to main

services/app-api/scripts/prepare-prisma-layer.sh
This removes an extra prisma `libquery_engine` from our layer. It wasn't showing up in earlier PR branches, but came up during the CRA/webpack 5 upgrade merge.
=> don't use @prisma/engine in layer

services/app-web/src/pages/StateSubmission/ReviewSubmit/ReviewSubmit.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/ReviewSubmit.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.test.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx
Error message on the unlock modal have been updated to: "You must provide a reason for unlocking this submission"
Error message on the resubmit modal have been updated to:  "You must provide a summary of changes"
Tests have been updated to mach copy changes.
=> Update error copy on unlock and resubmit modals and fix tests

services/app-api/prisma/migrations/20220425194642_drop_pre_pilot_data/migration.sql
We have a lot of data in the db that is out of date, especially protos that no longer decode, we decided to wipe the whole db and start over. 
https://qmacbis.atlassian.net/browse/MR-2083
Make sure the review app still works, it should lose the first run of Cypress data that was in there.
=> [MR-2083] Drop pre-pilot data

services/app-api/package.json, yarn.lock
There is something weird happening with this branch and how the CI is running it. Trying to fix by opening it with a new branch name.
Bumps [@apollo/gateway](https://github.com/apollographql/federation/tree/HEAD/gateway-js) from 0.48.1 to 2.0.1.
- [Release notes](https://github.com/apollographql/federation/releases)
- [Changelog](https://github.com/apollographql/federation/blob/main/gateway-js/CHANGELOG.md)
- [Commits](https://github.com/apollographql/federation/commits/@apollo/gateway@2.0.1/gateway-js)
=> Bump @apollo/gateway from 0.48.1 to 2.0.1

.github/workflows/deploy.yml
This moves the deploy workflow back to pointing at main since #940 merged.
=> Move branch ref back to main

services/app-web/src/documentHelpers/makeDocumentDateLookupTable.test.ts, services/app-web/src/pages/StateSubmission/ReviewSubmit/ReviewSubmit.tsx, services/app-web/src/pages/StateSubmission/StateSubmissionForm.tsx
[MR-2094](https://qmacbis.atlassian.net/browse/MR-2094)
Date missing from documents from Review/Submit page. 
Repeated the code from `SubmissionSummary` that generates the document dates in `StateSubmissionForm`. This is passed to `ReviewSubmit` which is then passed to `ContractDetailsSummarySection` and `RateDetailsSummarySection`. 
- makeDocumentDateLookupTable.test
- should use earliest document added date
=> MR-2094: Date missing from documents table on unlocked review and submit page

.envrc
If a developer doesn't have the appropriate environment variable set in their `.envrc.local` for the Launch Darkly `app-web` setup, the web application will not start up. This has caused a bit of confusion.
This PR adds a dummy var to `.envrc` itself so the application will start (it just won't have feature flags running in local dev). If a developer wants to add a live key they can do so by entering our client side key from our LD account into `.envrc.local`.
=> Add env var for LD client 

services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.tsx
[MR-2217](https://qmacbis.atlassian.net/browse/MR-2217)
`Does the actuary certify capitation rates specific to each rate cell or a rate range?` on review/submit and summary pages displayed incorrect data.
- `RateDetailsSummarySection.test.tsx`
- `renders rate cell capitation type`
- `renders rate range capitation type`
=> [MR-2217] Capitation rates specification on review/submit and summary pages displaying incorrect data

services/app-api/src/resolvers/submitHealthPlanPackage.test.ts
My initial fix for this issue didn’t take. It looks like I might have set the timeout incorrectly. I’ve also added some debug logging to see how far we are making it in the test before it times out. 
It’s still very possible that this timeout won’t fix things if the issue is about the sidecar db not being available instead of the test having a 2 second delay in it. Hopefully the debug printing will help narrow that down. 
https://qmacbis.atlassian.net/browse/MR-2147
=> [MR-2147] Set timout correctly on our api test that keeps timing out

services/app-web/src/pages/App/App.tsx, services/app-web/src/pages/App/AppBody.module.scss, services/app-web/src/pages/App/AppBody.test.tsx, services/app-web/src/pages/App/AppBody.tsx
Add banner.
Bonus:  strip out the jira collector from the frontend (cc: @MegMurphy, my understanding is this is no longer needed )
https://qmacbis.atlassian.net/browse/MR-2235
- shows test environment banner in val
- does not show test environment banner in prod
=> [MR-2235] Add test environment banner to val and dev environments

.github/workflows/deploy.yml
Our CI started failing due to not being able to find the appropriate tag on the `deployment-action` action. This upgrades us to the latest release.
=> Update deployment-action GHA

services/app-api/src/emailer/templates.test.ts, services/app-api/src/emailer/templates.ts, services/app-api/src/testHelpers/emailerHelpers.ts
[MR-2324](https://qmacbis.atlassian.net/browse/MR-2324)
Add logic for CHIP health plan package reviewer emails.
- templates.test.ts
- `CHIP contract only submission does not include ratesReviewSharedEmails and cmsRateHelpEmailAddress`
- `CHIP contract and rate submission does not include ratesReviewSharedEmails and cmsRateHelpEmailAddress`
- `CHIP contract only unlock email does not include ratesReviewSharedEmails and cmsRateHelpEmailAddress`
- `CHIP contract and rate unlock email does not include ratesReviewSharedEmails and cmsRateHelpEmailAddress`
- `CHIP contract and rate resubmission does not include ratesReviewSharedEmails and cmsRateHelpEmailAddress`
- `CHIP contract only resubmission does not include ratesReviewSharedEmails and cmsRateHelpEmailAddress`
=> [MR-2324] DMCP & OACT do not receive CHIP emails

services/app-api/src/resolvers/indexHealthPlanPackages.test.ts, services/app-web/src/common-code/healthPlanFormDataType/healthPlanFormData.test.ts, services/app-web/src/common-code/healthPlanFormDataType/healthPlanFormData.ts
Reorder the submssion name to put the number before programs. 
https://qmacbis.atlassian.net/browse/MR-2321
shockingly the only tests that broke were the ones related to the name generation code.
=> [MR-2321] reorder submission id to have number before programs

services/app-api/src/handlers/bulk_download.ts, services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.tsx, services/app-web/src/s3/s3Amplify.ts
[MR-2333](https://qmacbis.atlassian.net/browse/MR-2333)
Fixed by encoding file names in `s3Amplify.ts` then decoding in `bulk_download.ts`. 
Ticket [2335](https://qmacbis.atlassian.net/browse/MR-2335) for inconsistent file names when downloading a single document.
- **Please make sure to test on Chrome/Safari/Edge/Firefox and windows machine.**
=> [MR-2333] Files with commas in the name throw errors in Edge and Chrome

services/app-web/src/components/Footer/Footer.module.scss, services/app-web/src/components/SubmissionSummarySection/ContactsSummarySection/ContactsSummarySection.tsx
[MR-76](https://qmacbis.atlassian.net/browse/MR-76)
Fixed styling of the contact email links. Changed the email links to use `Link` from react-uswds and opening up new tab when clicking on email link.
**NOTE** Also fixed the feedback email text color in the footer to be white after visited.
=> [MR-76] Link styling for contact emails is the wrong shade of blue

services/app-api/src/postgres/insertHealthPlanRevision.ts, services/app-web/src/pages/App/App.tsx
[MR-25](https://qmacbis.atlassian.net/browse/MR-25)
Recently unlocked submissions should be at top of submission dashboard. Unlocking a submission was not updating the `updatedAt` field in the `protobuf` data. Add `args.draft.updatedAt = new Date()` in `insetHealthPlanRevision.ts` function updates the field when unlocking.
=> [MR-25] Recently unlocked submissions should be at top of submission dashboard

services/app-web/src/constants/localStorage.ts, services/app-web/src/hooks/useLocalStorage.ts, services/app-web/src/pages/App/AppRoutes.tsx
Add new `useLocalStorage` hook and a constants file for local storage key values. 
Prep for https://qmacbis.atlassian.net/browse/MR-897 I want to be able to quickly add a new keys to local storage and have error handling if local storage is already full or JSON.parse fails.  In the case of this bug want to track if a user is coming back from a failed login 
- This hook can be tested within the components where it is used. For example, we already have CMS unlock and resubmit tests that test that the hook is working when a CMS user tries to visit a submission url directly (and is redirected through Auth flow and then login) 
Test that IDM local is working as expected for CMS user visiting a specific submission URL
=> Add useLocalStorage hook

.github/workflows/deploy-infra-to-env.yml, services/postgres/serverless.yml
Serverless v3 uses a new hashing function for lambdas. Since we use the AWS supplied function for secrets manager rotation, we'll need to [tell serverless to update the hashing algo](https://www.serverless.com/framework/docs/guides/upgrading-v3#lambda-hashing-algorithm) used. We can remove this once it goes through promote once.
=> Enforce the v3 hashing update on an unchange func

.github/workflows/deploy-infra-to-env.yml
Since #1027 was used for the Serverless v3 upgrade, we can remove this one time deploy option now that it has rolled out to dev/val/prod.
=> No longer need --enforce-hash-update

services/infra-api/serverless.yml, services/postgres/serverless.yml, services/ui-auth/serverless.yml, services/uploads/package.json, services/uploads/serverless.yml
In the Serverless v3 upgrade we moved to using the ${aws.accountId} variable replacement syntax, but it looks like it's causing some issues with the `serverless-s3-local` plugin. It also doesn't have a fallback value. Since the ${AWS::AccountId} syntax is still available, let's just use that, as it seems to work fine and doesn't cause s3 local to break.
Fixes:
https://qmacbis.atlassian.net/browse/MR-2378
https://qmacbis.atlassian.net/browse/MR-2375
=> Move to AWS::AccountId

.github/workflows/deploy.yml, .github/workflows/promote.yml
The merge of #1050 had a couple dangling vars left over which caused promote to fail. This fixes that and reverts the sha back to `main`.
=> Remove unused vars in promote.yml

docs/Configuration.md
This adds guidance around setting the environment variables needed for using Launch Darkly in the application.
=> Add LD key guide to docs/Configuration.md

.codeclimate.yml
eslint has been erroring in code climate every single time for more than a month now. It might be a version mismatch problem, we install 8 but code climate only goes to 7. I’m turning it off so that Stephanie Copell doesn’t keep getting inundated with emails about the errors. 
Example failure: https://codeclimate.com/repos/616dbb175e8227015001784f/builds/2851
=> turn off eslint in code climate b/c it is erroring

.github/workflows/deploy.yml
We'd like to have dependabot PRs run through CI without needing to be manually triggered by an engineer. This gives PRs opened by dependabot write access via the `GITHUB_TOKEN` so that our review apps can be created.
=> Change deploy.yml GH permissions for dependabot

.github/workflows/deploy.yml
This adds onto #1079, adding the `GITHUB_SECRET` permissions to the last phase of CI for dependabot.
=> Add GH permissions to 'end-deployment' and 'cypress'

services/app-web/serverless.yml
Maz had been seeing some CI issues in `app-web` where the serverless deploy would hit an OOM. We fixed it in his branch, but it looks like it got reverted with #1075 . This adds it back in order to avoid those occasional GHA OOMs in `app-web`.
=> Run app-web serverless serially

services/app-web/src/components/FileUpload/FileProcessor/FileProcessor.tsx, services/app-web/src/components/ProgramSelect/ProgramSelect.stories.tsx, services/app-web/src/components/ProgramSelect/ProgramSelect.test.tsx, services/app-web/src/components/ProgramSelect/ProgramSelect.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetailsSchema.ts, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx
[MR-2485](https://qmacbis.atlassian.net/browse/MR-2485)
Seems like the issue was the `name` prop for `Select` component was not applying or incorrectly applying to the `input` element used in the component. Then focusing using the `name` attribute did not work. 
The fix was to pass `inputId` to `Select` component from `react-select` and then focus using `id` instead of `name` attribute. Then refactor forming error object passed into `ErrorSummary` to select `rateProgramIDs/programIDs` by adding `#` in front of each key. As described in the comments in `ErrorSummary` adding an `#` will switch from focusing using `name` to `id` attribute.
1. Please make sure `rate-certificiation-programs` feature flag is enabled in LaunchDarkly.
2. On the Submission type or Rate Details page, leave the …
=> [MR-2485] Program selection combobox not focused when error clicked

services/storybook/serverless.yml
This should fix the certificate issues with Storybook. When we moved to using Parameter Store for configuration values there was a typo in the `serverless.yml` that caused the logic in the configuration to not deploy the subdomain needed.
https://qmacbis.atlassian.net/browse/MR-2531
=> Fix storybook certificate

services/app-web/src/common-code/dateHelpers/index.ts, services/app-web/src/common-code/dateHelpers/mostRecentDate.test.ts, services/app-web/src/common-code/dateHelpers/mostRecentDate.ts, services/app-web/src/common-code/featureFlags/flags.ts, services/app-web/src/common-code/healthPlanFormDataMocks/healthPlanFormData.ts, services/app-web/src/common-code/healthPlanFormDataType/State.ts, services/app-web/src/common-code/healthPlanFormDataType/healthPlanFormData.ts, services/app-web/src/common-code/healthPlanFormDataType/index.ts, services/app-web/src/components/Header/EmptyHeader.tsx, services/app-web/src/pages/CMSDashboard/CMSDashboard.test.tsx, services/app-web/src/pages/CMSDashboard/CMSDashboard.tsx, services/app-web/src/pages/Errors/ErrorBoundaryRoot.tsx, services/app-web/src/pages/Errors/Errors.module.scss, services/app-web/src/pages/StateDashboard/StateDashboard.tsx, services/app-web/src/testHelpers/apolloHelpers.tsx, tests/cypress/integration/cmsWorkflow/unlockResubmit.spec.ts, tests/cypress/integration/cmsWorkflow/viewSubmission.spec.ts, tests/cypress/support/loginCommands.ts
- remove CMS_DASHBOARD feature flag
- Add last updated column and in general move from looking at current revision to previous submitted revision for form data. That's something I overlooked in the first pass at the dashboard, likely this would cause bugs.
https://qmacbis.atlassian.net/browse/MR-2466
**Jest**
see `CMSDashboard.test.tsx` (web tests)
- displays no submission text when no submitted packages exist
- displays submissions table when submitted packages exist
- displays submissions table with expected headers
- displays submissions table excluding any in progress drafts
- displays submission type as expected for current revision that is submitted/resubmitted
- displays the expected program tags for current revision that is submitted/resubmitted
- displays each health plan package …
=> Add last updated to CMS Dashboard

.envrc, docs/Configuration.md, services/app-api/serverless.yml, services/app-api/src/handlers/apollo_gql.ts, services/app-api/src/parameterStore/emailParameterStore/cmsReviewSharedEmails/getCmsReviewSharedEmails.ts, services/app-api/src/parameterStore/emailParameterStore/emailParameterStore.ts, services/app-api/src/parameterStore/emailParameterStore/index.ts, services/app-api/src/parameterStore/emailParameterStore/ratesReviewSharedEmails/getRatesReviewSharedEmails.ts, services/app-api/src/parameterStore/emailParameterStore/stateAnalystsEmails/getStateAnalystsEmails.test.ts, services/app-api/src/parameterStore/emailParameterStore/stateAnalystsEmails/getStateAnalystsEmails.ts, services/app-api/src/parameterStore/index.ts, services/app-api/src/testHelpers/parameterStoreHelpers.ts, tests/cypress/integration/stateWorkflow/stateSubmissionForm/submissionType.spec.ts
[MR-2539](https://qmacbis.atlassian.net/browse/MR-2539)
This will change `cmsReviewSharedEmails` and `ratesReviewSharedEmails` that was set using ENV variables to be pulled directly from parameter store. This is exactly how we are pulling state analyst emails. 
Also removed `SES_REVIEW_TEAM_EMAIL_ADDRESSES` and `SES_RATES_EMAIL_ADDRESSES` from `app-api/serverless.yml` and `.envrc`
=> MR-2539: Move getting some emails to email parameter store

services/app-api/serverless.yml
I accidentally removed `'/configuration/email/reviewHelpAddress': ${env:SES_REVIEW_HELP_EMAIL_ADDRESS, 'offline'}` from `app-api/serverless.yml` when making the bug fix for automated emails. This should have only affected local deployment.
=> Add back env:SES_REVIEW_HELP_EMAIL_ADDRESS to serverless yml

services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.test.tsx, yarn.lock
Removed `ldUseClientSpy` from test not testing feature flag code.
When `yarn install` from `main` this new `yarn.lock` file was generated. Pushing up to keep subsequent branches from having this generated.
=> Add new yarn lock and remove ld use client spy from single test

services/app-api/src/resolvers/updateHealthPlanFormData.ts
[MR-2405](https://qmacbis.atlassian.net/browse/MR-2405)
We received a production error while RI was filling out a submission in prod: New Relic (NR) error `Attempted to modify un-modifiable field(s): updatedAt` and on updating a draft submission we get this error in the api on every draft update done in the `updateHealthPlanFormData.ts` resolver.
```
api| ERRMOD id: old: baef1ccc-8715-40a7-98a6-e8051c5eec6b new: baef1ccc-8715-40a7-98a6-e8051c5eec6b
api| ERRMOD stateCode: old: MN new: MN
api| ERRMOD stateNumber: old: 1 new: 1
api| ERRMOD createdAt: old: Tue Jun 28 2022 20:00:00 GMT-0400 (Eastern Daylight Time) new: Tue Jun 28 2022 20:00:00 GMT-0400 (Eastern Daylight Time)
api| ERRMOD updatedAt: old: Wed Jun 29 2022 16:13:14 GMT-0400 (Eastern Daylight Time) new: Wed Jun 29 2022 16:13:14 …
```
=> MR-2405: Error in updatedAt on draft submission

services/app-api/src/resolvers/submitHealthPlanPackage.test.ts, services/app-api/src/resolvers/updateHealthPlanFormData.test.ts, services/app-api/src/resolvers/updateHealthPlanFormData.ts, services/app-web/src/common-code/healthPlanFormDataType/healthPlanFormData.test.ts, services/app-web/src/common-code/healthPlanFormDataType/healthPlanFormData.ts, services/app-web/src/common-code/healthPlanFormDataType/index.ts, services/app-web/src/components/FileUpload/FileUpload.tsx, services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.tsx
[MR-2566](https://qmacbis.atlassian.net/browse/MR-2566)
Fixed a bug where converting `Rate-supporting` docs to `Contract-supporting` when changing from `Contract and Rate` submission to `Contract Only` was not displaying previously `Rate-supporting` documents as `Contract supporting documents` on the `Review and Submit` page. 
Add code to convert `Rate-supporting` docs to `Contract-supporting` in `updateHealthPlanFormData.ts` resolver and removing code in `FileUpload.tsx` that converted `Rate-supporting` docs to `Contract-supporting` when changing from `Contract and Rate` submission to `Contract Only`. This will handle the converting of documents at the time of changing from `Contract and Rate` submission to `Contract Only` on the `Submission Type` page. …
=> MR-2566: Rate-supporting documents not converting to Contract-supporting when switching submission types

services/app-web/src/common-code/featureFlags/flags.ts, services/app-web/src/pages/Landing/Landing.test.tsx, services/app-web/src/pages/Landing/Landing.tsx
This came up during incident response.  We want to use LD to easily toggle on a site maintenance flag when we have an issue to communicate to users (in this case the API was down for an unexpected reason due to AWS outage).
n/a 
Added tests for flag on and off state.
=> Add site maintenance banner and feature flag

docs/templates/decision-record-template.md, docs/templates/technical-design-template.md
Add a templates folder so we have example templates on which to base our documentation. 
We can add more templates in the future as needed. For example I was thinking a "How to" template might be nice since some of the docs in the design docs folder are more how to style documentation.
=> Add templates folder, ADR and design doc templates

services/app-web/src/common-code/featureFlags/flags.ts, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.test.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx, tests/cypress/integration/stateWorkflow/stateSubmissionForm/rateDetails.spec.ts, tests/cypress/support/stateSubmissionFormCommands.ts
Remove the multi program rates flag from codebase.
https://qmacbis.atlassian.net/browse/MR-2591
I adjusted tests that referenced the flag and removed a test that tested if the flag worked. 
Check that multi-program rates workflows work as expected.
=> Remove rate_certification_programs flag

.github/workflows/deploy-app-to-env.yml, .github/workflows/deploy.yml, .gitignore, services/app-api/scripts/prepare-prisma-layer.sh, services/app-api/serverless.yml, services/app-api/src/handlers/postgres_migrate.ts, services/app-api/webpack.config.js, services/app-proto/package.json, services/app-proto/tsconfig.json
This fixes up the CI process around importing migration scripts into the migrator. It turns out that there is a bug in AWS lambda environments where imports cannot come from lambda layers. There are [some](https://github.com/vibe/aws-esm-modules-layer-support) [hacks](https://github.com/coderbyheart/aws-lambda-esm-with-layer) to work around this limitation, but here we're just moving away from using the layer altogether and instead using webpack. 
We compile the scripts from `app-proto` and then use copy webpack to move them into the bundle. 
https://qmacbis.atlassian.net/browse/MR-2614
=> Fix error in protobuf data migrator imports

services/postgres/serverless.yml
The default [Aurora DeletionPolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html) for `AWS::RDS::DBCluster` is `Snapshot`. This is fine for `val` and `prod`, where we do want to retain snapshots in the unlikely situation that our DB gets deleted. For our testing environments this is unnecessary, as there is only test data in the DB and each snapshot takes up AWS resources.
This configures it to delete snapshots when we're in any environment other than `val` and `prod`
https://qmacbis.atlassian.net/browse/MR-958
=> Configure Postgres Aurora DeletionPolicy

services/app-web/src/components/FileUpload/FileUpload.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.tsx
We now allow users to assign programs to rates (rateProgramIDs), as we've always done for submissions as a whole (with programIDs).  But that means older submissions don't have user-selected program names for their rates.  This PR falls back to program IDs to fill in program names for rates from older submissions.
Added a test to check that the fallback works.  The real test will be pulling up older submissions in a deployed environment and seeing program names in the rate detail section.
=> MR-2464: Fill in rate program names from programIDs

services/app-web/src/components/DynamicStepIndicator/DynamicStepIndicator.tsx, services/app-web/src/components/Header/Header.test.tsx, services/app-web/src/components/Header/Header.tsx, services/app-web/src/constants/routes.ts, services/app-web/src/constants/tealium.ts, services/app-web/src/hooks/useCurrentRoute.ts, services/app-web/src/hooks/useTealium.ts, services/app-web/src/pages/App/AppRoutes.tsx, services/app-web/src/pages/StateSubmission/StateSubmissionForm.tsx
The page_view events were not being properly associated in google analytics. There was some bad or just confusing data (things like `undefined: Home`, `Home: Home`, `Dashboard:Dashboard`  being logged).  I added a function to better determine the name of pages, particularly with a shared route (such as ROOT `/`)
I've also added new types `RouteTWithUnknown` to reflect a type that is already used in the app currently in a few places. 
This is a small part of MR-2572 I can complete now without waiting for response to Blast ticket. 
https://qmacbis.atlassian.net/browse/MR-2572 
If you navigate through the app locally you can see the mock Tealium event console log showing what page name would be logged. 
**Note to reviewers 😄 :** 
Even though the page names are now more correct you will see …
=> Improve page view logging in Tealium 

.github/workflows/deploy.yml, .github/workflows/promote.yml
The recently merged #1233 had a missing step in the promote script. This also swaps back the deploy script to use `main`.
=> Fix promote GHA

services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx
[MR-2231](https://qmacbis.atlassian.net/browse/MR-2231)
First rate-certification in multi-rate submission on Rate Details page should not be removable.
=> First rate-certification in multi-rate submission on Rate Details page should not be removable.

services/app-api/src/emailer/emails/__snapshots__/newPackageStateEmail.test.ts.snap, services/app-api/src/testHelpers/emailerHelpers.ts
Using `new Date()` in `emailerHelpers.ts` mocks caused snapshots generated on different dates to fail. Updated mocks in `emailerHelpers.ts` to use static dates and updated snapshot.
=> Fix emailer api snapshot test failures

services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx
[MR-2231](https://qmacbis.atlassian.net/browse/MR-2231?focusedCommentId=114581)
The new array is added when `FileUpload` component calls `onFileItemsUpdate` to update `fileItemsMatrix` with the files for the specific rate certification. `getDocumentsError` ran before a new array was added into `fileItemsMatrix` state so using any array method caused crashes. 
The fix was to push in new empty array into `fileItemsMatrix` when clicking on `Add another rate certification`.
=> Fix system error when adding additional rate when existing rates have incompletion errors.

services/app-api/serverless.yml, services/infra-api/package.json, services/infra-api/serverless.yml, yarn.lock
This adds the serverless waf setup that the macpro-quickstart team asked us to add. We are not using the external plugin that does the [auto association](https://github.com/MikeSouza/serverless-associate-waf), which is how CMS was suggesting we implement this, as that would require us to change our API Gateway names (they are not customizable in the plugin). Instead, we're using a regular CF associate stanza in `app-api`.
https://qmacbis.atlassian.net/browse/MR-2593
=> Add Serverless Waf Plugin

services/app-api/src/handlers/health_check.ts, services/app-web/src/common-code/featureFlags/flags.ts
Remove two flags from codebase that are no longer used. `app-api-graphql-errors` had no remaining code references so its just a constant change for that flag. 
https://qmacbis.atlassian.net/browse/MR-2630
=> Remove enable-health-endpoint and app-api-graphql-errors from codebase

services/app-api/serverless.yml
There are a couple IAM permissions that need to be added to our lambda in order for RDS snapshot deletion to occur. This adds the attributes.
https://qmacbis.atlassian.net/browse/MR-2589
=> Add additional IAM properties to cleanup task

.github/actions/setup_env/action.yml
Cleanup task after seeing warning in Github about using outdated Node versions in CI. Bring setup_env workflow setup-node  action to current major version - v3 This matches deploy and promote workflows.
=> Move all actions/setup-node to v3

services/app-web/src/common-code/proto/healthPlanFormDataProto/toLatestVersion.ts
Comment out the console log here. I do think it would be nice to have OTEL know when an old proto is opened (if we had to debug unexpected behavior with toLatestVersion) but not sure right now where that should connect into the active spans. 
https://qmacbis.atlassian.net/browse/MR-2761
=> Remove excessive console logs

tests/cypress/support/e2e.ts
Follow up from eng sync. Use console trace to have a better chance of actually returning a useful stack trace here. Cypress debugger is more used for debugging cypress but we know we have JS issues if we land in this helper.
=> Replace cypress debugger with console.trace in uncaughtException helper

services/app-web/src/components/Select/PackageSelect/PackageSelect.tsx, services/app-web/src/components/Select/ProgramSelect/ProgramSelect.tsx, services/app-web/src/components/Select/index.ts, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.test.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx
- Add label and  "View all submissions" link to the PackageSelect'
- Wrap the related fields in same Form Group - so error styles show for the entire block
- Export types for select options
Add on to #1332 
https://qmacbis.atlassian.net/browse/MR-2685
Here's how error styling will look now that both related fields are in same parent element.
=> [MD-2685] Add label and link to related submissions PackageSelect on Rate Details page 

.github/workflows/deploy.yml, .github/workflows/promote.yml
- Run promote in single thread
- Adjust deploy workflow to follow [docs](https://docs.cypress.io/guides/continuous-integration/github-actions#Using-Cypress-Cloud-with-GitHub-Actions) more closely  (seperate install step, share that build with parallelized tests) 
https://qmacbis.atlassian.net/browse/MR-2789
=> Adjust promote, deploy workflows for Cypress flakes

.github/workflows/promote.yml
Trying to address this [issue](https://docs.cypress.io/guides/references/error-messages#Run-is-not-accepting-any-new-groups) which cropped up when we removed parallelization on promote runs. This is currently blocking deploy to prod.
=> Address bug with promote workflow

.github/workflows/promote.yml
This came out of today's engineering sync - I took the AI to further simplifying our promote workflow and chance of flakes by removing Cypress from steps. 
Welcome reviews or adjustments to the PR, not sure how I feel about skipping val when I see it in code. Maybe we just skip dev. 
Follow on to #1337 and #1341 after more discussion
=> Remove Cypress checks for dev/val on promote to prod workflow

services/app-proto/src/health_plan_form_data.proto, services/app-web/src/common-code/healthPlanFormDataType/UnlockedHealthPlanFormDataType.d.ts, services/app-web/src/common-code/proto/healthPlanFormDataProto/toDomain.ts, services/app-web/src/common-code/proto/healthPlanFormDataProto/unlockedHealthPlanFormDataSchema.ts, services/app-web/src/components/Select/PackageSelect/PackageSelect.tsx, services/app-web/src/components/Select/ProgramSelect/ProgramSelect.tsx, services/app-web/src/components/Select/index.ts, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/UploadedDocumentsTable/UploadedDocumentsTable.module.scss, services/app-web/src/components/SubmissionSummarySection/UploadedDocumentsTable/UploadedDocumentsTable.tsx, services/app-web/src/gqlHelpers/healthPlanPackages.ts, services/app-web/src/pages/StateDashboard/StateDashboard.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.test.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.test.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx, services/app-web/src/pages/SubmissionSummary/__snapshots__/SubmissionSummary.test.tsx.snap
MR-2587 replacement for #1338 
MR-2684
MR-2686
Finishes up several of the rates across submissions tickets.  Incorporates @haworku's code for 2587.
We should now see a "SHARED" tag on documents that the user has told us are shared with other submissions.
We should see a "Linked submissions" column when such a document exists.
That column should contain the name of the other submission, and a link to it.
We should see the most recent 5 submissions in the dropdown in RateDetails where we can select the linked submission.
Includes a refactor of the `packagesWithSharedRateCerts` type to include both the name and the id of a package.  Since this is behind a feature flag and there are no prod submissions using the old type, this change doesn't require any migration work.
New unit tests for when …
=> Rates across submissions (issue numbers in description)

.github/workflows/deploy.yml, services/app-api/scripts/prepare-prisma-layer.sh
Promote failed when #1349 merged due to a total package size for the `app-api` lambdas becoming larger than the max size AWS allows. It turns out that the migration and query engine Prisma layers that we build for the environment started getting a lib built for a Debian environment which we weren't excluding (`libquery_engine-debian-openssl-3.0.x.so.node`). I'm guessing this happened from a Prisma upgrade or from the CI environment's underlying OS having lib changes that went unnoticed in our CI layer builds.
This removes the unneeded lib for our AWS deployed layer to save space.
=> Remove new Prisma query engines for debian

services/app-api/src/authn/cognitoAuthn.ts, services/app-api/src/postgres/insertUser.ts
When testing out the newly merged Users table work in #1321 , the shared CMS dev user seems to be having issues with inserting into Aurora. This is due to a difference in attributes for a state vs CMS user. 
This adds a default value to the insert for a CMS user (state is empty), and will return the user from cognito if there is a failure in this code path (so as to not bring down the application fully).
=>  Fix cognitoAuth CMS vs State users with Aurora

services/app-api/prisma/migrations/20221206000520_remove_email_unique/migration.sql, services/app-api/prisma/schema.prisma
In our dev environment we can have user accounts that have non-unique email addresses. Since we aren't really gaining anything from this constraint (and have unique IDs from IDM), we'll drop this for now.
=> Remove `unique` constraint on User emails

services/app-api/serverless.yml, services/app-api/src/emailer/awsSES.ts, services/app-api/src/emailer/emailer.ts, services/app-api/src/handlers/email_submit.ts
This fixes a bug where sending email notifications through SES was throwing an error. This likely cropped up due to moving from the AWS v2 SDK to the newer v3 SDK and a change on how lambdas are invoked.
Instead of invoking a lambda handler to do the SES sending, this just uses SES on it's own.
https://qmacbis.atlassian.net/browse/MR-2867
=> Fix SES email sending

.github/workflows/deploy.yml
Some of our Cypress runs were throwing an error like this:
```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```
After some searching I [found a fix](https://repo1.dso.mil/platform-one/big-bang/apps/library-charts/gluon/-/issues/7) that creates a virtual monitor so that Cypress will run there, as there is an issue with Chrome on Linux that this works around.
=> Add Cypress monitor hack for Chrome in Linux

services/app-api/serverless.yml, services/app-web/serverless.yml
While working on the Cypress issues I noticed that requests from React to the OTEL endpoint were getting 403s. I'm not sure when this started, but switching to use the application endpoint with the authorizer instead of the api gateway endpoint clears those up it seems. This was working fine in the past, so I'm not sure what changed with the API gateway to make this start failing all of a sudden.
=> Fix OTEL endpoint requests from React

package.json, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx, yarn.lock
Lerna has had a significant upgrade and this brings us up to date with the 6.0 line. This just upgrades the package, we can have a follow on PR to include the use of the new Lerna caching layer.
This PR should allow us to land upgrades for packages that previously were held back due to transient lerna dependencies.
https://qmacbis.atlassian.net/browse/MR-2498
=> Upgrade Lerna to 6

.github/workflows/deploy.yml
This moves the sha for the deploy infra/app workflows back to main from the last PR merge.
=> Fix deploy sha

services/app-api/src/handlers/apollo_gql.ts, services/app-api/src/launchDarkly/launchDarkly.ts, services/app-api/src/resolvers/submitHealthPlanPackage.ts, services/app-api/src/testHelpers/launchDarklyHelpers.ts
API was originally throwing an error when LaunchDarkly client failed initialization and stopping `initializeGQLHandler()` from finishing. This stops the API meaning the app will not function without LaunchDarkly client initialization, which does not follow the pattern of using a fallback when LaunchDarkly is not available. 
This PR is to add a LaunchDarkly offline service if  LaunchDarkly client failed initialization. The offline service `offlineLDService` will use default values in `featureFlags.ts` to generate default flags values for use and log to NR indicating no connection to LaunchDarkly and using the fallback `offlineLDService`.
=> API LaunchDarkly offline service

docs/technical-design/launch-darkly-testing-approach.md
[MR-2592](https://qmacbis.atlassian.net/browse/MR-2592)
Added documentation on unit testing for client and server side. I also added a note on the limitations of the LaunchDarkly implementation into Cypress testing.
=> MR-2592: LaunchDarkly unit testing docs

docs/technical-design/adding-emails.md
The ticket was to add emails for NJ, but we thought there should also be instructions for this procedure.
=> MR-2956: Add instructions for adding state analyst emails

services/app-web/src/common-code/formatters/pluralizer.ts, services/app-web/src/components/HealthPlanPackageTable/HealthPlanPackageTable.module.scss, services/app-web/src/components/HealthPlanPackageTable/HealthPlanPackageTable.test.tsx, services/app-web/src/components/HealthPlanPackageTable/HealthPlanPackageTable.tsx, yarn.lock
We want to display a bit of text when users are using filters, so that they either see a total count of submissions, when no filters are applied, or a x of y count, when some are.  There should be no message when filters are applied but don't return anything.
Added lines to existing filter tests to also check the text when we filter.
=> MR-2881: Add count text for filters

services/app-web/src/components/Form/FieldTextInput/FieldTextInput.module.scss, services/app-web/src/components/Form/FieldTextInput/FieldTextInput.test.tsx, services/app-web/src/components/Form/FieldTextInput/FieldTextInput.tsx, services/app-web/src/components/Form/FieldTextarea/FieldTextarea.tsx, services/app-web/src/components/Form/FieldYesNo/FieldYesNo.stories.tsx, services/app-web/src/components/Form/FieldYesNo/FieldYesNo.tsx, services/app-web/src/pages/StateSubmission/Contacts/ActuaryContactFields.tsx, services/app-web/src/pages/StateSubmission/Contacts/Contacts.test.tsx, services/app-web/src/pages/StateSubmission/Contacts/Contacts.tsx, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.tsx
Looking for feedback on the approach. I tried addressing the bug in two ways
- Using `.trim` in yup validations. This ensures validation error is simply not raised. See 482e326ea69c9bc0f161dbfe9ab047410aca1fe5 
- Direct remove leading and trailing whitespace from the input value itself `onBlur` to prevent this class of issue from arising, at least where our app-wide components are used . See 6ccda52dc6f5825503d1c6d447da43b887eaad4d 
Other change in this PR is slimming contacts and actuary contacts JSX by using `<FieldTextInput />` to remove extraneous markdown. 
https://qmacbis.atlassian.net/browse/MR-2542
- Besides testing bugfix to email address inputs, worth running through contacts and actuary contacts UI, make sure I didn't cause a regression here. Seems like we are testing with unit …
=> fix: MR-2542 Ensure that trailing spaces in email address inputs do not trigger errors

services/app-web/src/components/FilterAccordion/FilterAccordion.tsx, services/app-web/src/components/HealthPlanPackageTable/HealthPlanPackageTable.test.tsx, services/app-web/src/components/HealthPlanPackageTable/HealthPlanPackageTable.tsx
[MR-2872](https://qmacbis.atlassian.net/browse/MR-2872)
CMS dashboard page
- Screen reader reads filter applied and submission displayed on CMS dashboard page. 
- Reads on page load.
- Reads on filter change.
- Moved filter applied text to outside filter accordion, above submission count.
- Edit text for filter applied and submission count
State dashboard page
- Screen reader reads submission displayed on state dashboard page.
- Reads on page load
[Slack](https://cmsgov.slack.com/archives/C014CRU197U/p1673366114809069)
[Slack](https://cmsgov.slack.com/archives/C014CRU197U/p1673368036654629)
=> MR-2872: filters applied announced in screenreader

services/app-web/src/components/HealthPlanPackageTable/HealthPlanPackageTable.stories.tsx, services/app-web/src/components/HealthPlanPackageTable/HealthPlanPackageTable.test.tsx, services/app-web/src/components/HealthPlanPackageTable/HealthPlanPackageTable.tsx
Add a11y handling tweaks to table
- optional caption prop 
- `scope` attribute to specify that th header cell is a header for a column
- Use `showFilters` prop to determine if filtering language used in aria-live so its not possible to get into state where filters are off but text announces as if filters in place. 
See https://github.com/trussworks/accessibility/wiki/Tables
related to #1436 
- Added new test for caption. Had to edit several tests to pass filters prop for when we are testing filters
Running through table in screenreader.
=> Add caption prop, scope tag to HealthPlanPackageTable

services/app-api/src/authn/cognitoAuthn.test.ts, services/app-api/src/authn/cognitoAuthn.ts, services/app-api/src/domain-models/UserType.d.ts, services/app-api/src/resolvers/healthPlanPackage/createHealthPlanPackage.test.ts, services/app-web/src/localAuth/LocalLogin.tsx, services/app-web/src/localAuth/LocalUserType.ts, services/app-web/src/localAuth/localAuth.test.ts
Local Login failed after merging in the new User work. There was a type mismatch between the graphQL type which required ID and the domain type which did not. In trying to return a user without a type we got a graphql error. 
It’s not clear to me exactly why this is working fine for non-local users, but this fix makes me think it should work all the time.
Pull this branch and try and log in locally
also try and log in to the review app
=> Make User.id mandatory, resolve local login error

services/app-web/src/components/Form/FieldYesNo/FieldYesNo.tsx, services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.tsx
Small bugfix from product acceptance. See conversation on each ticket and commit history for context.
- https://qmacbis.atlassian.net/browse/MR-314
- https://qmacbis.atlassian.net/browse/MR-2962
- shows missing field error on amended provisions when expected
- does now show missing field error on amended provisions when fields are valid
Manual QA for MR-314 steps
- Log in as a state user and view the review/submit page on an unlocked submission where this field was not filled out on initial submission (you can get here by turning flag off, adding sub, unlocking, then turning flag on).
-  As expected, there is an error message shown on the review and submit page indicating this field is required. 
- Click edit on the submission type section and navigate to submission type page. 
- Leave …
=> fix: MR-2962 MR-314 for product acceptance

scripts/get-changed-services/index.ts, scripts/tsconfig.json
Occasionally the CI skipping script will throw an error that the git sha that it is comparing against can't be found. This adds a check for that and will run CI deploys for all services if it encounters that error.
https://qmacbis.atlassian.net/browse/MR-100
=> Fix CI skipping script when sha can't be found

services/app-web/src/common-code/featureFlags/flags.ts, services/app-web/src/components/ErrorAlert/ErrorAlert.module.scss, services/app-web/src/components/ErrorAlert/ErrorAlert.tsx, services/app-web/src/components/ErrorAlert/ErrorAlertScheduledMaintenance.tsx, services/app-web/src/components/ErrorAlert/index.ts, services/app-web/src/components/Header/Header.tsx, services/app-web/src/components/Header/UserLoginInfo/UserLoginInfo.test.tsx, services/app-web/src/components/Header/UserLoginInfo/UserLoginInfo.tsx, services/app-web/src/components/index.ts, services/app-web/src/constants/errors.ts, services/app-web/src/pages/App/AppBody.test.tsx, services/app-web/src/pages/App/AppBody.tsx, services/app-web/src/pages/Landing/Landing.test.tsx, services/app-web/src/pages/Landing/Landing.tsx
I made a new launch darkly flag to replace the current LD flag that has variations instead of just being a bool. Setup that flag to control the new scheduled maintenance alert vs. the unschedule maintenance alert. 
Moved that alert up from the landing page to AppBody. 
* This means that it shows no matter where someone is in the app
* I haven’t investigated if that would mean there would be data loss if someone left a tab open in our app when maintenance started, I think that risk is worth investigating but not before our first maintenance tomorrow that we have notified people about. 
* It means that whatever page someone is on disappears, replaced by the banner. This too is something we can revisit after tomorrow but would require a lot more changes (each page would need to display the …
=> update maintenance banner

services/app-web/src/components/FilterAccordion/FilterAccordion.tsx, services/app-web/src/components/HealthPlanPackageTable/HealthPlanPackageTable.test.tsx, services/app-web/src/components/HealthPlanPackageTable/HealthPlanPackageTable.tsx
There were a few outstanding issues from putting the filter state into the URL.
1) Focus was lost on the clicked element on rerender.  This fixes that.
2) A Typescript warning was being silenced. Using react-table's provided types and letting Jotai infer from those fixed that issue.
3) The URL is still URI encoded and hard to read.  This was partially addressed.  We can turn off encoding _within_ the values, but not between the values.  For example, what was 
```Contract%2520action%2520and%2520rate%2520certification``` 
is now  
```Contract+action+and+rate+certification```
But we still have substrings like  ```stateName%3DVirginia%252CMinnesota```
and that's because Jotai [runs `toString` on the URLParams](https://github.com/jotai-labs/jotai-location/blob/adabca165c3486cade23efa238f1f27d16 …
=> MR-2994 Fix focus on rerender

services/postgres/serverless.yml
Postgres 10 is EOL in AWS Aurora, so we need to run the manual in-place upgrade to Postgres 11 on dev/val/prod. This change sets the pg version to 11.13, which is the version that AWS does an in place upgrade to, so that all PR branches get the same version as is deployed in our higher environments. 
Once the dev/val/prod DBs have been upgraded in the AWS console we can merge this. This needs to land before January 31.
We have a separate ticket to do the more involved upgrade to Aurora Serverless v2 with a newer Postgres release.
https://qmacbis.atlassian.net/browse/MR-2577
=> Upgrade Aurora Serverless v1 to Postgres 11

services/uploads/serverless.yml
I just discovered a small copy/paste error with the IAM permission on the QA bucket for s3 list permissions. This removes the trailing wildcard to match the other buckets.
=> Fix typo in QA Bucket IAM

services/uploads/src/clamav.js
This is a fix for the issue where the AV Scan service has not been scanning anything for months. 
Details of ongoing investigation here: https://docs.google.com/document/d/1V3OUC9ryF24YY-kQccUhMfKH4JRWXVAp7vhPH2ckW5M/
Causes:
* avDownloadDefinitions has been failing because execSync() was not defined
* avScan has been failing because the invocation of the binary was munged
* avScan has been ignoring the binary failing because spawnSync() doesn’t throw when it errors
https://qmacbis.atlassian.net/browse/MR-3027
I attempted to upload a bad file to this review app and it was correctly flagged as dirty.
=> Fix for AVScan failure

.github/workflows/deploy.yml
This change removes the pins to the `bharvey-github-oidc` branch for reusable workflows now that the branch is merged to `main`
https://qmacbis.atlassian.net/browse/MR-2860
N/A
=> Remove pins to` bharvey-github-oidc`

services/app-web/src/common-code/featureFlags/flags.ts, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.tsx, services/app-web/src/pages/App/AppBody.tsx, services/app-web/src/pages/Landing/Landing.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.test.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetailsSchema.ts, tests/cypress/support/stateSubmissionFormCommands.ts
[MR-2841](https://qmacbis.atlassian.net/jira/software/projects/MR/boards/234)
- Removed the `rates-across-submissions` flag from `flags.ts` and updated code everywhere that was using the flag.
- Fixed typos.
- Removed the `rates-across-submissions` flag from unit tests.
- Added code to cypress commands to handle rates-across-submissions questions 
- `stateSubmissionFormCommands.ts`
- `fillOutNewRateCertification`
- `fillOutAmendmentToPriorRateCertification`
=> MR-2841: Remove rates across subs feature flag

services/app-api/serverless.yml, services/app-api/src/resolvers/questionAnswers/createQuestion.ts, services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/SupportingDocumentsSummarySection/SupportingDocumentsSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/UploadedDocumentsTable/UploadedDocumentsTable.tsx, services/app-web/src/contexts/S3Context.tsx, services/app-web/src/hooks/useErrorSummary.ts, services/app-web/src/hooks/useFileUpload.ts, services/app-web/src/index.tsx, services/app-web/src/pages/QuestionsAnswers/UploadQuestions/UploadQuestions.module.scss, services/app-web/src/pages/QuestionsAnswers/UploadQuestions/UploadQuestions.test.tsx, services/app-web/src/pages/QuestionsAnswers/UploadQuestions/UploadQuestions.tsx, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.tsx, services/app-web/src/pages/StateSubmission/Documents/Documents.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx, services/app-web/src/s3/s3Amplify.ts, services/app-web/src/s3/s3Client.d.ts, services/app-web/src/s3/s3Local.ts, services/app-web/src/testHelpers/apolloMocks/questionAnswerGQLMock.ts, services/app-web/src/testHelpers/apolloMocks/userGQLMock.ts, services/ui-auth/serverless.yml
Add file upload to add questions page. 
Other refactors: 
-  new React hooks -  `useFileUpload` and `useErrorSummary`. 
- edited `useS3` to include handling for bucket name and also hold S3 utility functions
https://qmacbis.atlassian.net/browse/MR-2886 
Also fixed this viewport scroll position bug https://qmacbis.atlassian.net/browse/MR-2997 
JEST:
- file upload accepts multiple pdf, word, excel documents
- displays form validation error if attempting to add question with zero files
- displays file upload alert if attempting to add question with all invalid files
- displays api error if createQuestion fails
CYPRESS:
- none yet, will address this as part of https://qmacbis.atlassian.net/browse/MR-2887 so we just add one full test for Q&A.
See ticket AC and also
- Make sure file uploads, …
=> MR-2886 CMS can upload a Q&A document

services/app-api/prisma/migrations/20230228215104_add_question_response/migration.sql, services/app-api/prisma/schema.prisma
Fix failed deploy of #1524 . This was due to not setting default values for `updatedAt`, which was added to new tables but also on existing question tables. 
Addressed the issue by editing initial migration to allow this to deploy in dev.
=> Fix: add_question_response migration 

.github/workflows/deploy-infra-to-env.yml, .github/workflows/promote.yml, services/github-oidc/README.md
This change enables GitHub OIDC for `val` and `prod` by:
- removing the pin so that `promote` now uses the updated versions of the `deploy-*-to-env` reusable workflows, and updating the inputs and secrets for those workflows
- adding some logic to choose the correct bootstrapped OIDC stage name based on the environment when the `github-oidc` service is deployed.  This is necessary because the `dev` environment uses the stage name `main` (for `val` and `prod` the stage name and environment name match)
Note:  I manually bootstrapped the `val` and `prod` OIDC roles following the instructions in the README 
This is a tricky one to test manually. Most of our QA comes from the fact that OIDC is working smoothly in `dev`.
I did test the changes to `deploy-infra-to-env` locally to ensure that the …
=> OIDC for higher environments

services/app-api/src/handlers/configuration.ts, services/app-api/src/handlers/postgres_migrate.ts
We ran into an issue where our restored Postgres DB in dev was unable to have a snapshot taken, which would fail the migrate. It looks like passing in an ARN for the DB as a cluster identifier is not working for the snapshots AWS SDK all of a sudden (this has been working fine). 
This change parses out the ID from the ARN and passes it to the snapshot call in the migrate handler.
=> Use ID instead of ARN in postgres migrate snapshot

.github/workflows/deploy.yml
Something changed in GH and our “deployment” lines in PRs have stopped having links in them that work pointing to the review app. 
All of our deployments are set to the environment: reviewapps, and it looks like now when a new review app deploys, it sets all previous deployments for “reviewapps” to be inactive. 
First try is to set each deployment to be “transient” which prevents that auto-inactive problem. But then we might want to delete them in destroy or something. We’ll see.
Also, setting environment: dev as part of our OIDC work seems to [unavoidably](https://github.com/actions/runner/issues/2120) create a deployment each time, which is why there are 3 extra “deployment” notifications per deployment in the PR history.
=> Set our reviewapp deployments to be transient

tests/cypress/integration/stateWorkflow/virusScan/virusScan.spec.ts
We have seen Cypress failures related to timeouts for the virus scan test (here's an [example failed run](https://github.com/CMSgov/managed-care-review/actions/runs/4386877719/jobs/7682009538)). This change mitigates that by increasing the timeout. 
[Slack thread for context](https://cmsgov.slack.com/archives/C014CRU197U/p1678464640258349)
N/A
N/A
=> Increase timeout

.github/workflows/promote.yml
In https://github.com/CMSgov/managed-care-review/pull/1531, I neglected to add `github-oidc` to the list of changed-services that is used by `promote`.  This fixes that!
=> Add github-oidc to changed services for promote

services/github-oidc/README.md, services/github-oidc/serverless.yml
I made a mistake with the bootstrapping logic that caused some CI failures with this error: `Error: No OpenIDConnect provider found in your account for https://token.actions.githubusercontent.com/`.  Here's what happened:
I set up bootstrapping so that each 'official' stage `[main, val, prod]` would be manually deployed once with a `bootstrap=true` flag that would tell the CloudFormation to go ahead and create the GitHub OICD IdP. The flag is tied to a CloudFormation conditional that tells the template to either create the IdP or not.
There can only be one of these IdPs pointing to GitHub per environment (attempts to create a duplicate will fail) and so I thought this would solve the problem of keeping each feature branch in dev from trying to deploy its own copy of the IdP and failing. …
=> Fix bootstrapping logic

.github/actions/get_aws_credentials/action.yml, .github/workflows/sechub-jira-sync.yml, services/github-oidc/serverless.yml
This change adds a workflow that runs on a cron and syncs Security Hub findings from the prod environment with Jira issues. See the inputs to the syncing action for details on the Jira configuration.  For more on the behavior of the syncing action, see https://github.com/Enterprise-CMCS/security-hub-visibility
There's also a small change to the composite action for getting AWS creds so that it can be called by workflows that don't pass a `changed-services` input.
- AWS
- uses OIDC to get prod credentials.  To support this, `securityhub` is added to the list of allowed AWS actions for the OIDC role
- Jira
- uses credentials for a Jira service user stored as Actions secrets to perform Jira actions
Manual testing: using static credentials (`PROD_AWS_SECRET_ACCESS_KEY`, etc), I ran the …
=> Sync SecHub findings with Jira issues

services/postgres/serverless.yml
Since the new aurora v2 upgrade last night, there have been some security hub recommendations that have come through to keep things in line with CMS requirements. This turns those things on.
The one that should be highlighted is the automatic minor version upgrades during the nightly maintenance window. This will apply minor upgrades to Aurora v2 postgres at night, which means the DB will be unavailable during the upgrade and the site will be down. Not sure how I feel about that to be honest, but it's what security hub says they want.
https://jiraent.cms.gov/browse/CLDSPT-43654
=> Aurora updates for security hub findings

services/app-api/src/emailer/awsSES.ts, services/app-api/src/emailer/emails/newPackageStateEmail.test.ts, services/app-api/src/emailer/emails/newPackageStateEmail.ts, services/app-api/src/emailer/emails/resubmitPackageStateEmail.ts, services/app-api/src/emailer/emails/unlockPackageStateEmail.ts
In trying to diagnose whether emails were sent, we ran into some gaps in our logging.  This PR adds a couple of lines, and also adds the team's email address to the recipients, so we can have another signal about whether a send happened.
=> Add a few console logs to our email sending flow

services/app-web/.storybook/storybook.scss, services/app-web/src/components/Banner/QuestionResponseSubmitBanner/QuestionResponseSubmitBanner.stories.tsx, services/app-web/src/components/Banner/QuestionResponseSubmitBanner/QuestionResponseSubmitBanner.test.tsx, services/app-web/src/components/Banner/QuestionResponseSubmitBanner/QuestionResponseSubmitBanner.tsx, services/app-web/src/components/Banner/QuestionResponseSubmitBanner/index.ts, services/app-web/src/components/Banner/index.ts, services/app-web/src/components/Breadcrumbs/Breadcrumb.test.tsx, services/app-web/src/components/Breadcrumbs/Breadcrumbs.module.scss, services/app-web/src/components/Breadcrumbs/Breadcrumbs.stories.tsx, services/app-web/src/components/Breadcrumbs/Breadcrumbs.tsx, services/app-web/src/components/Breadcrumbs/index.ts, services/app-web/src/components/index.ts, services/app-web/src/constants/routes.ts, services/app-web/src/pages/App/AppRoutes.tsx, services/app-web/src/pages/QuestionResponse/QuestionResponse.module.scss, services/app-web/src/pages/QuestionResponse/QuestionResponse.test.tsx, services/app-web/src/pages/QuestionResponse/QuestionResponse.tsx, services/app-web/src/pages/QuestionResponse/UploadQuestions/UploadQuestions.test.tsx, services/app-web/src/pages/QuestionResponse/UploadQuestions/UploadQuestions.tsx, services/app-web/src/pages/QuestionResponse/UploadResponse/UploadResponse.test.tsx, services/app-web/src/pages/QuestionResponse/UploadResponse/UploadResponse.tsx, services/app-web/src/pages/SubmissionSideNav/SubmissionSideNav.module.scss, services/app-web/src/pages/SubmissionSideNav/SubmissionSideNav.tsx, services/app-web/src/testHelpers/apolloMocks/questionResponseGQLMock.ts, tests/cypress/integration/stateWorkflow/questionResponse/questionResponse.spec.ts
1. Display breadcrumbs  with links back to submissions root and dashboard. Move `UploadResponse` and `UploadQuestions` into the submissions Outlet to enable referencing package data on these pages. 
2.  Add success banners on submit that display on main Q&A page.
https://qmacbis.atlassian.net/browse/MR-2901
https://qmacbis.atlassian.net/browse/MR-2906
Updated tests to handle submissions context sharing via outlet
- See ticket AC.
=> MR-2906 MR-2901 Add breadcrumbs to upload pages and success banners

services/app-api/src/emailer/emails/newPackageStateEmail.test.ts, services/app-api/src/emailer/emails/newPackageStateEmail.ts, services/app-api/src/emailer/emails/resubmitPackageStateEmail.ts, services/app-api/src/emailer/emails/unlockPackageStateEmail.ts, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.test.tsx
We have two failed promotes due to issues with unit tests today. This is a quick fix to try and address.
1. Remove invalid variable
2. Remove filling out the rate certs for remove button tests
=> Fix broken app-api unlock test and refactor flakey app-web rate details test

services/app-api/.eslintrc, services/app-api/src/emailer/formatters/formatEmailAddresses.test.ts, services/app-api/src/emailer/formatters/formatEmailAddresses.ts, services/app-api/src/emailer/formatters/index.ts, services/app-web/.eslintrc
@rswerve putting up a failing test for now. I will try to push a commit to fix but in case I don't get there before meetings start wanted to have visibility.
The cases the function needs to handle:
- prune duplicate emails due to alias 
- prune duplicate emails due to casing
- maintain aliased emails that are unique
- maintain raw emails that are unique even if they have uppercase (this is what was broken I believe - I think #1489 and caused divisions to be removed only in prod)
**Maz (@rswerve ) adds**: You were right.  Uppercasing was breaking pruneDupes....  I'm now comparing everything as lowercase, and returning whichever casing we see first in the array (so I tweaked your test to account for that).  All tests are passing.
=> Fix pruneDuplicateEmails

services/app-api/src/resolvers/healthPlanPackage/submitHealthPlanPackage.ts, services/app-api/src/resolvers/healthPlanPackage/unlockHealthPlanPackage.ts, services/app-web/src/components/Modal/UnlockSubmitModal.test.tsx, services/app-web/src/components/Modal/UnlockSubmitModal.tsx, services/app-web/src/constants/errors.ts, services/app-web/src/gqlHelpers/mutationWrappersForUserFriendlyErrors.ts, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx, services/app-web/src/testHelpers/apolloMocks/apolloErrorCodeMocks.ts, services/app-web/src/testHelpers/apolloMocks/healthPlanPackageGQLMock.ts
[MR-3116](https://qmacbis.atlassian.net/browse/MR-3116)
`submitHealthPlanPackage.ts` and `unlockHealthPlanPackage.ts` resolvers now throw `GraphQL` errors when sending emails fails.
On the front-end, users will no longer be shown errors when submitting, unlocking, or resubmitting fails due to a failure in sending emails.
Extras:
- `useCreateHealthPlanPackageMutation` in  `SubmissionType.tsx` is now updating the cache more consistent with the Q&A mutations.
- Adding some hard coded graphQL error codes in `errors.ts`. Follows the same style we used in `flags.ts` so we have a central place where we can store error codes. I'm using this for making the unlock and submit mock mutations more consistent with errors from the server. I think @mojotalantikite was talking about having something like …
=> MR-3116: Email errors should not block submit, unlock and resubmit to complete. 

.github/workflows/deploy.yml, .github/workflows/promote.yml
PR #1527 had a missing env var in the promote script. This also puts the sha for the deploy action back to the `main` branch.
=> Add NR_LICENSE_KEY to promote

scripts/destroy_stage.ts
We aren't cleaning up resources in PR branches related to `github-oidc` in the `destroy` action. This adds it to that script.
https://qmacbis.atlassian.net/browse/MR-3191
=> Add github-oidc to destroy action

services/app-api/src/resolvers/healthPlanPackage/submitHealthPlanPackage.test.ts, services/app-api/src/resolvers/healthPlanPackage/submitHealthPlanPackage.ts, services/app-web/src/common-code/featureFlags/flags.ts, services/app-web/src/components/SubmissionSummarySection/SubmissionTypeSummarySection/SubmissionTypeSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/SubmissionTypeSummarySection/SubmissionTypeSummarySection.tsx, services/app-web/src/pages/CMSDashboard/CMSDashboard.test.tsx, services/app-web/src/pages/CMSDashboard/CMSDashboard.tsx, services/app-web/src/pages/StateDashboard/StateDashboard.test.tsx, services/app-web/src/pages/StateSubmission/New/NewStateSubmissionForm.test.tsx, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.test.tsx, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionTypeSchema.ts, tests/cypress/integration/cmsWorkflow/unlockResubmit.spec.ts, tests/cypress/integration/cmsWorkflow/viewSubmission.spec.ts, tests/cypress/integration/stateWorkflow/dashboard/dashboard.spec.ts, tests/cypress/integration/stateWorkflow/questionResponse/questionResponse.spec.ts, tests/cypress/integration/stateWorkflow/stateSubmissionForm/reviewAndSubmit.spec.ts, tests/cypress/integration/stateWorkflow/stateSubmissionForm/submissionType.spec.ts, tests/cypress/support/stateSubmissionFormCommands.ts
[MR-3055](https://qmacbis.atlassian.net/browse/MR-3055)
Removed `CMS_DASHBOARD_FILTER` an `RATE_CERT_ASSURANCE` from feature flags in `flag.ts`
**Note**: `RATE_CERT_ASSURANCE` is a unique flag, it was used both in front end and the api.
=> MR-3055 Delete CMS dashboard and No Rate Cert feature flags and code. 

.github/actions/get_aws_credentials/action.yml, .github/workflows/deploy.yml, .github/workflows/promote.yml, README.md, package.json, scripts/collect_ci_runtime_stats.ts, scripts/get-changed-services/index.ts, services/app-proto/README.md, services/app-web/src/common-code/proto/healthPlanFormDataProto/README.md, services/github-oidc/serverless.yml, services/uploads/README.md
Since we had to move this repository over to the `Enterprise-CMCS` github org some scripting and docs needed to be upgraded to refer to the repository properly. This moves those references.
https://qmacbis.atlassian.net/browse/MR-3124
=> Move CMSGov references to Enterprise-CMCS

services/app-api/serverless.yml, services/postgres/serverless.yml
When we upgraded to Postgres Aurora v2 we left the old v1 database around to make sure everything was working properly with the upgrade. Since things seem to be fine it should be ok to remove the old resources.
https://qmacbis.atlassian.net/browse/MR-3200
=> Remove Aurora v1 resources

services/app-web/src/components/FileUpload/FileUpload.tsx, services/app-web/src/contexts/S3Context.tsx, services/app-web/src/otelHelpers/index.ts, services/app-web/src/otelHelpers/tracingHelper.ts, services/app-web/src/s3/s3Amplify.ts
We had a user encounter some issues with file uploads today, but there were no errors in the OTEL logs to indicate their particular issue. This adds some error recording to the error paths of the s3 context in hopes of getting more insight from that level of `app-web`.
=> Add more OTEL to s3 error paths

services/postgres/serverless.yml
We received a ticket (MDSO-187) saying our costs have gone up in the past 5 weeks in dev. It looks like it's mainly Aurora RDS related, probably due to some combination of provisioned capacity and how for a little while there we had both v1 and v2 aurora DBs deployed due to our upgrade (v1 is now fully removed).
This provisions our Aurora DBs in PR environments with the smallest possible deployment size.
https://qmacbis.atlassian.net/browse/MR-3228
=> Size down Aurora minimum capacity in review apps

docs/technical-design/launch-darkly-testing-approach.md, services/app-api/src/launchDarkly/launchDarkly.ts, services/app-api/src/resolvers/healthPlanPackage/submitHealthPlanPackage.ts, services/app-api/src/testHelpers/launchDarklyHelpers.ts, services/app-web/src/common-code/featureFlags/flags.ts, services/app-web/src/common-code/featureFlags/index.ts, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.test.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetailsSchema.ts, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionTypeSchema.ts, services/app-web/src/testHelpers/jestHelpers.tsx, tests/cypress/support/index.ts, tests/cypress/support/launchDarklyCommands.ts
Bring back feature flag to packages with shared rates dropdown so we have ability to remove the dorpdown from the form on demand if we want to. 
Notes: 
- Decided to leave the content displaying on submission summary, since we say that any data the states have filled out we want to display 
- Added `FeatureFlagSettings` type to use instead of hand typing the places we need this. 
-  Renamed the types a bit in flags file, I was getting confused when to expect the capitalized const enum we refer to versus the lowercased const from Launch Darkly. Open to renaming things back.
https://qmacbis.atlassian.net/browse/MR-3214
- no new tests added 
- nothing should be changed about the packages with shared rates behavior with flag on.
- flag off should be an option
=> Feature flag "packages with shared rates" dropdown

.github/workflows/deploy.yml, README.md
We were asked to move our Code Climate out of the old CMSGov organization, which has changed the badge links in our main `README`. This moves us to the new links.
https://qmacbis.atlassian.net/browse/MR-3262
=> Update Code Climate badge links

services/app-api/src/emailer/emails/newPackageCMSEmail.test.ts, services/app-api/src/emailer/emails/resubmitPackageCMSEmail.test.ts, services/app-api/src/emailer/emails/unlockPackageCMSEmail.test.ts, services/app-api/src/emailer/templateHelpers.test.ts, services/app-api/src/emailer/templateHelpers.ts, services/app-web/src/pages/Settings/EmailSettingsTables/EmailSettingsTables.tsx
- Remove the DMCOMCOGActions@cms.hhs.gov mailbox from receiving all system notifications
- DMCP & OACT do not receive emails for CHIP only submissions
https://qmacbis.atlassian.net/browse/MR-3179
https://qmacbis.atlassian.net/browse/MR-3184
Updated tests any tests checking for "all" division emails to only check for OACT and DMCP.
also added test for `to addresses list  does not include OACT and DMCP group emails for CHIP submission` 
- No emails go to DMCO (but still sends to state analysts)
- CHIP submission emails do not go to DMCP or OACT
=> MR-3184 MR-3179  Email config adjustments 

services/app-api/src/resolvers/healthPlanPackage/submitHealthPlanPackage.test.ts, services/app-api/src/resolvers/healthPlanPackage/submitHealthPlanPackage.ts, services/app-web/src/common-code/healthPlanFormDataType/ModifiedProvisions.ts, services/app-web/src/common-code/healthPlanFormDataType/healthPlanFormData.ts, services/app-web/src/common-code/healthPlanFormDataType/index.ts, services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.tsx, services/app-web/src/constants/healthPlanPackages.ts, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.test.tsx, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.tsx, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetailsSchema.ts, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.test.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.test.tsx, tests/cypress/support/stateSubmissionFormCommands.ts
Adjusted yes/no logic to have a different set of provisions for CHIP only (six provisions related to risks and payments are simply not included or displayed for CHIP subs). Also made copy changes that were in Figma to the MLR references.
https://qmacbis.atlassian.net/browse/MR-3177 
New tests
- ` shows correct validations for CHIP only submissions`
-  `does not allow setting risk related or payments provisions for CHIP only submissions`. 
- `removes any risk related modified provisions from CHIP submission and submits successfully`
- `sorts amended provisions correctly and removes risk provisions from unmodified list for CHIP amendment`
I suggest testing CHIP and non CHIP modified provisions behaviors.
=> MR-3177 State sees relevant yes/no provision options and citations for CHIP-Only

.github/workflows/deploy.yml, .github/workflows/promote.yml
Running our unit tests via the `dev` tool is fine locally, but produces hard to read output when in CI (e.g. lines get wrapped making failures harder to read back). This moves them to be setup with their appropriate `lerna` commands and run direct via `yarn`.
I also noticed a couple places I missed updating the CodeClimate keys when writing this change, so that fix is here too.
=> Run unit tests direct in CI

.github/github-lock.sh
Currently the github actions API has broken the ability to filter for `in_progress` runs. This changes how we query for `in_progress` runs by doing the filtering ourselves.
We have a [GitHub Support](https://support.github.com/ticket/personal/0/2125067) issue open reporting the API regression. Others have [noticed this as well](https://github.com/orgs/community/discussions/53266).
https://qmacbis.atlassian.net/browse/MR-3303
=> Fix github locking script

services/app-web/src/common-code/healthPlanFormDataType/ModifiedProvisions.ts, services/app-web/src/common-code/healthPlanFormDataType/healthPlanFormData.ts, services/app-web/src/common-code/healthPlanFormDataType/index.ts, services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.tsx, services/app-web/src/constants/healthPlanPackages.ts, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.test.tsx, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.tsx, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetailsSchema.ts, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.test.tsx, tests/cypress/support/stateSubmissionFormCommands.ts
The MLR references copy updates should be conditional (only apply to provisions when population covered = CHIP). This is from product design review.
https://qmacbis.atlassian.net/browse/MR-3177
Look at this [figma](https://www.figma.com/file/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?t=mbHghBniks1zDfro-0) - left side is non-CHIP behavior and right side is CHIP amendments
Updated tests again to cover expected behavior.
Also added new tests for MLR copy specifically
- renders amended provisions with MLR references for a Medicaid contract
- renders amended provisions with correct MLR references for CHIP contract
Create contract amendment submission. When you go between population covered = CHIP and other population covered options the MLR references will change subtly.
=> bugfix: Correct modified provisions MLR reference for non CHIP submission

services/app-web/src/components/SubmissionSummarySection/SubmissionTypeSummarySection/SubmissionTypeSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/SubmissionTypeSummarySection/SubmissionTypeSummarySection.tsx, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.test.tsx, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx
Fixing a typo in the population coverage question.
"which populations does this **_contact_** action cover" -> "which populations does this **_contract_** action cover"
=> Fix typo in population coverage question.

docs/technical-design/file-upload.md, services/app-web/src/components/FileUpload/FileUpload.tsx, tests/cypress/support/questionResponseCommands.ts
FileUpload has come up several times recently. I wanted to try and document its behavior and some of the design decisions.  The idea for this doc came up after I had very similar conversations with both @rswerve and Kelsey about "how does file upload work" topics. All feedback welcome here including things to add, delete, or edit. 
One question I have is should I include accessibility stuff here as well? We already have a doc for that in [confluence ](https://qmacbis.atlassian.net/wiki/spaces/OY2/pages/edit-v2/2894299137) but I am wondering should I include some of that content here as well.
=> Add doc describing FileUpload

services/app-api/src/resolvers/healthPlanPackage/submitHealthPlanPackage.test.ts, services/app-api/src/resolvers/healthPlanPackage/submitHealthPlanPackage.ts, services/app-web/src/common-code/healthPlanFormDataType/FederalAuthorities.ts, services/app-web/src/common-code/healthPlanFormDataType/ModifiedProvisions.ts, services/app-web/src/common-code/healthPlanFormDataType/UnlockedHealthPlanFormDataType.d.ts, services/app-web/src/common-code/healthPlanFormDataType/healthPlanFormData.ts, services/app-web/src/common-code/healthPlanFormDataType/index.ts, services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.tsx, services/app-web/src/constants/healthPlanPackages.ts, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.test.tsx, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.tsx, services/app-web/src/testHelpers/jestHelpers.tsx
State cannot select an operating authority that is not relevant to CHIP-Only
https://qmacbis.atlassian.net/browse/MR-3175
https://qmacbis.atlassian.net/browse/MR-3177 - last sprint work, just one additional CHIP copy change requested from stakeholders
- `displays correct form fields for federal authorities with CHIP only contract`
- `displays correct form fields for federal authorities fields with Medicaid contract`
- `renders federal authorities for a medicaid contract`
- `renders federal authorities for a CHIP contract as expected, removing invalid authorities`
- `removes any invalid federal authorities from CHIP submission and submits successfully`
-See ticket AC.
-  On submission type page you can toggle between CHIP and medicaid population covered - this will impacts federal …
=> MR-3175 CHIP only federal authorities list

services/app-api/serverless.yml, services/app-api/src/handlers/add_sha.test.ts, services/app-api/src/handlers/add_sha.ts, services/app-api/src/postgres/healthPlanPackage/updateHealthPlanRevision.ts, services/app-web/src/common-code/proto/healthPlanFormDataProto/toProtoBuffer.ts
In a previous PR, we started add a `sha256` property to every uploaded document.  This gives us a unique identifier for each file, which will eventually be queryable in the database.  In this PR, we're making a lambda to go back and add the sha256 to every file that was uploaded before the previous PR.  
In addition to the machinery to read the file, generate a sha, and put it on the file in the proto, the one bit of logic is that we should add the sha if it doesn't exist, but not overwrite it if it does.  This is what the new tests cover.
The way I tested this in the review app was to set the generated sha to ``${generateSha()}-testing`` in the first lambda run, followed by running the reports and manually examining the CSV output, and then finally setting the generated sha to something …
=> MR-3281: Add sha data migration

.github/workflows/deploy-app-to-env.yml, .github/workflows/deploy-infra-to-env.yml, .github/workflows/deploy.yml, .github/workflows/destroy.yml, .github/workflows/promote.yml, .github/workflows/sechub-jira-sync.yml, services/github-oidc/README.md
We hit an issue in a branch where Jason was attempting to output variables to use in our Cypress configuration, but because the value contains the string `us-east-1`, GitHub Actions masks that output value. There's no reason why `us-east-1` should be a secret, except I vaguely recall we had inherited that config from the quickstart.
This moves that variable to use `vars` instead of `secrets`.
=> Move aws region into a var, remove from secrets

.github/workflows/promote.yml
This fixes the location of the default region to the appropriate place in the promote script. After the change in #1711 I missed updating this in promote.
=> Fix promote for default region

.github/workflows/deploy.yml
Restoring the pointer in `deploy.yml` back to `@main` from the work in [1704](https://github.com/Enterprise-CMCS/managed-care-review/pull/1704)
=> Restore deploy workflow pointer to main

.github/workflows/deploy.yml, services/cypress/cypress.config.ts
Failed to promote in prod because in `promote.yml`, we are not copying over the `gen` folder, specifically the `schema.graphql` file. This file is needed for the `readGraphQLSchema` task in `cypress.config.ts`. 
Since promote only runs the `promote.spec.ts,` that task is never called. So the quickest solution was to read the schema when the task is called and not at startup.
=> Move reading schema to inside readGraphQLSchema task.

services/cypress/integration/stateWorkflow/stateSubmissionForm/newSubmission.spec.ts, services/cypress/integration/stateWorkflow/stateSubmissionForm/submissionType.spec.ts, services/cypress/support/navigateCommands.ts, services/cypress/support/questionResponseCommands.ts
Looking at the [cypress failures](https://cloud.cypress.io/projects/tt5hbz/runs/bae7be7b-918e-4ec5-b88f-f5ee7b28a879/test-results/226d784d-8eb8-4d47-bd44-2f407e61e05b) for the dependabot [PR#1735](https://github.com/Enterprise-CMCS/managed-care-review/pull/1735). 
Increasing the timeout for uploading files may have let servers go to sleep. Then hitting `Continue`, the wait for `updateHealthPlanFormDataMutation` times out. Increasing the default timeout for `cy.wait('@updateHealthPlanFormDataMutation')` should allow the tests to wait longer for server response.
Also, increasing the timeout for the `wait` in `questionResponseCommands.ts` since they also wait on graphql request right after document upload.
=> Increase timeout for updateHealthPlanFormDataMutation.

.github/workflows/deploy-app-to-env.yml, .github/workflows/deploy-infra-to-env.yml, .github/workflows/deploy.yml, .github/workflows/destroy.yml, .github/workflows/promote.yml, dev, lerna.json, package.json, run_build.sh, yarn.lock
We've been seeing some issues in CI where Lerna will complain about a configuration option that is no longer available in Lerna 7 (which is true), and sometimes be totally fine with our Lerna 6 config. Looks like GHA will sometimes put us on an Ubuntu server that has Lerna 7 installed, and sometimes it will put us on one with Lerna 6 installed.
This change upgrades us to Lerna 7 and then uses `npx` to call it, using our yarn installed local version, rather than the system version in the GHA environment.
https://qmacbis.atlassian.net/browse/MR-3458
=> Upgrade Lerna to 7

package.json, yarn.lock
[MR-3480](https://qmacbis.atlassian.net/browse/MR-3480)
Cypress 12.16.0 fixed the code coverage bug.
=> MR-3480: Update Cypress to 12.16.0

services/github-oidc/serverless.yml
We started hitting an issue where github oidc connect setup for AWS credentials started failing. Jason found this [blog post](https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/) from GitHub yesterday that tells users to make sure both OIDC intermediary thumbprints are added in AWS. 
We only had the first one, so this adds the second one to the list of known thumbprints.
https://qmacbis.atlassian.net/browse/MR-3529
=> Update GitHub AWS OIDC thumbprints

services/app-web/src/pages/StateSubmission/Documents/Documents.tsx, services/infra-api/serverless.yml
https://qmacbis.atlassian.net/browse/MR-3540
updateHPFormData is erroring when NJ adds 35 files to supporting documents. 
Best guess so far is that this is hitting a default WAF rule for body length at 2^13 bytes.
=> Upload Many Documents Bug

services/app-api/src/handlers/migrate_rate_documents.test.ts, services/app-api/src/handlers/migrate_rate_documents.ts
This addresses a failed migration in DEV due to `rateInfos` being undefined.
#1763
=> Fix: Supporting docs migration - address type error, guard against similar issues

dev_tool/src/serverless.ts, services/output.sh
`./dev hybrid` was failing for me because my built in serverless version is out of date. We've moved to invoking with `npx` elsewhere to address this problem
=> make dev hybrid commands not rely on built in serverless

.github/workflows/sechub-jira-sync.yml
The SecHub/Jira sync action is hosted in a repo MAC-FC recently renamed. GitHub does the right thing and resolves the new repo, but the best practice is to update the reference in that workflow to the new repo name, which is [Enterprise-CMCS/mac-fc-security-hub-visibility.](https://github.com/Enterprise-CMCS/mac-fc-security-hub-visibility) 
N/A
N/A
N/A
I can't test it directly because I don't have repo access to workflows anymore.  Someone with that access could try this on a branch if they want to
=> Update sechub/jira sync action to use new repo name

.github/workflows/deploy-app-to-env.yml, .github/workflows/deploy.yml, services/app-api/scripts/invoke-migrate-lambda.sh, services/app-api/src/handlers/proto_to_db.ts
We were seeing a failure in `app-api` deploy at the step that the called the `proto_to_db` handler. It turns out that the case of `statusCode` returned from that handler was slightly different than the other migration handler (`StatusCode` vs `statusCode`). This caused the error check to fail in the invoke script.
This fixes it by using the same TypeScript return type in the handler.
https://qmacbis.atlassian.net/browse/MR-3585
=> Fix statusCode return value in migrate lambdas

scripts/destroy_stage.ts
Right now the `destroy` script is a bit aggressive, exiting if it fails to find an expected stack. This is unnecessary, as it's possible a stack never got created or was deleted by a previous run of destroy.
This change makes the destroy script continue over stacks that aren't found and makes the script idempotent.
https://qmacbis.atlassian.net/browse/MR-3590
=> More permissive destroy script

services/app-web/src/components/Banner/GenericApiErrorBanner/GenericApiErrorBanner.tsx, services/app-web/src/pages/Errors/GenericErrorPage.tsx
[MR-3541](https://qmacbis.atlassian.net/browse/MR-3541)
Fixed the `GenericErrorBanner` `href` link to open to email box correctly and unified `let us know` links to be consistent with how we display help desk links everywhere else.
Also updated the `GenericErrorPage` link to the help desk email.
=> MR-3541: Fix "Let us know" link goes to 404 page

services/app-web/src/s3/s3Amplify.ts
[MR-3569](https://qmacbis.atlassian.net/browse/MR-3569)
Changed the expiration for the document URLs to 1 hour. I was still able to download files past 15 minutes.
This is the error after an hour (Using a different file)
If you keep opening the same file, it will work past 1 hour. Not sure why, maybe it's cached? But below are instructions on how to correctly test the expiration time.
For testing this issue:
1. Open a submission, but do not click on any file.
2. Wait 45 minutes or right before an hour.
3. Click on any file to download, and it should still work
4. Wait past 1 hour and click on **A DIFFERENT file** and it should open a new tab to an error.
=> MR-3569: Prod: User reported error in downloading zip files

services/infra-api/serverless.yml, services/storybook/serverless.yml, services/ui/serverless.yml
This resolves the security hub notice `CloudFront.5 CloudFront distributions should have logging enabled`. It adds logging to the CloudFront bucket under a prefix path of `$stage-$service-cloudfront-logs`.
https://qmacbis.atlassian.net/browse/MR-3105
=> Fix SecurityHub CloudFront.5 logging

services/app-api/src/emailer/emails/newPackageCMSEmail.ts, services/app-api/src/emailer/emails/resubmitPackageCMSEmail.ts, services/app-api/src/emailer/emails/resubmitPackageStateEmail.ts, services/app-api/src/emailer/emails/unlockPackageCMSEmail.ts, services/app-api/src/emailer/emails/unlockPackageStateEmail.ts
Misread the requirement for [MR-3405](https://qmacbis.atlassian.net/browse/MR-3405). I added the help desk email as the `replyToAddresses` for all other system notification emails.
=> Add replyto for the rest of system notification emails.

services/app-web/src/components/Banner/DocumentWarningBanner/DocumentWarningBanner.tsx, services/app-web/src/components/DownloadButton/DownloadButton.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx
Fixed margins for warning banner when the Q&A UI is toggled off.
=> Fix document download warning banner margin for Q&A flag off UI

services/app-api/src/domain-models/contractAndRates/contractTypes.ts, services/app-api/src/domain-models/contractAndRates/formDataTypes.ts, services/app-api/src/domain-models/contractAndRates/index.ts, services/app-api/src/domain-models/contractAndRates/rateTypes.ts, services/app-api/src/domain-models/contractAndRates/revisionTypes.ts, services/app-api/src/domain-models/healthPlanPackage.ts, services/app-api/src/postgres/contractAndRates/findContractWithHistory.ts, services/app-api/src/postgres/contractAndRates/index.ts, services/app-api/src/postgres/contractAndRates/insertContract.ts, services/app-api/src/postgres/contractAndRates/prismaSharedContractRateHelpers.ts, services/app-api/src/postgres/contractAndRates/prismaToDomainModel.test.ts, services/app-api/src/postgres/contractAndRates/updateDraftContract.ts, services/app-api/src/postgres/postgresStore.ts, services/app-api/src/resolvers/configureResolvers.ts, services/app-api/src/resolvers/healthPlanPackage/updateHealthPlanFormData.test.ts, services/app-api/src/resolvers/healthPlanPackage/updateHealthPlanFormData.ts, services/app-api/src/testHelpers/contractAndRates/contractHelpers.ts, services/app-api/src/testHelpers/emailerHelpers.ts, services/app-api/src/testHelpers/storeHelpers.ts, services/app-web/src/common-code/healthPlanFormDataType/LockedHealthPlanFormDataType.d.ts, services/app-web/src/common-code/healthPlanFormDataType/UnlockedHealthPlanFormDataType.d.ts, services/app-web/src/common-code/proto/healthPlanFormDataProto/toDomain.ts, services/app-web/src/pages/StateSubmission/StateSubmissionForm.tsx, services/app-web/src/testHelpers/apolloMocks/healthPlanFormDataMock.ts
[MR-3639](https://qmacbis.atlassian.net/browse/MR-3639)
- Modified updateHHP to update contract only submissions with the new DB.
- Updated `managedCareEntities` type to be string literals of the entities instead of a string array.
- Removed `documentCategories` from the `contractFormDataSchema`. Adding document categories in `convertContractRevisionToHealthPlanRevision`.
- Updating `stateContacts`, `supportingDocuments`, and `contractDocuments` is not implemented in this PR. We will need a reliable way to CRUD these relationships using a `UUID` or something. This work of adding a unique ID will be done in a different ticket.
- Just heads up, looks like our frontend doesn't let state contacts be partially filled out when `Save as draft`
- `updateHealthPlanFormData.test.ts`
- Used …
=> MR-3639: Modify update hpp mutation

.github/workflows/deploy.yml, README.md, scripts/get-changed-services/index.ts
There is a bug -- or really, a lack of functionality -- with cypress re-runs when using the GHA `re-run failed jobs` option, which is a [known issue](https://github.com/cypress-io/github-action/issues/531#issuecomment-1608902697). If you're using a parallelized container build in GHA CI (as we do) and a container or two has a failed spec, choosing to use the GHA `re-run failed jobs` feature will load _all_ of the Cypress tests onto that container that has failed and try to re-run everything there. This is unexpected, as I think people assume only the failed specs and other tests that were allocated to the failed container will re-run. Since we have a 25 minute timeout on Cypress runs, and we're running the entire test suite on a fraction of the containers in this scenario, we'll always …
=> Skip ahead to re-run only Cypress

services/app-web/src/components/Header/Header.tsx, services/app-web/src/components/Header/PageHeadingRow/PageHeadingRow.test.tsx, services/app-web/src/components/Header/PageHeadingRow/PageHeadingRow.tsx, services/app-web/src/pages/App/AppBody.test.tsx, services/app-web/src/pages/App/AppRoutes.test.tsx, services/app-web/src/pages/App/AppRoutes.tsx, services/app-web/src/pages/CMSDashboard/CMSDashboard.tsx, services/app-web/src/pages/Help/Help.tsx, services/app-web/src/pages/Landing/Landing.module.scss, services/app-web/src/pages/Landing/Landing.tsx, services/app-web/src/pages/StateDashboard/StateDashboard.test.tsx, services/app-web/src/pages/StateDashboard/StateDashboard.tsx, services/app-web/src/pages/StateSubmission/StateSubmissionForm.module.scss, services/app-web/src/testHelpers/apolloMocks/userGQLMock.ts, services/cypress/integration/smokeTest/smokeTest.spec.ts, services/cypress/support/loginCommands.ts, services/cypress/support/navigateCommands.ts, services/cypress/support/stateSubmissionFormCommands.ts
This PR fixes an issue that was introduced in https://github.com/Enterprise-CMCS/managed-care-review/pull/1910 by ensuring that logged in users can access the help page
[Relevant slack thread](https://cmsgov.slack.com/archives/C014CRU197U/p1694207335614259)
https://qmacbis.atlassian.net/browse/MR-3339
As a state user, make sure the links to the help page are accessible
=> [MR-3339] ensure that logged in and non logged in users can access the help page

.github/workflows/sechub-jira-sync.yml
We need to update the ID of the Security Hub findings epic for the sync tool. Since we had our Jira migrated over the weekend, this value has changed.
=> Update SecHub Epic for Jira Migration

services/app-web/src/pages/StateSubmission/Contacts/ActuaryContactFields.tsx, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.tsx, services/app-web/src/pages/StateSubmission/RateDetails/SingleRateCert/SingleRateCert.tsx, services/app-web/src/pages/StateSubmission/StateSubmissionForm.module.scss, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx
This PR updates the following:
- Adjust the margin on the Submission type, Contract and Rate details pages so that there's only the 32px padding applied to the form container
- On the Submission Type page ensure JAWS reads out that the Submission description field is required
- On the Rate details page: ensure JAWS doesn't skip the Rate certification type label and gets rid of the redundant "Required group, required." announcement
- On the Rate details page ensure that JAWS calls out the Certifying actuary fields as required
This PR doesn't include the following
- Changes the order of announcement on the rate and contract pages between the labels and upload links. I'll wait for confirmation from Design and Hana if there's a preference. Same with the optional call out on the supporting …
=> [MR-3576] Design and accessibility tweaks to  required and optional labels

services/app-api/src/domain-models/contractAndRates/convertContractWithRatesToHPP.ts, services/app-api/src/resolvers/healthPlanPackage/updateHealthPlanFormData.test.ts
Fixes additional actuaries getting copied multiple times based on the number of rates on a contract when converting our new domain contract data to HPP contract data.
Using `Set.add()` does not check for the equality of objects when adding them to the array. This caused every additional actuary contract from every rate to be copied to the `contract.addtlActuaryContacts` then when saving to the db, that `contract.addtlActuaryContacts` is then set to every `rate.addtlActuaryContacts`. Run this circle a few times, and it will duplicate the contacts exponentially. 
`updateHealthPlanFormData.test.ts`
- `'creates, updates, and deletes rates in the contract'` - Update to test additional actuaries.
=> Fix additional actuary duplication and add tests.

services/cypress/integration/cmsWorkflow/unlockResubmit.spec.ts, services/cypress/integration/stateWorkflow/questionResponse/questionResponse.spec.ts, services/cypress/integration/stateWorkflow/stateSubmissionForm/documents.spec.ts, services/cypress/integration/stateWorkflow/virusScan/virusScan.spec.ts, services/cypress/support/index.ts, services/cypress/support/launchDarklyCommands.ts, services/cypress/support/stateSubmissionFormCommands.ts, services/cypress/support/submissionReviewCommands.ts
[MR-2369](https://qmacbis.atlassian.net/browse/MCR-2369)
- Turns on `rates-db-refactor` flag for Cypress tests
- Turns on `supporting-docs-by-rate` flag for Cypress tests
- Since `supporting-docs-by-rate` is dependent on `rates-db-refactor`, the UI changes behind it were never activated in `dev`. By activating `rates-db-refactor` in dev we now see the UI in dev Cypress tests.
- All tests have been updated for the UI changes.
- Skip `questionsResponse.spec` tests because we have not migrated the Q&A API endpoint yet.
- **NOTE** Currently, the change history is incorrect and our cypress tests does not accurately test the change history and its order.
- This test is in `unlockResubmit.spec`
- It still passes
- I will have a follow-up ticket to address this once we fix the change history. …
=> MR-2369: turn on rates db refactor flag for cypress

.github/workflows/deploy-app-to-env.yml, services/app-api/src/handlers/proto_to_db.test.ts, services/app-api/src/handlers/proto_to_db.ts
We encountered an error migrating dev where a rate revision was not able to be created because the contract it linked to did not exist yet. This PR reorganizes the migrator to migrate all the contracts and then all the rates.
=> Reorder migrator to migrate rates after contracts to prevent linking errors

services/app-api/src/domain-models/contractAndRates/revisionTypes.ts, services/app-api/src/postgres/contractAndRates/parseContractWithHistory.ts, services/app-api/src/postgres/contractAndRates/prismaDraftContractHelpers.ts, services/app-graphql/src/queries/fetchRate.graphql, services/app-graphql/src/queries/indexRates.graphql, services/app-graphql/src/schema.graphql, services/app-web/src/pages/SubmissionSummary/RateSummary.tsx
[MCR-3549](https://qmacbis.atlassian.net/browse/MCR-3549)
- Add `contractID` to the contract revision level data.
- Update domain types
- Update Graphql schemas
- Remove `contractRevision` from the `Rate` level in GraphQL schemas.
=> MCR-3549: Add parent contract id to contract revision

services/postgres/README.md
This adds additional documentation around how to add your IP to the security group in order to get to the Aurora instances via the jumpbox. 
https://qmacbis.atlassian.net/browse/MCR-2948
=> Add more documentation on jumpbox access

services/app-api/src/postgres/contractAndRates/findRateWithHistory.test.ts, services/app-api/src/postgres/contractAndRates/parseRateWithHistory.ts, services/app-api/src/postgres/contractAndRates/prismaDraftRatesHelpers.ts, services/app-api/src/resolvers/contractAndRates/fetchRate.test.ts, services/app-api/src/resolvers/contractAndRates/indexRates.test.ts, services/app-graphql/codegen.yml, services/app-graphql/src/queries/fetchRate.graphql, services/app-graphql/src/queries/indexRates.graphql, services/app-graphql/src/schema.graphql, services/app-web/src/pages/CMSDashboard/CMSDashboard.tsx, services/app-web/src/pages/SubmissionSummary/RateSummary.tsx
We saw an error on prod.
In app-web, we were treating Rate.revisions like we have been treating HPP.revisions, where the first revision can be a draft or not. If the package is unlocked, we would then use the second revision as the data to display in the table b/c the first is assumed to be the draft.
RateType no longer puts the draft in the list of revisions, we have a separate draft revision in place. 
In prod, against _migrated_ data, this errored because there was no second revision. 
Locally, we didn't see errors, because we were returning duplicate revisions for _unmigrated_ data. This is because we were still using the revision mapping code that spits out a revision for every related submission action, code we ditched on packages and code I've reconsidered, ultimately. 
So by …
=> Update GQL Rate to have draft rate and only return individual rate revs

services/app-api/src/domain-models/contractAndRates/contractTypes.ts, services/app-api/src/domain-models/contractAndRates/formDataTypes.ts, services/app-api/src/domain-models/contractAndRates/index.ts, services/app-api/src/domain-models/contractAndRates/rateTypes.ts, services/app-api/src/domain-models/contractAndRates/revisionTypes.ts, services/app-api/src/domain-models/contractAndRates/statusType.ts, services/app-api/src/postgres/contractAndRates/parseContractAndRates.test.ts, services/app-api/src/postgres/contractAndRates/parseContractWithHistory.ts, services/app-api/src/postgres/contractAndRates/prismaDraftContractHelpers.ts, services/app-api/src/postgres/contractAndRates/prismaSharedContractRateHelpers.ts, services/app-api/src/testHelpers/contractAndRates/contractHelpers.ts, services/app-graphql/src/queries/fetchRate.graphql, services/app-graphql/src/queries/indexRates.graphql, services/app-graphql/src/schema.graphql, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.tsx, services/app-web/src/pages/SubmissionSummary/RateSummary.tsx
[MCR-3557](https://qmacbis.atlassian.net/browse/MCR-3557)
- `Submission this rate was submitted with` section
- This will show the submission this rate was submitted with.
- The shared rates submission link is now on the documents section like the current summary pages.
- Prisma query changes
- `includeContractFormData`
- `contractID` was not enough to generate a package name, so I'm including the contract data the revision belongs to
- This is mainly needed when querying rates and including its `contractRevisions`. Since querying contracts we have the data at the top level.
- GraphQL Schema and Domain Type changes
- Domain Types
- For `RateRevisionType`, the `contractRevisions` on this type only the `contractID` field; this was not enough data to generate a package name.
- I could add …
=> MCR-3557: Cms sees link to submission on rate summary page and shared rate submissions

services/app-api/src/postgres/contractAndRates/unlockRate.ts
This work fixes unlock rate not copying over `contractsWithSharedRateRevision`.
=> Copy contractsWithSharedRateRevision when unlocking rate.

services/app-api/src/handlers/proto_to_db.test.ts, services/app-api/src/postgres/contractAndRates/proto_to_db_CleanupLastMigration.ts, services/app-api/src/resolvers/healthPlanPackage/submitHealthPlanPackage.test.ts, services/app-api/src/resolvers/healthPlanPackage/unlockHealthPlanPackage.test.ts, services/app-api/src/resolvers/healthPlanPackage/updateHealthPlanFormData.test.ts, services/app-api/src/resolvers/healthPlanPackage/updateHealthPlanFormData.ts, services/app-api/src/testHelpers/gqlHelpers.ts, services/app-web/src/common-code/proto/healthPlanFormDataProto/healthPlanFormDataEncoding.test.ts, services/app-web/src/common-code/proto/healthPlanFormDataProto/toProtoBuffer.ts, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx
We're seeing duplicate entries in the rates table for updated rates.
This was due to the fact that we were not actually perpetuating the UUID for rateInfos correctly. The front end didn't send the ID in its updateHPFD api call, so it was getting reset on every call to that API from the RateDetails page. This PR will stop the bleeding, future unlocked submissions will no longer create duplicate rates. A following PR will clean up the existing rates. I expect there to be duplicate rates for both migrated and unmigrated data. 
[MCR-3566: Previous versions of rates are displayed on the rates dashboard](https://qmacbis.atlassian.net/browse/MCR-3566)
We didn't effectively test this because it's a failure in between app-web and app-api. I'm not sure how to test this yet outside of the yet to be …
=> Get stricter about rateinfo ids

docs/technical-design/contract-rate-change-history.md, services/app-api/src/domain-models/contractAndRates/revisionTypes.ts, services/app-api/src/postgres/contractAndRates/parseContractAndRates.test.ts, services/app-api/src/postgres/contractAndRates/parseContractWithHistory.ts, services/app-api/src/postgres/contractAndRates/parseRateWithHistory.ts, services/app-api/src/postgres/contractAndRates/prismaDraftRatesHelpers.ts, services/app-api/src/postgres/contractAndRates/prismaSharedContractRateHelpers.ts, services/app-api/src/postgres/contractAndRates/unlockContract.test.ts, services/app-api/src/resolvers/contractAndRates/fetchRate.test.ts, services/app-api/src/resolvers/healthPlanPackage/submitHealthPlanPackage.test.ts, services/app-api/src/resolvers/healthPlanPackage/submitHealthPlanPackage.ts, services/app-api/src/testHelpers/contractAndRates/rateHelpers.ts, services/app-api/src/testHelpers/gqlHelpers.ts, services/app-api/src/testHelpers/healthPlanPackageHelpers.ts, services/app-web/src/components/DataDetail/DataDetailContactField/DataDetailContactField.tsx
[MCR-3570](https://qmacbis.atlassian.net/browse/MCR-3570)
**Bug**
Previous contract submissions would contain incorrect rate data.
**Cause**
`contractWithHistoryToDomainModel` builds the contract revision history for a contract. Each contract revision record from the **database** will include rate revisions after the contract revision has been submitted, but `contractWithHistoryToDomainModel` did not account for these rate revisions. So they would get added to the contract revision history and remove the previous version of that rate revision. This results in the history not displaying the correct rate revision when the contract was submitted.
**Reproduction steps**
- Create and submit a contract and rate submission.
- Unlock submission and edit rate.
- Resubmit the submission.
- View the …
=> MCR-3570 fix: Previous contract submissions contained incorrect rate data

services/app-api/src/resolvers/contractAndRates/indexRates.test.ts, services/app-api/src/testHelpers/gqlHelpers.ts
Three tests that attempt to cover/fail for the three issues we saw in the rates dashboard this week. 
https://qmacbis.atlassian.net/browse/MCR-3570
https://qmacbis.atlassian.net/browse/MCR-3566
https://qmacbis.atlassian.net/browse/MCR-3567
- `returns a rate with history with correct data in each revision`
- `does not add rates a draft contract and rates package submitted later as contract only`
- `does not add any rates when contract only packages submitted`
=> Tests for indexRates bugs

services/app-api/src/postgres/contractAndRates/findRateWithHistory.test.ts, services/app-api/src/postgres/contractAndRates/parseRateWithHistory.ts, services/app-api/src/testHelpers/contractAndRates/contractHelpers.ts
Fixes rate history revisions contract data.
This fix refactors `rateWithHistoryToDomainModel` to only include the earliest submitted contract after the rate revision submission `submitInfo.updatedAt`. Any proceeding contract revision with the same `contractID` will be skipped.
There was a discussion in [DTBM 10.24.23](https://docs.google.com/document/d/1uVi5I_7KUPskeUQpkdWeWg4qP4ejwNJAiF1GJlfQFM4/edit) around the `Submission this rate was submitted with` and if it should link to the latest submission summary or the submission summary that this rate was submitted with. Specifically, when a rate was removed, the summary is still linked to the latest submission summary.
=> Fix rate history contract revisions

services/app-web/src/pages/App/AppRoutes.tsx, services/app-web/src/pages/MccrsId/MccrsId.module.scss, services/app-web/src/pages/MccrsId/MccrsId.test.tsx, services/app-web/src/pages/MccrsId/MccrsId.tsx
- Adds `<Breadcrumbs>`
- Changes the placement of the `/mccrs-record-number` route so that it's no longer embedded within the `SideNav` route. This is because [design says](https://qmacbis.atlassian.net/browse/MCR-2616?focusedCommentId=125169) this page won't ever display the side nav. So instead of getting the package through the side nav context this PR updates the mccrs id page to fetch the health plan package instead
https://qmacbis.atlassian.net/browse/MCR-2616
Breadcrumbs have been added to the `/mccrs-record-number` page
=> [MCR-2616] add breadcrumbs to mccrs id page

services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsTable.tsx, services/cypress/integration/cmsWorkflow/rateReview.spec.ts, services/cypress/support/apiCommands.ts, services/cypress/support/commands.ts, services/cypress/support/index.ts, services/cypress/support/loginCommands.ts, services/cypress/utils/apollo-test-utils.ts
Add test that goes to rates dashboard and checks a rate summary page
https://qmacbis.atlassian.net/browse/MCR-3583
Tests pass
=> Rates dash cypress

services/app-web/package.json, services/app-web/src/components/SectionHeader/SectionHeader.module.scss, services/app-web/src/components/SectionHeader/SectionHeader.stories.tsx, services/app-web/src/components/SectionHeader/SectionHeader.test.tsx, services/app-web/src/components/SectionHeader/SectionHeader.tsx, services/app-web/src/components/SubmissionSummarySection/ContactsSummarySection/ContactsSummarySection.stories.tsx, services/app-web/src/components/SubmissionSummarySection/ContactsSummarySection/ContactsSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/ContactsSummarySection/ContactsSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.stories.tsx, services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.stories.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/SubmissionTypeSummarySection/SubmissionTypeSummarySection.stories.tsx, services/app-web/src/components/SubmissionSummarySection/SubmissionTypeSummarySection/SubmissionTypeSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/SubmissionTypeSummarySection/SubmissionTypeSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/SupportingDocumentsSummarySection/SupportingDocumentsSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/SupportingDocumentsSummarySection/SupportingDocumentsSummarySection.tsx, services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsDashboard.test.tsx, services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsTable.test.tsx, services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsTable.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/ReviewSubmit.tsx, yarn.lock
- Fix text display on filters and in rate table as per this [comment](https://qmacbis.atlassian.net/browse/MCR-2617?focusedCommentId=125108 )
- Update react-select so we get better a11y behavior - should announce "deselected" clearly now.
- Fix `SectionHeader.module.scss` - target mcrrs styles more to bring download buttons back in alignment.
-  See images for before/after.
- Rename `navigateTo` since now they are other links in the section header (such as mc-crs id) 
https://qmacbis.atlassian.net/browse/MCR-2617
Before:
After:
react-select (any program or package dropdown) should still be working well for us
=> Further styling cleanup for rate summary/dashboard

services/app-web/src/constants/routes.ts, services/cypress/integration/stateWorkflow/dashboard/dashboard.spec.ts, services/cypress/integration/stateWorkflow/login/login.spec.ts, services/cypress/support/loginCommands.ts
This PR implements Hana's [suggestion](https://qmacbis.atlassian.net/browse/MCR-3568?focusedCommentId=125483) to add more details to the page titles for the dashboard submissions and rate review pages. 
- Replaces the previous "Dashboard" title for both the submissions and rate review pages to be "Submissions Dashboard" and "Rate Reviews Dashboard" so that the screen readers and all users are given more context on which page they're on when switching between the submissions and rate review tabs
https://qmacbis.atlassian.net/browse/MCR-3568
https://github.com/Enterprise-CMCS/managed-care-review/assets/67110378/d189ca45-c4b9-4359-88b4-613c712bd239
=> [MCR-3568] CMS Dashboard Page Title Accessibility improvement 

services/app-web/src/components/Breadcrumbs/Breadcrumb.test.tsx, services/app-web/src/components/Breadcrumbs/Breadcrumbs.module.scss, services/app-web/src/components/Breadcrumbs/Breadcrumbs.stories.tsx, services/app-web/src/components/Breadcrumbs/Breadcrumbs.tsx, services/app-web/src/pages/MccrsId/MccrsId.module.scss, services/app-web/src/pages/MccrsId/MccrsId.tsx, services/app-web/src/pages/QuestionResponse/UploadQuestions/UploadQuestions.tsx, services/app-web/src/pages/QuestionResponse/UploadResponse/UploadResponse.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx
This PR resolves 2 A11y issues in the MCCRS record number flow
**Bug 1**
- Located on the submission summary page, after a MCCRS record number has been added for a submission
- If you click on the MCCRS record number (that is a link to the mccrs system) you should now hear a clear label for this link instead of silence
- If you click on the "Edit MCCRS record number" link you should now hear a clear label for this link instead of silence
**Bug 2**
- Located on the Add MCCRS record number page
- Tabbing through the breadcrumbs, the middle breadcrumb for the submission page should no longer be read out as current page
- Added in this PR is the ability to tab to the third breadcrumb and hear that the mccrs record number page is the current page
https://qmacbis.atlassian.net/browse/MCR-3625 …
=> [MCR-3625] MCCRS Record Number page a11y fixes

services/app-graphql/src/schema.graphql
[MCR-3754](https://qmacbis.atlassian.net/browse/MCR-3754)
Duplicate enums in `schema.graphql` caused errors that broke the explorer tool.
Visit the endpoint `/dev/graphql-explorer` and make sure the schema loads without errors, and you can run a query. If there is an error, a pop-up will appear at the lower right of the app.
=> Fix graphQL schema errors and the graphQL explorer tool

services/app-web/src/constants/statutoryRegulatoryAttestation.ts, services/cypress/support/stateSubmissionFormCommands.ts
Update 438 non-compliance text box label text. See this [comment](https://qmacbis.atlassian.net/browse/MCR-3601?focusedCommentId=125737) in Jira.
=> Update 438 attestation text box label text.

services/app-api/serverless.yml
Prod is hitting the timeout when trying to create a large bulk download file. Increasing the timeout from around 6 to 60 seconds to see if that fixes the issue.
=> Increase timeout when creating bulk download zip file.

services/uploads/jest.config.ts, services/uploads/src/lambdas/avScan.ts, services/uploads/src/lib/avScan.test.ts, services/uploads/src/lib/avScan.ts
We've had a long standing issue where occasionally files in our CI tests are marked as viruses. It looks like that's because we run avScan on a directory of files that gets added to on subsequent scans, so a single valid failure can then mark future scans as failures. 
This fix does all scanning in a tmp directory which should fix this bug restoring peace to our CI runs. 
https://qmacbis.atlassian.net/browse/MCR-2647
=> run avScan in tmp dirs

.github/workflows/deploy-app-to-env.yml, .github/workflows/deploy.yml, .github/workflows/promote.yml
Bumps [actions/download-artifact](https://github.com/actions/download-artifact) from 3 to 4.
Bumps [actions/upload-artifact](https://github.com/actions/upload-artifact) from 3 to 4.
- Both need to be on 4 for them to merge. See the comment from @mojotalantikite [here](https://github.com/Enterprise-CMCS/managed-care-review/pull/2125#issuecomment-1861385208).
- Changed some duplicate action/upload-artifact names. Duplicate names no longer allowed [actions/upload-artifact breaking changes](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes)
=> Bump actions download and upload artifact from 3 to 4

.github/workflows/promote.yml
We changed the upload-artifact name for the `gen` folders on prod. `cypress-prod` needs to look for the new artifact name for the download steps.
=> Fix promote cypress-prod actions/download-artifact name.

docs/technical-design/api-jwt-security.md, services/app-api/package.json, services/app-api/src/domain-models/apiKey.ts, services/app-api/src/domain-models/index.ts, services/app-api/src/handlers/apollo_gql.ts, services/app-api/src/jwt/index.ts, services/app-api/src/jwt/jwt.test.ts, services/app-api/src/jwt/jwt.ts, services/app-api/src/resolvers/APIKey/createAPIKey.test.ts, services/app-api/src/resolvers/APIKey/createAPIKey.ts, services/app-api/src/resolvers/APIKey/index.ts, services/app-api/src/resolvers/configureResolvers.ts, services/app-api/src/testHelpers/gqlHelpers.ts, services/app-graphql/src/mutations/createAPIKey.graphql, services/app-graphql/src/schema.graphql, yarn.lock
This is step one for adding a new page that can generate JWTs. 
I created a new GraphQL mutation for creating a new API Token. 
I created a new service module called `jwt` that wraps what seemed like overwhelmingly the most popular JWT JS library. 
@pearl-truss I think you will want to use the JWTLib I added here to do the validation of the JWT coming in to the lambda authorizer. Feel free to modify it at will, I made the API just return a user ID from the token, that might not be all we need? I think it's got what I need for the creation page is what I was focused on. 
https://qmacbis.atlassian.net/browse/MCR-3833
=> Add createAPIToken endpoint and jwtLib service

services/app-api/serverless.yml
New `graphql_external` endpoint created. This is a copy of the `graphql` endpoint with the following changes:
- ~~Only has a get method. I believe we said we would limit 3rd parties to queries for now.~~ I added in the post method because of the language in https://qmacbis.atlassian.net/browse/MCR-3836 seems like it's something we will eventually implement
- URL path to invoke is `v1/graphql/external` per eng notes on the ticket
- 3rd party authorizer is attached
https://qmacbis.atlassian.net/browse/MCR-3835
I tested locally with curl
```
curl \
--request GET \
--header "Accept: text/javascript" \
--header "Authorization: Bearer {token}" \
--data '{"query": "query { indexHealthPlanPackage { totalCount edges{} } }"}' \
http://127.0.0.1:3030/local/v1/graphql/external
```
**With a valid …
=> MCR-3835: Attach lambda authorizer to api gateway endpoint

services/postgres/serverless.yml
We received a security alert from CMS cloud that the security group rule that allows access on `0.0.0.0/0` for ssh (protected by pub key auth) is disallowed. That rule was automatically reverted by their scanning and we've been adding dev IPs to an allowlist for ssh. They've asked us to also remove that open rule from our automation, which is what this is.
This adds the dev IPs that were manually added to the security group to our cloud formation template for that security group.
https://qmacbis.atlassian.net/browse/MCR-3825
=> Add dev IPs to jump box security group

services/app-api/src/resolvers/configureResolvers.ts, services/app-api/src/resolvers/rate/unlockRate.test.ts, services/app-api/src/resolvers/rate/unlockRate.ts, services/app-api/src/testHelpers/assertionHelpers.ts, services/app-api/src/testHelpers/contractAndRates/contractHelpers.ts, services/app-api/src/testHelpers/contractAndRates/rateHelpers.ts, services/app-api/src/testHelpers/errorHelpers.ts, services/app-api/src/testHelpers/gqlHelpers.ts, services/app-api/src/testHelpers/index.ts, services/app-api/src/testHelpers/stateHelpers.ts, services/app-graphql/src/mutations/unlockRate.graphql, services/app-graphql/src/schema.graphql, services/app-web/src/components/SectionHeader/SectionHeader.module.scss, services/app-web/src/components/SectionHeader/SectionHeader.test.tsx, services/app-web/src/components/SectionHeader/SectionHeader.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/UnlockRateButton.tsx, services/app-web/src/gqlHelpers/mutationWrappersForUserFriendlyErrors.ts
Add rate unlock button
Reminder: no banners, no modal yet. All that happens is that when CMS user clicks the button, we hit the `unlockRate`. The button starts showing up disabled while the rate is unlocked.
https://qmacbis.atlassian.net/browse/MCR-3767
- **(from design review)**  We talked about how the rate name was was not breaking properly. There's empty space to the right of the first line. Looks like css `break-word` or overflow does not work as expected because our name also includes numbers. I found a solution using HTML entities in [cf47ef1](https://github.com/Enterprise-CMCS/managed-care-review/pull/2166/commits/cf47ef17c6ffcc513d7a7a805bc10c4d103f59b4) but pulled it off this PR to refine it more and ship as it's own work. FYI @kelseylistrom still working on this. 
`app-web`
- …
=> MCR-3767 CMS has unlock rate button

services/app-web/src/pages/App/AppRoutes.tsx, services/app-web/src/pages/SubmissionSummary/RateSummary/RateSummary.test.tsx, services/app-web/src/pages/SubmissionSummary/RateSummary/RateSummary.tsx
Added a new route for state users to be able to view rate summary's when accessing the `/rates/:id` url, the dashboard link has also been changed to route to the standard dashboard for state users but still routes to the rates dashboard for CMS users.
[MCR-3813](https://qmacbis.atlassian.net/browse/MCR-3813)
Wrote two unit tests:
- State user has access to `/rates/:id`
- Expected error page is rendered when rate ID is invalid
visit the `/rates/:id` url as a state user using a valid rate id
=> MCR-3813: Made rate summary route available to state user

services/infra-api/serverless.yml
We got a security hub alert about needing to force SSL on buckets, and the New Relic data hose bucket is the only one that we don't have an explicit SSL deny on. This adds the policy to that bucket to close out that alert.
https://qmacbis.atlassian.net/browse/MCR-2246
=> Force SSL on the New Relic datahose bucket

services/infra-api/serverless.yml
This policy seems to already exist in `main`, reverting it while I figure out why it's conflicting with already deployed resources to unblock promotes.
Reverts Enterprise-CMCS/managed-care-review#2180
=> Revert "Force SSL on the New Relic datahose bucket"

.github/workflows/deploy.yml
The last PR to land had a moved sha to my branch name to pick up the deploy workflow. This moves the sha back to main.
=> Point deploy back to main after av-layer merge

docs/technical-design/launch-darkly-testing-approach.md, services/app-web/package.json, services/app-web/src/components/SubmissionSummarySection/ContactsSummarySection/ContactsSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.test.tsx, services/app-web/src/pages/App/AppBody.test.tsx, services/app-web/src/pages/App/AppRoutes.test.tsx, services/app-web/src/pages/Landing/Landing.test.tsx, services/app-web/src/pages/QuestionResponse/QuestionResponse.test.tsx, services/app-web/src/pages/QuestionResponse/UploadQuestions/UploadQuestions.test.tsx, services/app-web/src/pages/QuestionResponse/UploadResponse/UploadResponse.test.tsx, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.test.tsx, services/app-web/src/pages/SubmissionSideNav/SubmissionSideNav.test.tsx, services/app-web/src/pages/SubmissionSummary/RateSummary/RateSummary.test.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.test.tsx, services/app-web/src/testHelpers/index.ts, services/app-web/src/testHelpers/jestHelpers.tsx, yarn.lock
[MCR-3758](https://qmacbis.atlassian.net/browse/MCR-3758)
- Replace `ldUseClientSpy` with `LDProvider` to configure feature flags for unit testing.
- Using `LDProvider` to initialize our tests because `jest.spyOn` used in `ldUseClientSpy` is not working with `launchdarkly-react-client-sdk` versions 3.0.9 and above. I'm not exactly sure why it stopped working. I've tried to fully construct a `useLDClient` `mockImplemenation` in `ldUseClientSpy` with no success.
- With `LDProvider`, we are initializing a mocked `ldClient` for our unit tests when using `renderWithProviders`. Since we are initializing the `ldClient` outside of `LDProvider,` it does not do it internally, which requires an API call to LaunchDarkly; we are isolating tests from flag values in LaunchDarkly.
- With using …
=> MCR-3758: Update launch darkly and fix testing

.github/workflows/deploy.yml
This is your typical PR to move the deploy workflow back to point to `main` after a PR.
=> Move the infra deploy.yml to main

services/app-web/src/hooks/useTealium.ts
It was pointed out in adding event tracking analytics that we aren't running `utag.view` in initial app load, only when we switch pages. This PR addresses that by adding a call to register tags on the initial load `useEffect`.
https://qmacbis.atlassian.net/browse/MCR-3891
https://jira.cms.gov/browse/BLSTANALYT-7038 
This could be tested with breakpoints - checking that appropriate effect fires when expected when launching the SPA
=> Send utag.view tag data on initial app load

services/app-web/src/hooks/useTealium.ts
This should address the issue the cause the failed promote referenced in #2229. Please take a look though, let me know your thoughts. This adds a second to the initial app load before tealium called. From what I can tell from those tags usually take around 35 ms to load. 
Also added guard clause so this won't break app compile when window.utag is not set yet. 
#2215
=> bugfix: make sure utag.view exists

.github/workflows/deploy.yml
This just moves the branch pointer back to main for the infra deploy after a change in the last PR to land.
=> Re-point infra deploy to main

services/app-api/src/resolvers/rate/fetchRate.ts, services/app-web/src/pages/Errors/ErrorForbiddenPage.tsx, services/app-web/src/pages/RateEdit/RateEdit.tsx, services/app-web/src/pages/SubmissionSummary/RateSummary/RateSummary.tsx
…tate code
A continuation to MCR-3793, the purpose of this PR is to deny access to rates from unrelated states (i.e. Minnesota should not be able to access Virginia's rates)
[MCR-3813](https://jiraent.cms.gov/browse/MCR-3813)
Will display custom error message if provided:
Standard forbidden error message if no error message is provided:
1. Grab a rate id of your choice
2. Log in as a state user that differs from the state attached to the rate
3. When visiting `/rates/:id` and `rates/:id/edit` you should be met with the Forbidden error page
=> MCR-3813 Restricting rate access to each respective state

services/postgres/serverless.yml
Amazon has removed the python runtime that we had originally set up our lambda secrets manager rotator with, which caused CI to fail in deploys of the `postgres` service. This PR bumps the runtime to the latest python runtime available in AWS for lambdas.
https://jiraent.cms.gov/browse/MCR-3951
=> Bump python lambda runtime on secrets manager rotator

services/github-oidc/serverless.yml
I've noticed that on my PR branch for #2256 the `github-oidc` service has started running changes off of the `main` deploy, rather than my local branch. Since I have changes to what that provider can do -- namely talk to Route53 -- I've noticed that the branch no longer deploys all of a sudden. I've opened a bug ticket (below), but until then I need this permission on that provider for my PR to run in CI now. 
https://jiraent.cms.gov/browse/MCR-3958
=> Add Route53 permissions to github-oidc

services/app-web/src/pages/RateEdit/RateEdit.tsx, services/app-web/src/pages/StateSubmission/PageActions/PageActions.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.test.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.tsx, services/app-web/src/pages/StateSubmission/StateSubmissionForm.module.scss, services/app-web/src/pages/StateSubmission/StateSubmissionForm.tsx
Addressing a point from design review
- Rate Summary page buttons should say Cancel and Submit ... not Back and Continue
Also noticed  🐛s:
- the validation error messages for capitation rates and the actuary preference were not displaying the proper strings. This was due to `null` instead of `undefined` types passing through to yup validators
- banner styles not consistent for unlocked on review and submit versus summary page
https://jiraent.cms.gov/browse/MCR-3771
=> MCR-3777 Design review feedback

services/app-graphql/src/schema.graphql
This PR adds GraphQL types for Contracts and ContractEditions.
I'm still not completely happy with these names, but this should get us started in implementing the FE and the BE.
https://jiraent.cms.gov/browse/MCR-3948
=> Add Contract types to GraphQL

services/app-graphql/src/schema.graphql
Adds the GQL for our updateDraftContractRates mutation to GQL
Unfortunately GQL does not support unions for inputs, so we kind of fake one here with validation on the server side. 
This supports Hana's work on the RateInfo page
=> add updateDraftContractRates mutation to GQL

services/uploads/serverless.yml, services/uploads/src/avLayer/clamd.conf, services/uploads/webpack.config.js
It turns out the reason why DNS wasn't resolving properly in val and prod for `clamav.mc-review.local` in PR #2256 was because when CMS provisioned our VPCs, hostname resolution wasn't turned on in higher environments. Now that it's turned on, we should be fine going back to the simpler version here of using the same hostname across environments.
https://jiraent.cms.gov/browse/MCR-3960
=> Use single DNS name for clamav

services/app-web/src/components/Modal/UnlockSubmitModal.tsx, services/app-web/src/gqlHelpers/fetchHealthPlanPackageWrapper.ts, services/app-web/src/gqlHelpers/mutationWrappersForUserFriendlyErrors.ts, services/app-web/src/pages/StateDashboard/StateDashboard.tsx, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx
Remove caching on state submission form as per refactor plan for Contract & Rates Types. To recap...
_Benefits:_
-  prep for multiple APIs in use on frontend (HPP on some pages, contract and rates on other pages)
- reduce chance for regressions while we refactor page by page and also have feature flags in use (Linked Rates)
- ensure submission form, summary pages, dashboard and Q&A all fetch their own correct data
_Drawbacks:_
- During this interim period, we will have the loading indicator displaying more often when users change pages. 
- Cypress could get a little more flaky and times for cypress go up slightly
We can reduce the time period we have no caching by having a clear timeline to fully implement refactor 
None, this is prep for Linked Rates and having two versions of Rate …
=> Removing FE cacheing from application

services/app-web/src/components/FileUpload/FileUpload.tsx, services/app-web/src/pages/RateEdit/RateEdit.test.tsx, services/app-web/src/pages/RateEdit/RateEdit.tsx, services/app-web/src/pages/RateSummary/RateSummary.test.tsx, services/app-web/src/pages/StateSubmission/Contacts/ActuaryContactFields.tsx, services/app-web/src/pages/StateSubmission/Contacts/Contacts.tsx, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.tsx, services/app-web/src/pages/StateSubmission/Documents/Documents.tsx, services/app-web/src/pages/StateSubmission/ErrorOrLoadingPage.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetailsSchema.ts, services/app-web/src/pages/StateSubmission/RateDetails/SingleRateCert.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.test.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/SingleRateCertV2.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/SingleRateFormFields.tsx, services/app-web/src/pages/StateSubmission/StateSubmissionForm.tsx, services/app-web/src/testHelpers/apolloMocks/rateDataMock.ts, services/app-web/src/testHelpers/apolloMocks/rateGQLMocks.ts, services/app-web/src/testHelpers/jestRateHelpers.tsx
Main work completed:
- Implement  `MULTI` RateDetails workflow
- I saw some rendering issues after adding additional `useQuery` calls for the new APIs. I spent the most time on trying to investigate what is going on with re-renders.
- Change the API that is called to be conditional -  contract API if we are in MULTI, rate API if we are in SINGLE 
Other notes:
- noticed there's still something odd going on with `ProgramSelect` in terms of that UI triggering additional re-renders. However, addressing that seemed out of scope + needs more investigation. It is an existing issue.
https://jiraent.cms.gov/browse/MCR-3940
UI with linked rate flag off (red box shows the packages with shared rates UI is present) 
UI with linked rate flag on (no red box - these fields are not visible and we should …
=> MCR-3940 Change RateDetails page to call fetchContract

services/app-web/src/hooks/useTealium.ts
I think my last fix  #2215 still didn't fully resolve this - let's try this. Moving the tealium call to be in the `.then` 
How to test: This can be tested in review apps by removing the environment specific guard clause (see below) and then putting a breakpoint or console logging where we call utag.view  
```// Do not add tealium for local dev or review apps
if (process.env.REACT_APP_AUTH_MODE !== 'IDM') {
```
=> Tweak tealium more - get it loading on page launch

services/app-api/src/domain-models/contractAndRates/contractTypes.ts, services/app-graphql/src/mutations/updateDraftContractRates.graphql
A previous PR updated `stateContact` graphql types to have a `titleRole` instead of `title` field. This PR switches over a lingering `title` field that caused issues on promote 
`./dev generate` runs without graphql errors
=> MCR-3944 - titleRole grapqhl fix

services/app-web/src/pages/LinkYourRates/LinkRateSelect.tsx, services/app-web/src/pages/LinkYourRates/LinkYourRates.tsx
This PR adds expanded rate info to the link your rates dropdown options
Navigate to the rate details page of the form, select `Yes, this rate certification is part of another submission`, and scroll the dropdown
=> [MCR-3889] State user sees expanded rate info in dropdown

services/app-web/src/pages/LinkYourRates/LinkRateSelect.tsx
Quick fix for the rate name being displayed in the dropdown
Before:
After:
=> rate name fix

services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/RateDetailsSummarySectionV2.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/RateDetailsSummarySectionV2.tsx
This PR displays the shared rates UI on the uploads table of the ReviewSubmit page for historic submissions
- "historic" submissions are determined if the `packagesWithSharedRateCerts` field is populated (going forward this field this will not be used)
- While it was included as AC for this ticket, removing the "is this rate cert uploaded to any other submissions" field was already removed when the linked rates flag is on
https://jiraent.cms.gov/browse/MCR-3886
**V1 version**
**V2 version**
- shared rate UI is present when rate is shared
- shared rate UI is not present when the rate isn't shared
- Create a submission with the linked rates flag off so that you can populate the "is this uploaded to other submissions" field on the Rate Details page
- Once on the ReviewSubmit page turn the …
=> [MCR-3886] Display the shared rate UI on historic submissions

services/app-api/src/postgres/contractAndRates/findAllRatesWithHistoryBySubmitInfo.test.ts, services/app-api/src/postgres/contractAndRates/findAllRatesWithHistoryBySubmitInfo.ts, services/app-api/src/postgres/postgresStore.ts, services/app-api/src/resolvers/rate/indexRates.ts, services/app-graphql/src/queries/indexRates.graphql, services/app-web/src/components/SubmissionSummarySection/UploadedDocumentsTable/UploadedDocumentsTable.tsx, services/app-web/src/pages/LinkYourRates/LinkRateSelect.tsx, services/app-web/src/pages/LinkYourRates/LinkYourRates.stories.tsx, services/app-web/src/pages/LinkYourRates/LinkYourRates.test.tsx, services/app-web/src/pages/LinkYourRates/LinkYourRates.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetailsSchema.test.ts, services/app-web/src/pages/StateSubmission/RateDetails/RateDetailsSchema.ts, services/app-web/src/pages/StateSubmission/RateDetails/V2/LinkedRateSummary.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/SingleRateFormFields.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/rateDetailsHelpers.test.ts, services/app-web/src/pages/StateSubmission/RateDetails/V2/rateDetailsHelpers.ts, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ContactsSummarySectionV2.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/RateDetailsSummarySectionV2.tsx
**Still to do for demo**:  
**Not needed for demo but blockers for turning on Linked Rates for Production :**
_^ we need Jira tickets for this work or add to AC of remaining tickets_ 
**Notes on significant code changes:**
- adjusted `indexRates` to only return state user's state when a state user hits this API
- adjusted `LinkRateSelect`  to be a single select (not multi select)
- as soon as linked rate selected, override content in that  `rateForm` use the linked rate info instead. FieldArray `replace` will allow autofill of that linked rate. as soon as linked rate is cleared, clear the autofilled form data and go back to an empty `rateForm` 
- added `LinkRateSummary` to display instead of the form when there's a linked rate
https://jiraent.cms.gov/browse/MCR-3900
None yet.
- I …
=> State can select from a list of previously submitted rates on rate details page

services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/RateDetailsSummarySectionV2.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/RateDetailsSummarySectionV2.tsx
We want to show the legacy UI (rates across submissions) only for the submission summary experience. This is for historical data reasons.
For unlocked contracts currently being edited - e.g. Review and Submit - let's hide the old SHARED tag and related submissions field in the documents table.
product/design review on 
https://jiraent.cms.gov/browse/MCR-3886
- renders shared rate certifications when submission is locked
- does not render shared rate cert info if submission is being unlocked and being edited
- Look at legacy submission that has the old "rates across submissions" feature - such as[ MCR-MN-016](https://d25pfhkipqgt0p.cloudfront.net/submissions/4a1e13c9-1678-4a01-8d9c-fda00c694d68)
- See shared tag should be visible and linked submissions column is present
- Turn ON linked …
=> fix ReviewSubmitV2: Hide shared rates across submission when linked rates flag is on 

services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.tsx, services/app-web/src/pages/RateSummary/RateSummary.tsx
This is interim UI for when Linked Rates is turned on but unlock and edit for standalone rates is still turned off. 
For that case, we render an unlock rate button but redirect to the first related contract submission so the rate can be unlocked with the contract submission unlock. 
https://jiraent.cms.gov/browse/MCR-3905
-  `renders unlock button that redirects to contract submission page when standalone rate edit and unlock is disabled`
- get a submission in the dashboard
- log in as CMS user with linked rates feature flag ON but unlock edit rates flag OFF
- CMS user can click "Unlock rate" and they are redirected to the submission summary of the contract that made the rate
=> MCR-3905 CMS links from rate summary to parent submission to unlock a rate

services/app-web/src/pages/StateSubmission/RateDetails/V2/rateDetailsHelpers.ts
https://jiraent.cms.gov/browse/MCR-4000
- Turn Linked rates feature flag off
- Make a contract with rates submission
- Sign in as a CMS user and unlock the submission
- Go to the submission as a state user and navigate to the Rate Details page. It should now display as No for the linked rates question and the other fields should be editable
=> Prevent rates from being read as a linked rate just because its unlocked

services/app-web/src/pages/Settings/EmailSettingsTables/EmailAnalystsTable.tsx, services/app-web/src/pages/Settings/EmailSettingsTables/EmailSettingsTables.tsx, services/app-web/src/pages/Settings/Settings.module.scss
To prepare for 20+ changes to states list and emails, want to make this table easier to filter. Spot checking by eye is getting difficult because the table has too much data in it to grok all at once.
Decided to throw instate and email filters at the top to make it easier to check for specific entries. 
https://jiraent.cms.gov/browse/MCR-4028
This is dev only functionality for internal admins - dont think it needs QA.
=> Make state analysts email table easier to check

scripts/import-programs.ts, services/app-web/src/common-code/data/statePrograms.json
Added another correctness check to the script, otherwise just ran it on the new data.
Note: removing programs is dangerous, only doing that here because we've never had NY submissions before so nothing can be pointing at the deleted program. 
https://jiraent.cms.gov/browse/MCR-4020
=> update programs for 2024-04-22

services/app-web/src/pages/SubmissionSummary/V2/SubmissionSummaryV2.test.tsx, services/app-web/src/pages/SubmissionSummary/V2/SubmissionSummaryV2.tsx
- Pages in val were crashing instead of displaying the error container. The submissions with the failures hadn't had data migrated yet. One issue with page was the assumption that `contract.packageSubmissions[0].` would be populated. This PR updates to check the packageSubmissions length and return the generic error page when there aren't any submissions
- Updates the heading name to use the `contractName` field on the submitted contract revision 
https://jiraent.cms.gov/browse/MCR-4066
- Previously written test cases that were using a mocked draft submission failed and were updated to use a submitted contract
=> SubmissionSummaryV2 bug

services/app-web/src/pages/LinkYourRates/LinkRateSelect.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/LinkedRateSummary.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.test.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/rateDetailsHelpers.ts, services/app-web/src/testHelpers/apolloMocks/rateDataMock.ts
Fix for two bugs
[MCR-4036](https://jiraent.cms.gov/browse/MCR-4036): Rate submitted date is incorrect
[MCR-4037](https://jiraent.cms.gov/browse/MCR-4037): Link rates dropdown sort order is incorrect
`RateDetailsV2.test.ts`
- `lists dropdown options in desc order by latest submission date`
=> MCR-4036 & MCR-4037: link rates dropdown and linked rate submitted date

services/app-web/src/components/ChangeHistory/ChangeHistoryV2.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/SubmissionSummarySection.module.scss, services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/RateDetailsSummarySectionV2.tsx, services/app-web/src/pages/SubmissionSummary/V2/SubmissionSummaryV2.test.tsx, services/app-web/src/pages/SubmissionSummary/V2/SubmissionSummaryV2.tsx, services/app-web/src/testHelpers/apolloMocks/contractPackageDataMock.ts, services/cypress/integration/cmsWorkflow/unlockResubmit.spec.ts
- Turn on `unlockResubmit` for linked rate flag on.
- Fix unlock banner does not display bug
- Fix contract actions list display (emulate what we do for checkbox fields on summary pages)
- Fix "Initial contract" display (which was happening on migrated submissions on another branch) and it should not show the updated reason in the Change history anyway
https://jiraent.cms.gov/browse/MCR-4052
https://jiraent.cms.gov/browse/MCR-4073
- unlockResubmit tests pass for Cypress (except for previous submission page cases)
- As CMS user - Check a submitted package with linked rates for the "Contract actions" display". [example submission](https://dvwwmg3ijqha8.cloudfront.net/rates/deb2ccb5-3fdc-4d64-9191-b4ee236ae1d2)
- AS CMS user - Confirm unlock banner appears on unlock submission. [example …
=> unlockResubmit cypress for linked rates and other bugfix 

services/app-api/src/postgres/contractAndRates/parseContractWithHistory.ts, services/app-api/src/postgres/contractAndRates/parseRateWithHistory.ts, services/app-api/src/postgres/contractAndRates/prismaSharedContractRateHelpers.ts, services/app-api/src/resolvers/contract/submitContract.test.ts, services/app-api/src/resolvers/rate/fetchRate.test.ts, services/app-api/src/testHelpers/gqlContractHelpers.ts
We are seeing broken date handling with the document dateAdded fields.
This is the first pass at fixing those, but is specific to fetchContractWithHistory. 
This same fix will need to be applied to fetchRateWithHistory
But I think the idea that this is an in-place change that happens after putting together the list of revisions feels like the right direction. (though thinking about it, linked rates might lose some of that... not every linked rate revision is going to be in packageSubmissions)
It's definitely a bit of a tricky fix, b/c I'm updating the revision object's dates in situ. But that means there are actually a bunch of copies of those revisions we need to update:
* contract.submissionPackage.contractRevision
* contract.submissionPackage.rateRevisions
^ These are the two this …
=> move document date processing to end of parseContractWithHistory

services/app-web/src/components/SubmissionSummarySection/UploadedDocumentsTable/UploadedDocumentsTable.tsx
Follow on cleanup to a fix I made in #2378 where I [deleted the `('Draft')` handling](https://github.com/Enterprise-CMCS/managed-care-review/pull/2378/files#diff-97d1efcaeb0cb06ef777a0e379865170389f972294ac2521df366a9f60ebd4ddR108-R112) all together in the legacy rates across submissions UI shown on the summary pages. This was to address a [bug](https://jiraent.cms.gov/browse/MCR-4074).
To my eye, the way we were calculating Draft didn't seem proper anyway. Also, this is a legacy UI (the shared rates across submissions experience for state users) that we will be turning off within a week as we ship LinkedRates. [Product seemed to confirm this](https://cmsgov.slack.com/archives/C014CRU197U/p1714411273689879)  -- so going ahead and just deleting the code paths around handling draft shared …
=> Fully remove (Draft) handling from legacy shared rates UI

services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/UploadedDocumentsTable/DocumentTag.tsx, services/app-web/src/components/SubmissionSummarySection/UploadedDocumentsTable/UploadedDocumentsTable.test.tsx, services/app-web/src/components/SubmissionSummarySection/UploadedDocumentsTable/UploadedDocumentsTable.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/LinkedRateSummary.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ContractDetailsSummarySectionV2.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/RateDetailsSummarySectionV2.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ReviewSubmitV2.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/SubmissionTypeSummarySectionV2.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/SubmissionTypeSummarySectionV2.tsx, services/app-web/src/pages/SubmissionSummary/V2/SubmissionSummaryV2.tsx
- If there's missing data the field is not included in the UI for the submission summary page
- submission date is now included for all submitted submissions on the submission summary page
https://jiraent.cms.gov/browse/MCR-4072
[MCR-4069](https://jiraent.cms.gov/browse/MCR-4069)
https://jiraent.cms.gov/browse/MCR-4071
- Missing fields are not displayed on submission summary page
- Warning for multiple files is not included on any pages (_Hana note: think this is the implied scope of MCR-4071 and trying to prepare for linked rates_)
- renders SHARED tag on docs table to CMS users when packages across submissions present 
- renders SHARED tag to state users when packages across submissions present
- It's not possible to get a new submission into a state with missing required information. …
=> Remove incomplete warnings on submission summary page

services/app-web/src/gqlHelpers/contractsAndRates.ts, services/app-web/src/pages/App/AppRoutes.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ContactsSummarySectionV2.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ContactsSummarySectionV2.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ContractDetailsSummarySectionV2.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ContractDetailsSummarySectionV2.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/RateDetailsSummarySectionV2.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ReviewSubmitV2.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/SubmissionTypeSummarySectionV2.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/SubmissionTypeSummarySectionV2.tsx, services/app-web/src/pages/SubmissionRevisionSummary/SubmissionRevisionSummaryV2.test.tsx, services/app-web/src/pages/SubmissionRevisionSummary/SubmissionRevisionSummaryV2.tsx, services/app-web/src/pages/SubmissionRevisionSummary/index.ts, services/app-web/src/pages/SubmissionSummary/V2/SubmissionSummaryV2.tsx, services/app-web/src/testHelpers/apolloMocks/contractPackageDataMock.ts, services/app-web/src/testHelpers/apolloMocks/index.ts
- Update SubmissionRevisionSummary to use fetchContract
- Skipped test will be addressed in a follow on PR for this ticket
- Create a linked rate submission
- Unlock and then resubmit the submission with a different rate
- Revision page should show the correct rate name for each revision reversion
=> Create SubmissionRevisionSummaryV2 to use Contract data

services/app-web/src/pages/StateSubmission/Contacts/ActuaryContactFields.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx, services/app-web/src/pages/StateSubmission/RateDetails/SingleRateCert.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/SingleRateFormFields.tsx, services/app-web/src/pages/StateSubmission/StateSubmissionForm.module.scss
Fixed form errors not showing up and some styling.
Form Errors
- [Slack about form errors](https://cmsgov.slack.com/archives/C014CRU197U/p1714488591378709?thread_ts=1714487387.788659&cid=C014CRU197U)
- under actuarial firm if I select "other" the validation error "you must enter a description" appears right away. It should only appear after I hit continue
- If I am missing a form field in the additional actuaries and try to continue, I get only line item errors. I am NOT seeing the error appear within the error summary banner at the top like I would expect.
- I also find "remove" to be vague given all the competing links. I would suggest "remove certifying actuary" or something like that. (there are a lot of links, something for Kelsey to noodle on I think, but not a blocker)
UI styling
- …
=> Fix form errors and styling on rate details page

services/app-web/src/pages/LinkYourRates/LinkRateSelect.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.test.tsx
This PR is to address the dropdown menu which opens by default when the yes radio button is selected on the rate details page. With these changes the dropdown should no longer open unless clicked by the user.
Tests remained the same minus minor updates to address the changed behavior
- Start a new submission with rates or navigate to the rate details page via the summary page on an already existing submission.
- Once on the rate details page click the `Yes, this rate certification is part of another submission` radio button
- The dropdown should render but remain closed and only expands when clicked.
=> [MCR-4038] dropdown menu does not open until the user clicks into field

services/app-api/src/postgres/contractAndRates/unlockContract.ts, services/app-api/src/resolvers/contract/submitContract.test.ts
If you removed a child rate, on unlock it would error saying you can't unlock an already unlocked rate
https://jiraent.cms.gov/browse/MCR-4093
made a new API test that reproduced the problem
try the steps in the bug
=> Fix unlock removed child rate crasher

services/app-api/src/postgres/contractAndRates/parseRateWithHistory.ts, services/app-api/src/postgres/contractAndRates/prismaSubmittedRateHelpers.ts, services/app-api/src/resolvers/rate/submitRate.test.ts
We were seeing contracts disappear on linked rates when contracts+rates were resubmitted. This forces rate revs to always have the latest set of contracts associated with them. 
https://jiraent.cms.gov/browse/MCR-4091
https://jiraent.cms.gov/browse/MCR-4095
I thought there was a third one
=> Have rate revisions return the most recent set of contracts

services/app-api/src/postgres/contractAndRates/submitContract.ts, services/app-api/src/resolvers/contract/submitContract.test.ts
I was able to reproduce this issue we were seeing on val by making three contracts that each had rates linking to one another. Once I unlocked the first contract to recursively link it to the other ones, I couldn't submit it. 
Fix was just to filter out our links to only create unique ones. 
I tested this by pulling down val. 
After this merges, https://mc-review-val.onemac.cms.gov/submissions/1915bbe8-a519-4555-b6fd-f2296a47e873/edit/review-and-submit should be submittable. 
https://jiraent.cms.gov/browse/MCR-4099
made a new test that reproduced the crash
make a couple submissions that each link to each others rates. They should all be submittable
=> Fix recursive linked rates submit crash

services/app-api/src/domain-models/contractAndRates/convertContractWithRatesToHPP.ts, services/app-api/src/resolvers/healthPlanPackage/contractAndRates/resolverHelpers.ts, services/app-web/src/common-code/healthPlanFormDataMocks/healthPlanFormData.ts, services/app-web/src/common-code/proto/healthPlanFormDataProto/toDomain.ts, services/app-web/src/common-code/proto/healthPlanFormDataProto/toProtoBuffer.ts, services/app-web/src/components/DataDetail/DataDetailContactField/DataDetailContactField.tsx, services/app-web/src/components/SubmissionSummarySection/ContactsSummarySection/ContactsSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/ContactsSummarySection/ContactsSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/ContactsSummarySection/index.ts, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.tsx, services/app-web/src/components/SubmissionSummarySection/index.ts, services/app-web/src/gqlHelpers/contractsAndRates.ts, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.test.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetailsSchema.ts, services/app-web/src/pages/StateSubmission/RateDetails/SingleRateCert.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/SingleRateFormFields.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/rateDetailsHelpers.ts, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ContactsSummarySectionV2.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ContactsSummarySectionV2.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/RateDetailsSummarySectionV2.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/RateDetailsSummarySectionV2.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.test.tsx, services/cypress/integration/cmsWorkflow/unlockResubmit.spec.ts, services/cypress/integration/cmsWorkflow/viewSubmission.spec.ts, services/cypress/integration/stateWorkflow/stateSubmissionForm/rateDetails.spec.ts, services/cypress/support/stateSubmissionFormCommands.ts
[MCR-4088](https://jiraent.cms.gov/browse/MCR-4088)
[Figma](https://www.figma.com/file/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?type=design&node-id=12168-102675&mode=design&t=fdPmi5rqLTxBsv5H-0)
- Fixed the issue of Actuary communication preference not  being displayed with data by updating UI
- Moved Actuary communication preference radio to each rate certification section on the Rate details page.
- This change is applied to both V1 and V2
- V1 saves Actuary communication preference to each respective rate instead of top level package
- Moved Additional actuaries and Actuary communication preferences to each respective rate certification section on the review and submit and summary pages.
- Added Additional actuaries and Actuary communication preferences to the rate summary page.
=> MCR-4088: actuary comm preference not functioning correctly for linked rates and UI changes.

services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.tsx
[MCR-4101](https://jiraent.cms.gov/browse/MCR-4101)
- Fix RateDetailsV2 routing on the back button
- Fix was to switch routes based on `displayAsStandaloneRate`.
=> MCR-4101: Navigating using Back button on rate details page takes user to dashboard.

services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ContractDetailsSummarySectionV2.test.tsx, services/app-web/src/pages/SubmissionRevisionSummary/SubmissionRevisionSummaryV2.test.tsx, services/app-web/src/pages/SubmissionRevisionSummary/SubmissionRevisionSummaryV2.tsx, services/app-web/src/testHelpers/apolloMocks/contractPackageDataMock.ts
off by one error computing index. We want the indices for history revisions to be 1 indexed, not 0 indexed
https://jiraent.cms.gov/browse/MCR-4100
Should be able to look at past submissions in all their glory now
=> fix contract history index

services/app-web/src/components/DynamicStepIndicator/DynamicStepIndicator.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ReviewSubmitV2.tsx, services/app-web/src/pages/StateSubmission/StateSubmissionForm.tsx
This fixes the step indicator to only display the `Rate details` segment for contract and rate submissions and vice versa on the review submit page
[MCR-4090](https://jiraent.cms.gov/browse/MCR-4090)
- Access an unlocked contract only submission and verify the rate details step indicator segment does not exist 
- Access an unlocked contract and rates submission and verify the rate details step indicator segment does exist
=> [MCR-4090] fixing rate details step indicator bug

.github/workflows/promote.yml
I was waiting to do some dev testing on a newly merged PR and noticed that we run the 'lock this branch' script before doing any sort of unit tests in `promote`. When the previous merge finishes `promote`, the next one in the queue starts promoting, which includes running unit tests, which takes about 11 minutes between environment setup and tests. I don't see any reason not to run those tests before waiting, which will let a new `promote` taken off the queue just go straight into the `promote` rather than having to then run unit tests.
=> Change where we wait in 'promote' GHA

services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/SubmissionTypeSummarySectionV2.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/SubmissionTypeSummarySectionV2.tsx, services/app-web/src/pages/SubmissionRevisionSummary/SubmissionRevisionSummaryV2.test.tsx, services/app-web/src/pages/SubmissionRevisionSummary/SubmissionRevisionSummaryV2.tsx
A couple things were missing from the submission revision summary page, this adds them back.
https://jiraent.cms.gov/browse/MCR-4100
For a submission that is older than today, please confirm that the Submitted date on a previous revision shows correctly
=> display id and submitted at date in past revision summary

services/app-web/src/components/ChangeHistory/ChangeHistoryV2.test.tsx, services/app-web/src/components/ChangeHistory/ChangeHistoryV2.tsx, services/app-web/src/pages/SubmissionRevisionSummary/SubmissionRevisionSummaryV2.tsx, services/app-web/src/testHelpers/apolloMocks/contractPackageDataMock.ts
This PR fixes an issue with unlock events not appearing in the change history when the submission is a draft (state hadn't resubmitted yet)
https://jiraent.cms.gov/browse/MCR-4103
- submit and unlock events are displayed in the change history
- Log in as a CMS user and unlock a submission
- Ensure that the unlock event gets logged in the change submission (without needing to the state user to first resubmit)
=> Add unlock action to change history for drafts

services/app-web/src/pages/StateSubmission/RateDetails/V2/rateDetailsHelpers.ts
This PR is a small enhancement that makes the No selection behavior the same as the yes flow when a user selects an option for the yes/no Was this rate included in another submission' without filling in any additional info. The selection gets cleared for either selection
The implementation is in rateDetailsHelpers. I found that specific fields had to be omitted for checking if they were filled out or not because a few of the fields are auto populated on No selection. I initially was trying to add checks inside of RateDetails as a part of the save as draft handler flow. If there are other ideas  please let me know
https://jiraent.cms.gov/browse/MCR-4108
- As state user on RateDetails page select No to the 'Was this rate included in another submission'
- Without filling out any fields, …
=> Clear yes/no selection for ratePreviouslySubmitted field

services/app-web/src/pages/StateSubmission/RateDetails/V2/rateDetailsHelpers.test.ts, services/app-web/src/pages/StateSubmission/RateDetails/V2/rateDetailsHelpers.ts
[MCR-4108](https://jiraent.cms.gov/browse/MCR-4108)
The work in MCR-4108 was broken when I added `certifyingActuaryContacts` in the check for filled-in fields in this [PR](https://github.com/Enterprise-CMCS/managed-care-review/pull/2430). 
Adding `certifyingActuaryContacts` broke because the frontend automatically adds a certifying actuary with empty strings into the array. You can find that code in `formatActuaryContactsForForm`. This is done so that Yup has something to validate against and UI errors can be generated (see `generateErrorSummaryErrors`).
The fix was to loop through every actuary contact and check for at least one with some fields filled in. I pulled out that logic and refactored it to keep the types in each property of `RateFormData`. Also, I only checked for filled-in …
=> Fix for MCR-4108

services/app-web/src/pages/LinkYourRates/LinkRateSelect.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/SingleRateFormFields.tsx
[MCR-4116](https://jiraent.cms.gov/browse/MCR-4116)
[MCR-4115](https://jiraent.cms.gov/browse/MCR-4115)
- Fix `Add another rate certification` and `Add a certifying actuary` focus.
- Console errors from putting a `ref` in uswds `Button` component.
- <img src="https://github.com/Enterprise-CMCS/managed-care-review/assets/98117700/0664bf04-d1f9-497f-a599-9033a804fc88" />
- The fix was to revert back to regular `button` element.
- Fix menu list options sub-categories font size.
- Fix selected option display styling
- When a rate is selected, the select box should only display the rate name cutting off overflowing portions.
- When a rate is displayed in the select dropdown menu, then show the rate name and sub-categories.
- [Figma](https://www.figma.com/file/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care …
=> MCR-40116 & MCR-4115: Fix linked rate select styling and accessbility

services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsDashboard.tsx, services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsTable.test.tsx, services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsTable.tsx
Display human readable rate id on rate review dashboard - Product asked we add this just to see what these values look like in production. 
https://jiraent.cms.gov/browse/MCR-4161
- renders rate number for Admin users
- does not render rate number by default
=> Add rate number for admin users

services/app-api/src/postgres/contractAndRates/prismaContractRateAdaptors.ts, services/app-api/src/resolvers/contract/updateDraftContractRates.test.ts, services/app-api/src/resolvers/rate/submitRate.test.ts, services/app-api/src/resolvers/rate/submitRate.ts, services/app-api/src/testHelpers/gqlRateHelpers.ts, services/app-api/src/testHelpers/rateDataMocks.ts, services/app-graphql/src/schema.graphql, services/app-web/src/pages/StateSubmission/RateDetails/V2/rateDetailsHelpers.ts, services/app-web/src/testHelpers/apolloMocks/contractGQLMock.ts
[MCR-4196](https://jiraent.cms.gov/browse/MCR-4196)
Fix system error when updating rates with `packagesWithSharedRateCerts` with `linked-rates` flag on.
This bug was caused by the difference in `packagesWithSharedRateCerts` between the GraphQL `RateFormDataInput` and `RateFormData` type.
There were three solutions
1. Map through `packagesWithSharedRateCerts` and return the object that matches the input type
2. Pass in an empty array, because we no longer want to  carry forward this field in new rate revisions
3. Remove `packagesWithSharedRateCerts` from the update rate mutations all together since it is depreciated and we no longer want to carry forward this data.
I choose option 3, removing it from the input of the mutation altogether by removing `packagesWithSharedRateCerts` from …
=> MCR-4196: updating rates with packages with shared rates causes system error

services/app-web/src/components/Footer/Footer.tsx, services/app-web/src/components/Header/Header.tsx, services/app-web/src/pages/GraphQLExplorer/GraphQLExplorer.module.scss
Hides the header and footer from the graphql explorer page to make it easier to use
https://jiraent.cms.gov/browse/MCR-3753
=> MCR-3753: hide header and footer from graphql explorer page

services/app-web/src/common-code/ContractTypeProvisions.ts, services/app-web/src/components/DataDetail/DataDetail.tsx, services/app-web/src/components/HealthPlanPackageTable/HealthPlanPackageTable.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ContactsSummarySectionV2.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ContractDetailsSummarySectionV2.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ContractDetailsSummarySectionV2.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/RateDetailsSummarySectionV2.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/RateDetailsSummarySectionV2.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ReviewSubmitV2.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ReviewSubmitV2.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/SubmissionTypeSummarySectionV2.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/SubmissionTypeSummarySectionV2.tsx, services/app-web/src/pages/SubmissionRevisionSummary/SubmissionRevisionSummaryV2.test.tsx, services/app-web/src/pages/SubmissionSummary/V2/SubmissionSummaryV2.test.tsx, services/app-web/src/pages/SubmissionSummary/V2/SubmissionSummaryV2.tsx, services/app-web/src/testHelpers/apolloMocks/contractPackageDataMock.ts, services/app-web/src/testHelpers/apolloMocks/index.ts, services/app-web/src/testHelpers/apolloMocks/rateDataMock.ts, services/app-web/src/testHelpers/apolloMocks/userGQLMock.ts
[MCR-4195](https://jiraent.cms.gov/browse/MCR-4195)
This work refactored where we are determining when to show the missing data error notification. Before this was done at each summary section with slightly different conditions. I refactored to have this be determined at the summary page component, then passed into the summary sections. 
This made more sense since we determine the notifications based on the summary page and the user, not at each summary section component.
- `ReviewSubmitV2` is only for state users and should always notify them of any missing data, not just certain sections.
- `SubmissionRevisionSummaryV2` is for viewing historical data where notifications for missing data is not important for any user because it is no longer in review. 
- `SubmissionSummaryV2` only shows …
=> MCR-4195: CMS user shouldn't see missing field error for populations covered

services/uploads/serverless.yml
The local offline service for `uploads` is failing to start. It was missing a few entries to mock out ssm values for local dev environments.
https://jiraent.cms.gov/browse/MCR-4220
=> Fix local uploads service

services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/RateDetailsSummarySectionV2.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/RateDetailsSummarySectionV2.tsx, services/app-web/src/testHelpers/apolloMocks/contractPackageDataMock.ts
We should still display that old rate programs field and its data
- on previous submission revision page
- on the CMS visible standalone rate summary page
- on the CMS visible submissions summary page 
The only time when this historical data field is hidden is for state users looking at review and submit and starting to edit that unlocked rate.
https://jiraent.cms.gov/browse/MCR-4206
- does not display deprecated fields on unlocked submissions for state users
- displays deprecated fields on previous submissions viewed by state users
-  displays deprecated fields on unlocked submissions for CMS users
- to evaluate this look at submission that uses the old rate programs field. probably have to use historic data  to achieve this
=> Historic rate programs still appear on previous submission and rate summary pages

services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsTable.tsx, services/cypress/integration/cmsWorkflow/rateReview.spec.ts, services/cypress/integration/cmsWorkflow/unlockResubmit.spec.ts, services/cypress/support/apiCommands.ts, services/cypress/support/index.ts, services/cypress/support/stateSubmissionFormCommands.ts, services/cypress/utils/apollo-test-utils.ts
[MCR-4024](https://jiraent.cms.gov/browse/MCR-4024)
- Added a new cypress test `'can unlock and resubmit a linked rate and change history updates'` in `unlockResubmit.spec`
- Updated `createAndSubmitContractWithRates` to use the new Contract and Rate API.
- The function did not work using the HPP API to create rates, not sure how `rateReview.spec` even passed in other branches. 
- Instead of trying to fix it with the old API, I updated it to use the new rates API.
- I'm also returning `Contract` instead of `HealthPlanPackage`. 
- This is because rate names differ between them and instead of updating HPP to match rate name formats today, I just switched to using `Contract` instead. 
- This made `rateReview.spec` fail because it was looking for HPP rate names, but the rates were made using …
=> MCR-4024: Fix cypress tests for linked rates

services/app-api/src/postgres/contractAndRates/prismaSharedContractRateHelpers.ts, services/app-api/src/resolvers/contract/submitContract.test.ts, services/app-api/src/resolvers/rate/fetchRate.test.ts, services/app-api/src/resolvers/rate/submitRate.test.ts, services/app-api/src/testHelpers/documentHelpers.ts, services/app-api/src/testHelpers/gqlRateHelpers.ts, services/app-api/src/testHelpers/index.ts, services/app-graphql/src/schema.graphql, services/app-web/package.json, services/app-web/src/common-code/dateHelpers/dayjs.ts, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/UploadedDocumentsTable/UploadedDocumentsTable.test.tsx, services/app-web/src/components/SubmissionSummarySection/UploadedDocumentsTable/UploadedDocumentsTable.tsx, services/app-web/src/gqlHelpers/contractsAndRates.ts, services/app-web/src/pages/MccrsId/MccrsId.tsx, services/app-web/src/pages/RateSummary/RateSummary.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ContractDetailsSummarySectionV2.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/RateDetailsSummarySectionV2.tsx, services/app-web/src/pages/SubmissionRevisionSummary/SubmissionRevisionSummary.tsx, services/app-web/src/pages/SubmissionRevisionSummary/SubmissionRevisionSummaryV2.tsx, services/app-web/src/pages/SubmissionSideNav/SubmissionSideNav.tsx, services/app-web/src/testHelpers/apolloMocks/rateDataMock.ts, yarn.lock
The bugs here are two specific cases 
1. when submit unlock resubmit happen on same day our date added was off
2. or, when viewing previous subission pages our date added was off 
Resolved this by:
- Fix NEW tag display for same date submissions by using DateTime graphql schema type
- Fix NEW tag display for previous submissions by making sure the `lastSubmittedDate` is based on the submission preceeding the current version being displayed 
- Upgrade react-router-dom minor versions to clean up types for router params
- Use timezone aware `isSameOrAfter` date comparison function from dayjs to determine NEW tag
https://jiraent.cms.gov/browse/MCR-4199
- renders the NEW tag when a document is submitted after the last submission, even if same day
- Create and resubmit a package and check new …
=> MCR-4199 Adjust NEW tag logic for same date submission and previous revisions

.github/workflows/sechub-jira-sync.yml
We have been given credentials to move this over to Jira Enterprise finally. The credentials have been updated and this is a minor fix to the action.
https://jiraent.cms.gov/browse/MCR-3877
=> Update security hub jira sync tool

services/app-api/src/postgres/contractAndRates/submitContract.ts, services/app-api/src/resolvers/contract/submitContract.test.ts
Discussion for this is in the [Incident Log](https://docs.google.com/document/d/1V3OUC9ryF24YY-kQccUhMfKH4JRWXVAp7vhPH2ckW5M/edit)
Production issue, caused an error when unlocking and resubmitting an old contract while a new contract was linked to one of its rates. That error shouldn't have been an error but instead should have been a noop. Also fixed the transaction handling for submitContract. 
https://jiraent.cms.gov/browse/MCR-4245
=> Fix submitting an old contract when there is a new contract linked to one of its rates

services/app-api/src/resolvers/contract/submitContract.test.ts, services/app-api/src/resolvers/contract/updateDraftContractRates.test.ts, services/app-api/src/resolvers/contract/updateDraftContractRates.ts, services/app-api/src/resolvers/rate/fetchRate.test.ts, services/app-api/src/testHelpers/gqlRateHelpers.ts, services/app-graphql/src/schema.graphql, services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.test.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.tsx, services/app-web/src/testHelpers/apolloMocks/contractGQLMock.ts, services/app-web/src/testHelpers/apolloMocks/contractPackageDataMock.ts, services/cypress/integration/cmsWorkflow/rateReview.spec.ts, services/cypress/integration/stateWorkflow/questionResponse/questionResponse.spec.ts, services/cypress/support/apiCommands.ts, services/cypress/support/index.ts, services/cypress/utils/apollo-test-utils.ts
- Adds a check in `updateDraftContractRates` for optimistic concurrency control. The mutation takes an extra input field `lastSeenUpdatedAt` from `contract.draftRevision.updatedAt` to compare with the  same draft revisions `updatedAt` in the DB to prevent newer changes being overwritten by stale data.
- I also went ahead and updated all the api commands in Cypress to only use the new API's and remove all references to HPP.
`updateDraftContractRates.test.ts`
- `'errors on concurrent updates'`
- With the `link-rates` feature flag on.
- Open two windows with the same draft contract and rates submission
- On the first the window:
- Continue with the form until the Rate details page
- On the second window:
- Continue with the form until the Rate details page
- Make a change to the rate.
- …
=> Fix updateDraftContractRates resolver to check for concurrent update

services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/RateDetailsSummarySectionV2.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/RateDetailsSummarySectionV2.tsx
To replicate:
1. Create a new submission
2. Select "contract action and rate certification" and fill out form
3. On the Rate details page link a rate certification that was submitted prior to when the rate name enhancement feature went live.
4. Click continue and fill out the rest of the submission
5. When you arrive at the Review and submit page...
Current behavior:
The Rate details will flag an error validation on the field  "Rates this rate certification covers" and prevent a submission, despite the rate being locked. 
Expected behavior:
We will not flag an error validation on a locked linked rate.
Displays the historic 'Programs this rate covers' if the linked rate is locked and historic
**BEFORE**
**AFTER**
- Displays the old field for historic rates
- Renders the new field on …
=> MRC-4244: Bug fix for Showing an error on a submitted rate

.github/workflows/deploy.yml, .github/workflows/promote.yml
In the Vite PR there was a missing config value for `vite_app_auth_mode`. This fixes that and also moves the `deploy.yml` back to `main`.
https://jiraent.cms.gov/browse/MCR-1797
=> Fix promote for vite_app_auth_mode

.github/workflows/promote.yml
With the changes from the Vite branch, `promote` is missing some codegen to run unit tests. This adds that codegen in.
https://jiraent.cms.gov/browse/MCR-1797
=> Fix promote unit test code gen 

services/app-api/src/domain-models/contractAndRates/contractTypes.ts, services/app-api/src/domain-models/contractAndRates/statusType.ts, services/app-api/src/postgres/contractAndRates/findRateWithHistory.test.ts, services/app-api/src/postgres/contractAndRates/unlockContract.ts, services/app-api/src/resolvers/contract/unlockContract.ts, services/app-graphql/src/schema.graphql
This PR makes the minor changes that were brought up in RSP
- Restricts the status of an `UnlockedContractType` to be `UNLOCKED`
- Makes `draftRates` mandatory on the domain model 
- Uses the extend syntax on the domain model type
=> Changes for unlockedContract type

services/app-web/src/components/TealiumLogging/Button.tsx, services/app-web/src/components/TealiumLogging/Link.tsx, services/app-web/src/hooks/useTealium.ts, services/app-web/src/pages/RateSummary/RateSummary.tsx, services/app-web/src/pages/StateSubmission/Contacts/Contacts.tsx, services/app-web/src/pages/SubmissionSideNav/SubmissionSideNav.tsx, services/app-web/src/pages/SubmissionSummary/V2/SubmissionSummaryV2.tsx, services/app-web/src/tealium/constants.ts, services/app-web/src/tealium/index.ts, services/app-web/src/tealium/tealium.ts, services/app-web/src/tealium/tealiumHelpers.ts
Narrow in work from #2543 for navigation links specifically
- Address missing fields from[ Blast analytics tagging strategy doc](https://confluence.cms.gov/pages/viewpage.action?spaceKey=BLSTANALYT&title=mc-review.onemac.cms.gov+-+Tagging+Strategy)
- Use dashboard or homepage rather than "root" as the page name for the `/` url and dashboards
- Add more granular `event_name` types by allowing that value to be set in nav links. This allows distinct loggined for navigation clicked versus back button versus internal link clicked
https://jiraent.cms.gov/browse/MCR-4219
n/a
n/a we dont unit test analytiucs
This work with be QA/ed by Blast in product -  code reviewers can just skim change high level
=> Add navigation event tagging

services/app-web/src/pages/StateSubmission/RateDetails/LinkedRateSummary.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/RateDetailsSummarySection.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/RateDetailsSummarySection.tsx
This PR updates the RateDetailsSummarySection to ensure no missing data error validations display for a linked rate and it updates the linkedRatesSummary (that appears on the RateDetails page) to not display missing data error either
https://jiraent.cms.gov/browse/MCR-4258
**BEFORE**
AFTER
- RateDetailsSummarySection - checks that missing data text doesn't appear for a draft linked rate
- create and submit a contract with one rate (Rate A) submission
- go in through db functions and remove a required field from Rate A(make start date added empty, for example)
- create a new contract and rate submission that has Rate A as a linked rate
- go to review and submit page
- no validation errors should appear
=> MCR-4258: Hide missing data text for linked rates

services/app-web/src/hooks/useTealium.ts, services/app-web/src/pages/Settings/EmailSettingsTables/EmailAnalystsTable.tsx
Settings page started to crash on load. Looks like  mutable array was causing crash - throwing a type a error `0 is read only" for trying to alter state analysts array.
Other notes
- will look into an eslint role for this next
- will also write basic E2E test for settings page load
- I changed the error state for tealium because on full page crash that error was getting thrown multiple times and it floods the console. Not helpful. 
https://jiraent.cms.gov/browse/MCR-4317
No new tests yet, will be next PR
Log is as admin user and navigate to /settings. Try to change an existing users division assignment.  Before the crash happened as soon as you hit the setting page.
=> Unblock settings page usage

services/cypress/support/stateSubmissionFormCommands.ts
We have a [recurrent issue on cypress runs](https://cloud.cypress.io/projects/tt5hbz/analytics/top-failures/3147a9e3-7bad-840a-b997-e16de99e4069-d020e680-9e8f-88c8-fdc7-eef74f64d75a) yesterday and today. Trying  a different way of selecting checkbox items in Cypress to see if it helps.
n/a 
Screenshot of the app at the point of  cypress failures is below.  The faliures happen from within an existing state submission form helper which had been working fine... up until this week. 
The errors are for the two checkbox fields (managed care entities and federal authorities). Re-runs show these checkbox fields register as clicked and can be seen visually as selected in cypress re-runs intiially.  However, a few commands later, the selections disappear and the checkbox uncheck itself. This causes …
=> fix: cypress checkbox behavior - swap .safeClick to .check to handle the USWDS checkbox

services/app-api/src/handlers/apollo_gql.ts, services/app-web/package.json, services/app-web/src/index.tsx, services/app-web/src/react-app-env.d.ts, services/app-web/vite.config.ts, yarn.lock
Since merging the CRA -> Vite refactor, LaunchDarkly has been throwing cors errors in local dev. This adds some LD proxies that will get CORS checks to succeed. 
https://jiraent.cms.gov/browse/MCR-4298
=> Add vite proxy configs to deal with LD CORS

services/app-web/src/components/SubmissionSummarySection/SubmissionSummarySection.module.scss, services/app-web/src/pages/StateSubmission/ReviewSubmit/RateDetailsSummarySection.tsx
This PR addresses feedback on [ticket](https://jiraent.cms.gov/browse/MCR-4130):
- Replace rate button is 32px from the right of the border box
- When replace rate button isn't on the page, prevent unnecessary wrapping of the rate name
https://jiraent.cms.gov/browse/MCR-4130
View submissions as an admin issue with a non linked rate. should see the replace rate button is properly positioned
On a submission summary that doesn't have the replace rate button (viewed by a non admin user or a linked rate), ensure there's no unneeded wrapping happening on the rate name
=> MCR-4130: Design fixes for Replace Rate btn

services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.test.tsx, services/app-web/src/pages/StateSubmission/StateSubmissionForm.test.tsx, services/uploads/serverless.yml
A user tried uploading a 30M file, which caused an error. It looks like we set the StreamMaxLength file size in the lambda config, but not on the AV server. This fixes that.
https://jiraent.cms.gov/browse/MCR-4331
=> Increase StreamMaxLength filesize setting on ClamAV server

services/app-web/src/pages/StateSubmission/ReviewSubmit/RateDetailsSummarySection.tsx
This is a design fix PR that prevents rate name from wrapping when viewing a previous revision 
BEFORE FIX
AFTER FIX
- Sign in as an admin
- View a contract and rate submission that has been resubmitted
- Click the 'view previous submission' link in the change history section
- The rate details section shouldn't have unnecessary wrapping on the rate name
=> [MCR-4130] Prevent wrapping of rate name on previous submissions

.github/workflows/promote.yml, README.md
There was a small error in the clamav build step in the `promote` GHA task (`pnpm` not found). This adds the environment setup action which includes the `pnpm` install.
=> Fix clamav step in promote.yml

.github/workflows/promote.yml
When landing the `pnpm` work we got a failure in the cypress promote action due to an outdated container. This just bumps that container to match what we have in review apps.
=> Bump container for cypress in promote

.github/actions/setup_env/action.yml, .github/workflows/deploy.yml
The `promote` task started throwing errors on the last Cypress step after we merged in the pnpm change. It turns out in `promote` we had `install: false` set, which caused the action to not find the binary at that point (I'm not sure why it completed on my initial merge/promote, but then started failing on subsequent promotes). 
This updates the cache location to include the relative `~` dir expansion. The reason for this is that in VMs the path for the cache is in `/github/home/.cache/Cypress` whereas in containers it is in `/root/.cache/Cypress`. I've also set `install: false` in review app deploys to save a little time now that this works properly.
=> Fix cypress bin cache location

.github/actions/setup_env/action.yml, .github/workflows/deploy.yml, .github/workflows/promote.yml, pnpm-lock.yaml, services/cypress/package.json
I guess the last PR to fix cypress in promote broke cypress in review runs. This bumps cypress to use the latest, which puts it in the cache, and removes the `install: false`
=> Another cypress cache fix

services/app-api/src/emailer/emails/newPackageCMSEmail.test.ts, services/app-api/src/emailer/emails/resubmitPackageCMSEmail.test.ts, services/app-api/src/emailer/emails/sendQuestionCMSEmail.test.ts, services/app-api/src/emailer/emails/sendQuestionCMSEmail.ts, services/app-api/src/emailer/emails/sendQuestionResponseCMSEmail.test.ts, services/app-api/src/emailer/emails/sendQuestionResponseCMSEmail.ts, services/app-api/src/emailer/emails/unlockContractCMSEmail.test.ts, services/app-api/src/emailer/emails/unlockPackageCMSEmail.test.ts, services/app-api/src/emailer/templateHelpers.test.ts, services/app-api/src/emailer/templateHelpers.ts, services/app-api/src/resolvers/healthPlanPackage/unlockHealthPlanPackage.test.ts, services/app-api/src/resolvers/questionResponse/createQuestionResponse.test.ts, services/app-web/src/pages/Settings/EmailSettingsTables/EmailSettingsTables.tsx
If a contract is not risk based than OACT shouldn't be notified about it
https://jiraent.cms.gov/browse/MCR-4279
Updated existing test to use a risked based contract if expecting oact to receive emails
Submit a risked based contract, in review app. OACT should not be notified
=> MCR-4279: prevent oact from getting emails about non risked based contracts

scripts/add_cypress_test_users.ts, services/app-web/src/contexts/AuthContext.tsx, services/app-web/src/localAuth/LocalLogin.tsx, services/app-web/src/pages/App/AppRoutes.tsx, services/app-web/src/pages/Settings/CMSUsersTable/CMSUsersTable.tsx, services/cypress/integration/adminWorkflow/settings.spec.ts, services/cypress/utils/apollo-test-utils.ts
Follow on to #2578. Adds new Admin workflow Cypress tests. This helps protect against the various crash/freeze behaviors we saw on settings page this sprint (one was with users table, one was with state analysts table). 
🔍 I also made a change to the use of `navigate` in AppRoutes and AuthContext. It was failing silently - we didn't notice. A test that could have caught it breaking has been skipped since Contract and Rates API was introduced.  I found out when I tried to write an admin test that would attempt to go to /settings, login, then redirect. Using `window.location.href` directly seems to resolve the issue. 
https://jiraent.cms.gov/browse/MCR-4317
- update user division assignments
- filter down state analysts by state code
If Cypress tests pass,  we can merge. The bugfix already …
=> MCR-4317 add admin cypress tests for Settings  - on fresh branch

pnpm-lock.yaml
The previous dependabot PR (#2622) that we merged hit an error in promote where the lockfile was found to be broken. This PR is just from running `pnpm install` locally in a branch to fix that lockfile error. I've opened a bug ticket to figure out why this happened in the first place (i.e. why didn't dependabot update the lockfile properly and why did we pass CI on that branch).
https://jiraent.cms.gov/browse/MCR-4346
=> Fix pnpm lockfile from dependabot merge

.github/workflows/deploy.yml, scripts/get-changed-services/index.ts
This just cleans up the last PR merge that needed to use a branch name for CI scripts. Moves it back to main. Also there were a couple comments that still mentioned lerna.
=> Move git reference for CI back to main

services/app-graphql/src/queries/indexRates.graphql, services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsDashboard.test.tsx, services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsDashboard.tsx
[MCR-4150](https://jiraent.cms.gov/browse/MCR-4150)
- Rates dashboard will skip rates with `withdrawInfo`.
- `RateReviewsDashboard.test.ts`
- `'renders dashboard without withdrawn rates'`
The UI to withdraw a rate is not implemented yet, but this is a small task and it can be verified with tests. We can merge this in, but we should wait for acceptance testing until MCR-4152 and the issue found with the withdraw API have been merged. See this Slack [thread](https://cmsgov.slack.com/archives/C014CRU197U/p1723131423175859) for more information.
For reviewing this PR, I think making sure the code and test are good. Please comment if you think that would not be sufficient to approve this.
=> MCR-4150: Do not display withdrawn rates on rates dashboard.

services/infra-api/serverless.yml, services/postgres/serverless.yml
This adds some additional bucket policies to a couple s3 buckets that we have for configuration. It should force SSL to make the security hub alerts go away.
This isn't something we can see in review apps, as these buckets and policies are only deployed in dev/val/prod, so we'll have to verify once it merges.
https://jiraent.cms.gov/browse/MCR-4239
https://jiraent.cms.gov/browse/MCR-4238
=> Enhance some S3 bucket policies for Security Hub

services/app-web/src/pages/GraphQLExplorer/GraphQLExplorer.tsx
[MCR-4302](https://jiraent.cms.gov/browse/MCR-4302)
In our vite.config.ts we are using `'vite-plugin-graphql-loader'` to load our GraphQL schema. The output is a `DocumentNode` which I think differred from when we used webpack which outputted a string. The `ApolloExplorer` component only takes an `IntrospectionQuery` or `SDLstring` for the schema. So the fix here is to convert the document node into the `SDLstring` using `print()` from `graphql` library.
=> MCR-4302: Fix GraphQL explorer tool

services/app-web/src/components/Banner/RateWithdrawnBanner/RateWithdrawnBanner.tsx, services/app-web/src/components/Banner/index.ts, services/app-web/src/pages/RateSummary/RateSummary.test.tsx, services/app-web/src/pages/RateSummary/RateSummary.tsx
[MCR-4222](https://jiraent.cms.gov/browse/MCR-4222)
- Add new `RateWithdrawnBanner` component
- Add the withdrawn banner to the Rate summary page.
`RateSummary.test.ts`
-`'displays withdrawn banner on a withdrawn rate'`
QA here is to make sure the test and code look ok, here is a screen shot from local of the UI. Without some of the other redundant rate tickets we can get a rate into that state in this review app
=> MCR-4222: CMS and States see withdrawn label on Rate Summary Page

services/uploads/src/deps/clamAV/clamAV.ts
I was looking around our cloudwatch logs for MCR-4354 and noticed a lot of `err undefined` in the logs. Looking at the code this seems normal, we were logging if there was something in `avResult.error` -- which usually is `undefined`. Just added checks here so that we don't see a bunch of `err undefined` in the logs thinking we're missing something.
https://jiraent.cms.gov/browse/MCR-4354
=> avscan service: check if there is an error value before logging

services/postgres/serverless.yml
MacRae just saw a warning for an unavailable runtime in the `postgres` service's CI deploy. This puts it to the available version.
=> Fix: runtime 3.12 not available

services/app-api/serverless.yml, services/uploads/serverless.yml
The lambda layer that AWS provides for OTEL tooling has had a minor version bump. This brings us in line with the 0.40 OTEL collector.
=> Bump AWS Distro for OTEL layer to latest

services/app-web/src/components/FileUpload/FileUpload.tsx, services/app-web/src/s3/s3Amplify.ts
A user attempted to upload a document with an extension of `.PDF`. Turns out that s3 file extension policies are case-sensitive. This downcases the extension on every file upload before sending it to s3.
https://jiraent.cms.gov/browse/MCR-4375
=> Downcase file extensions uploaded with ALLCAPS

services/app-api/src/emailer/emails/newPackageCMSEmail.ts, services/app-api/src/emailer/emails/newPackageStateEmail.ts, services/app-api/src/emailer/emails/resubmitPackageCMSEmail.ts, services/app-api/src/emailer/emails/resubmitPackageStateEmail.ts, services/app-api/src/emailer/emails/sendQuestionCMSEmail.ts, services/app-api/src/emailer/emails/sendQuestionResponseCMSEmail.ts, services/app-api/src/emailer/emails/sendQuestionResponseStateEmail.ts, services/app-api/src/emailer/emails/sendQuestionStateEmail.ts, services/app-api/src/emailer/emails/unlockContractCMSEmail.ts, services/app-api/src/emailer/emails/unlockContractStateEmail.ts, services/app-api/src/emailer/emails/unlockPackageCMSEmail.ts, services/app-api/src/emailer/emails/unlockPackageStateEmail.ts
[MCR-4366](https://jiraent.cms.gov/browse/MCR-4366)
Removed the entire `replyToAddress` it was only the helpdesk email in there..
=> MCR-4366: Remove help desk from replyToAddresses

.github/workflows/send-dso-metrics.yml
We've been asked to setup a metric export to the mac-fc backend that is collecting deploy metrics. This uses the [mac-fc-scan](https://github.com/Enterprise-CMCS/mac-fc-scan-github) action that Ben wrote and puts in just our promote metrics.
Since we can't run this to debug until it merges there likely will be follow-on PRs.
=> Add mac-fc DSO metrics collection

.github/workflows/send-dso-metrics.yml
When #2674 merged it looks like the syntax for the ARN is not expanding properly. This adds quotes to expand the account ID.
=> Fix syntax in DSO metrics action

services/app-api/src/emailer/emails/newPackageCMSEmail.ts, services/app-api/src/emailer/emails/newPackageStateEmail.ts, services/app-api/src/emailer/emails/resubmitPackageCMSEmail.ts, services/app-api/src/emailer/emails/resubmitPackageStateEmail.ts, services/app-api/src/emailer/emails/sendQuestionCMSEmail.ts, services/app-api/src/emailer/emails/sendQuestionResponseCMSEmail.ts, services/app-api/src/emailer/emails/sendQuestionResponseStateEmail.ts, services/app-api/src/emailer/emails/sendQuestionStateEmail.ts, services/app-api/src/emailer/emails/unlockContractCMSEmail.ts, services/app-api/src/emailer/emails/unlockContractStateEmail.ts, services/app-api/src/emailer/emails/unlockPackageCMSEmail.ts, services/app-api/src/emailer/emails/unlockPackageStateEmail.ts
[MCR-4366](https://jiraent.cms.gov/browse/MCR-4366)
Lets try setting `replyToAddresses` in the emailer as empty array. I think it would have the same result as not including the property at all. 
I believe [AWS SES ](https://docs.aws.amazon.com/ses/latest/dg/send-email-concepts-email-format.html)defaults the `replyTo` of emails as the sender when we don't specify the `replyToAddresses` in the emailer.
=> Set email replyToAddresses as empty array.

.husky/pre-commit
This updates running our linters from `npx` to using `pnpm` directly. I'll also say that I'm not sure that this will change much, as I personally wasn't seeing any of the issues that Hana or Pearl were seeing with linters not running locally in pre-commit. But running from pnpm does work and is recommended since we're using it now.
I originally intended to include a CI step for linting, but there are more failures than I had thought. Here is a follow on ticket and explanation of what I found: https://jiraent.cms.gov/browse/MCR-4391
https://jiraent.cms.gov/browse/MCR-4390
=> Run lint-staged from pnpm

services/app-web/src/components/FormContainer/FormContainer.module.scss, services/app-web/src/components/FormContainer/FormNotificationContainer.tsx, services/app-web/src/components/FormContainer/index.ts, services/app-web/src/components/index.ts, services/app-web/src/pages/StateSubmission/Contacts/Contacts.tsx, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.tsx, services/app-web/src/pages/StateSubmission/Documents/Documents.tsx, services/app-web/src/pages/StateSubmission/PageBannerAlerts.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ReviewSubmitV2.tsx, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx
[MCR-4410](https://jiraent.cms.gov/browse/MCR-4410)
We moved banners outside the grid containers that set a max width. The banners `show more` text needs to have a max width in order for it to know when to clamp long strings.
This fix places both the step indicator and the page banners inside it's own grid container,`FormNotificationContainer`.
A good refactor is to move the step indicator and page banners to the `StateSubmissionForm` component, but for now we need to get this merged in so that users can continue their work.
[MCR-3757](https://jiraent.cms.gov/browse/MCR-3757)
I did not see this happen, but included it anyways to review that it is no longer an issue. This was created last year in November so changes in the project since then may have fixed this.
=> MCR-4410 & MCR-3757 fix show more text on banners

.github/workflows/send-dso-metrics.yml
This adds the environment specifier for the DSO metrics action. The last merge is still having issues expanding the AWS ID, which is marked as a prod secret in our config it looks like.
=> Add environment to DSO metrics action

.github/workflows/send-dso-metrics.yml, services/github-oidc/serverless.yml
This adds permissions for the role to be assumed for DSO metrics. I tested this with a manual change and it worked fine.
=> Add sts:AssumeRole to DSO metrics role

pnpm-lock.yaml
The last dependabot merge to `main` had an issue with the lockfile. This fixes the conflict by just running `pnpm install` on the branch and letting pnpm work out the dependency conflict.
=> Fix pnpm-lockfile

services/app-api/serverless.yml
This increases the memory for the lambda zip function in prod, in order to speed up the processing of files. This fixes an issue where a user is attempting to view a submission that has a large amount of files and the zip function is hitting the max runtime of 30s in AWS Lambda.
=> Bump lambda environment's memory in prod

services/app-api/serverless.yml
This fixes the syntax to expand the `stage` from PR #2723 to use the more recent `sls:stage` syntax from Serverless.
https://jiraent.cms.gov/browse/MCR-4434
=> Syntax fix on zip lambda stage

services/app-web/src/pages/Settings/EditStateAssign/EditStateAssign.tsx, services/app-web/src/pages/Settings/Settings.test.tsx, services/app-web/src/pages/Settings/Settings.tsx, services/app-web/src/pages/Settings/SettingsCells/SettingsCells.tsx, services/app-web/src/pages/Settings/SettingsTables/StateAssignmentTable.tsx, services/app-web/src/pages/Settings/index.ts
Forgotten AC from MCR_4264 - "edit" links are added to the analyst assignment table. Also correct column heading and the casing bug from the url work.
https://jiraent.cms.gov/browse/MCR-4264
Added basic test for Edit state assignments column presence based on feature flag
Make sure AC is working and is featured flagged
=> MCR-4264 Add actual edit links to dashbaord

services/app-web/src/components/Header/Header.module.scss, services/app-web/src/components/Header/Header.test.tsx, services/app-web/src/components/Header/UserLoginInfo/UserLoginInfo.tsx, services/cypress/integration/stateWorkflow/login/login.spec.ts, services/cypress/support/loginCommands.ts
[MCR-4262](https://jiraent.cms.gov/browse/MCR-4262)
ACs:
- If I am logged in as a CMS user or an Admin then I see an "MC-Review settings" link in the header
- If I click on the link then I am directed to /mc-review-settings 
- Place user email and sign out button under a `Your account` dropdown.
Other things
- Placed `MC-Review settings` link and the `Your account` dropdown into a `nav` element
- Fixed the `nav` section for small screens
- Update `login.spec.ts` to also check for accessibility violations. (It actually found a mistake I made when I ran the test!)
`login.spec.ts`
- `'can log in and log out as expected without accessibility violations'`
=> MCR-4262: cms and admin see link to email settings in header

services/app-web/src/tealium/tealium.ts
Follow on to #2739 - I realized they instructed us **not** to deploy to prod yet, only to lower environments. Makes sense, I see that the new script isn't working in prod when I look in the console. Bringing back the old script for prod.
https://jiraent.cms.gov/browse/MCR-4458
This will be tested after deploy
=> fix: Pull Tealium change off prod, keep on lower env

services/app-web/src/pages/QuestionResponse/QuestionResponse.tsx, services/app-web/src/pages/Settings/Settings.test.tsx, services/app-web/src/pages/Settings/SettingsTables/DivisionAssignmentTable.tsx
[MCR-2501](https://jiraent.cms.gov/browse/MCR-2501)
- On Division assignments tab (formally CMS users):
- Change Family Name to Last name
- Change Given Name to First name
- All first and last name entries should be in sentence case
- On the State assignments tab (formally state analysts):
- Page header should be in sentence case State assignments
- Update page description to say “Below is a list of the DMCO staff assigned to states.”
- Add space after comma between emails
=> MCR-2501: Update copy on settings page

services/ui-auth/serverless.yml
The pen testing team was able to get a user signup through in val, although it had no privileges to do anything. This remediates their finding by disabling the Cognito IDP signup in val and prod environments. 
I was able to confirm that user signup was allowed in my review branch, which gave me a confirmation code to my signup email address:
I then added my branch's environment to the CloudFormation check to disable this, which worked as expected:
```
An error occurred (NotAuthorizedException) when calling the SignUp operation: SignUp is not permitted for this user pool
```
I'm not really sure we can test this in any other way prior to merging, but we can confirm in val once it promotes.
https://jiraent.cms.gov/browse/MCR-4430
=> Security Finding: Disallow user creation on val/prod

services/app-api/src/postgres/postgresErrors.ts, services/app-api/src/postgres/postgresStore.ts, services/app-api/src/postgres/state/updateStateAssignedUsers.ts, services/app-api/src/resolvers/configureResolvers.ts, services/app-api/src/resolvers/user/updateStateAssignment.test.ts, services/app-api/src/resolvers/user/updateStateAssignmentsByState.test.ts, services/app-api/src/resolvers/user/updateStateAssignmentsByState.ts, services/app-api/src/testHelpers/storeHelpers.ts, services/app-graphql/src/mutations/updateStateAssignmentsByState.graphql, services/app-graphql/src/schema.graphql
This PR adds a new API for updating state analysts by the whole state instead of updating the states assigned to a single user. The UI works this way so the API should work this way. 
Wrote new API tests
API isn't being hit yet so can't really validate it manually
=> update state analyst by state

services/app-web/src/components/ExpandableText/ExpandableText.module.scss
[MCR-3757](https://jiraent.cms.gov/browse/MCR-3757)
Used the wrong css display type.
Safari browser
Test the expandable text of the banners in both Safari and Chrome ( maybe Firefox too) to check for regressions.
=> MCR-3757: Fix expandable text for Safari

services/cypress/integration/adminWorkflow/settings.spec.ts, services/cypress/support/commands.ts, services/cypress/support/index.ts, services/cypress/support/loginCommands.ts, services/cypress/support/userSettingCommands.ts
[MCR-4325](https://jiraent.cms.gov/browse/MCR-4325)
- Add cypress test for state assignments.
- Updated user commands to be used with all the CMS user accounts.
- `settings.spect.ts`
- `'can update state assignment and see in on the state assignment table'`
=> MCR-4325: Add state assignments cypress test

services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.test.tsx
I believe the assertion looking for `Optional` text was happening before the page was re-rendered from the feature flag and showing the element with the `Optional` text. Changing the method to `findAllByText` allows time for re-rendering.
`ContractDetails.test.tsx`
- `'displays correct form guidance'`
=> Fix flaky unit test in ContractDetails.tsx

services/app-web/src/pages/Settings/Settings.test.tsx, services/app-web/src/pages/Settings/SettingsCells/SettingsCells.tsx, services/app-web/src/pages/Settings/SettingsTables/StateAssignmentTable.tsx
Add on PR for [MCR-4266](https://jiraent.cms.gov/browse/MCR-4266) after JAWS testing
[MCR-4266](https://jiraent.cms.gov/browse/MCR-4266) 
n/a
Added test case for links having clearer names - should be "Edit Minnesota" not just "Edit"
check screenreader announcement on table row
=> Announce state on edit links for screenreader

services/app-web/src/gqlHelpers/mutationWrappersForUserFriendlyErrors.ts, services/app-web/src/pages/QuestionResponse/QuestionResponse.test.tsx, services/app-web/src/pages/QuestionResponse/QuestionResponse.tsx, services/app-web/src/pages/QuestionResponse/UploadQuestions/UploadQuestions.test.tsx, services/app-web/src/pages/QuestionResponse/UploadQuestions/UploadQuestions.tsx, services/app-web/src/pages/QuestionResponse/UploadResponse/UploadResponse.test.tsx, services/app-web/src/pages/QuestionResponse/UploadResponse/UploadResponse.tsx, services/app-web/src/pages/StateSubmission/StateSubmissionForm.test.tsx, services/app-web/src/pages/StateSubmission/StateSubmissionForm.tsx, services/app-web/src/pages/SubmissionSideNav/SubmissionSideNav.test.tsx, services/app-web/src/pages/SubmissionSideNav/SubmissionSideNav.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.test.tsx, services/app-web/src/testHelpers/apolloMocks/apolloErrorCodeMocks.ts, services/app-web/src/testHelpers/apolloMocks/contractGQLMock.ts, services/app-web/src/testHelpers/apolloMocks/contractPackageDataMock.ts, services/app-web/src/testHelpers/apolloMocks/index.ts, services/cypress/support/commands.ts, services/cypress/support/dashboardCommands.ts, services/cypress/support/loginCommands.ts, services/cypress/support/navigateCommands.ts, services/cypress/support/questionResponseCommands.ts
This PR updates the submissionSideNav to use the contract API. It also updates the UploadQuestion, UploadResponse, SubmissionSummary and SubmissionForm to fully use the contract API
https://jiraent.cms.gov/browse/MCR-4144
Existing test updates to use contract API. The exception was the test covering the /documents route since going forward that page will no longer exist
- sign in as a CMS user and submit a question 
- sign in as a state user and submit a response 
- manually test sidenav
=> MCR-4144: use contractAPI on submissionSideNav

services/app-api/src/domain-models/QuestionsType.ts, services/app-api/src/domain-models/UserType.ts, services/app-api/src/domain-models/index.ts, services/app-api/src/postgres/questionResponse/index.ts, services/app-api/src/postgres/questionResponse/questionHelpers.ts, services/app-api/src/resolvers/configureResolvers.ts, services/app-api/src/resolvers/contract/contractResolver.ts, services/app-api/src/resolvers/contract/indexContracts.test.ts, services/app-api/src/resolvers/rate/fetchRate.test.ts, services/app-api/src/resolvers/rate/rateResolver.ts, services/app-api/src/resolvers/user/userResolver.ts, services/app-graphql/src/queries/fetchRateWithQuestions.graphql, services/app-graphql/src/schema.graphql
[MCR-4450](https://jiraent.cms.gov/browse/MCR-4450)
- `rateResolver` returns questions similar to `contractResolver`.
- Refactored the questionHelpers to work with both types of questions
- new `fetchRateWithQuestions` that includes the `questions` field.
NOTE: As a follow on ticket I wanted to rename all the existing `question` for contract questions to `contractQuestion` to better clarify which question type belongs to a rate and a contract. Separating it from this work will make it easier to review.
`fetchRate.test.ts`
- `'returns the questions on for a rate'`
=> MCR-4450: Update rate resolver to return questions field

services/app-web/src/pages/Settings/SettingsTables/StateAssignmentTable.tsx
[MCR-4522](https://jiraent.cms.gov/browse/MCR-4522)
The text is corrected to be `Below is a list of the DMCO staff assigned to states. To edit the assigned staff click on the edit link below.`.
=> MCR-4522: Correction to the copy fix for State assignment page.

.github/dependabot.yml
We started getting dependabot updates that were grouping minor updates of totally unrelated packages. This is not what we want, so I've set it in the config to deal with everything outside of our explicit groupings.
This also ungroups the `tsconfig-eslint` group, as it's impossible to ignore major versions when grouped and dependabot keeps opening PRs for it (we are a couple versions behind and have a ticket for the upgrade).
=> Ungroup "npm_and_yarn" dependabot 

services/app-web/src/contexts/AuthContext.tsx, services/app-web/src/contexts/S3Context.tsx, services/app-web/src/s3/s3Error.ts, services/cypress/integration/cmsWorkflow/rateReview.spec.ts, services/cypress/integration/stateWorkflow/virusScan/virusScan.spec.ts
This fixes up the test for av scanning to trigger the case I had seen when a good file and a bad file are added to the file upload dialogue causing the application to reload and clearing out even the good file. This cypress test successfully triggered that behavior, and I elaborated on the test by then removing the bad file and re-uploading a known good file.
Some cleanup around the s3 funcs fixed up this behavior.
https://jiraent.cms.gov/browse/MCR-4500
=> Fixes for file upload when virus is present

services/app-web/src/hooks/useScript.ts, services/app-web/src/tealium/tealium.ts
This is to address an error showing up in the console in higher environments.  Found a way to resolve that also rips out the odd boilerplate code we had in there for loading the async analytics tag (with adds `utag.js`).
https://jira.cms.gov/browse/BLSTANALYT-9419
https://jira.cms.gov/browse/BLSTANALYT-9293
We can only test on VAL or prod, no tealium in lower env. 
look over code, if tests pass, lets merge and check again
=> Refactor initializeTealium to append async script via createScript

docs/contract-rate-non-revision-design.md, services/app-graphql/src/schema.graphql
Added docs with all the fields I think we need to send to salesforce for the POC. 
Notably not sending any "revision" info, just straight contract and rate b/c Salesforce does auto-history-tracking
Also left out contacts for now, we use those for emailing which Salesforce doesn't need to do for us now so it reduces the complexity. 
https://jiraent.cms.gov/browse/MCR-4493
=> Add Salesforce model docs

services/app-web/src/pages/QuestionResponse/RateQuestionResponse.tsx, services/app-web/src/pages/SubmissionSideNav/RateSummarySideNav.test.tsx, services/app-web/src/pages/SubmissionSideNav/RateSummarySideNav.tsx, services/app-web/src/pages/SubmissionSideNav/SubmissionSideNav.test.tsx, services/app-web/src/pages/SubmissionSideNav/SubmissionSideNav.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.test.tsx, services/cypress/integration/cmsWorkflow/rateReview.spec.ts, services/cypress/integration/stateWorkflow/submissionSummary.spec.ts
[MCR-2553](https://jiraent.cms.gov/browse/MCR-2553)
Fix back link text. `Back to dashboard` -> `Go to dashboard`
=> Change Back to dashboard to Go to dashboard

dev_tool/src/jumpbox.ts
Meghan had an issue running the jumpbox clone command to get some prod data. Turns out her home network has both ipv6 and ipv4 external addresses, and the command to get her external address was returning the ipv6 address, but ssh/scp defaults to ipv4.
Here we just add the ipv4 address explicitly to the allowlist.
https://jiraent.cms.gov/browse/MCR-4501
=> Use ipv4 address in jumpbox clone

services/app-web/src/pages/SubmissionSideNav/SubmissionSideNav.test.tsx, services/app-web/src/pages/SubmissionSideNav/SubmissionSideNav.tsx
If you go on VAL or DEV, earlier submissions with `deprecatedRateProgramIDs` and no `rateProgramIDs` would show empty rate Q&A links.
This fix adds code to switch to `deprecatedRateProgramIDs` if:
- `deprecatedRateProgramIDs` has programs
- `rateProgramIDs` has no programs
If both conditions are not met, the link will fallback to the text `Rate questions: Unknown Program(s)`
`SubmissionSideNav.test.tsx`
- `'loads sidebar nav with expected links for state user'`
- I updated this test to Include rates for both no programs and only `deprecatedRateProgramIDs`
- You wont be able to test this on the review app, since we do not have submissions from a time where `deprecatedRateProgramIDs` would exist.
=> Fix rate Q&A links not showing depreciated rate names.

services/app-web/src/pages/SubmissionSideNav/SubmissionSideNav.test.tsx
`SubmissionSideNav` test failing, due to updates in route paths.
=> Fix test url from merges

services/app-web/src/pages/QuestionResponse/QATable/CMSQuestionResponseTable.tsx, services/app-web/src/pages/QuestionResponse/QATable/QuestionResponseRound.tsx
- Other divisions' questions section header typo
- Remove `(CMS)` tag on rate Q&A document table for CMS users.
=> Fix cms rate q&a questions table UI

services/app-web/src/pages/QuestionResponse/QATable/CMSQuestionResponseTable.tsx, services/app-web/src/pages/QuestionResponse/QATable/QuestionResponseRound.tsx, services/app-web/src/pages/QuestionResponse/QATable/StateQuestionResponseTable.tsx, services/app-web/src/pages/QuestionResponse/QuestionResponse.module.scss, services/app-web/src/pages/QuestionResponse/QuestionResponseHelpers/index.ts, services/app-web/src/pages/QuestionResponse/QuestionResponseHelpers/questionResponseHelpers.ts, services/app-web/src/pages/QuestionResponse/RateQuestionResponse.test.tsx, services/app-web/src/pages/QuestionResponse/RateQuestionResponse.tsx, services/app-web/src/testHelpers/apolloMocks/rateDataMock.ts
[MCR-4480](https://jiraent.cms.gov/browse/MCR-4480)
- Questions and responses are organized in two sections (see [designs](https://www.figma.com/design/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=14541-53434&node-type=frame&t=kL6zigeMblAJ7NiD-0)):
- Outstanding questions: Questions without responses.
- Answered questions: Questions with responses.
- Each question has dynamic headings based on which CMS division the question was asked by.
- Each question has a Upload response button.
- Upload response button on outstanding questions is the primary button style.
- Upload response button on answered questions is the outlined button style.
- Clicking on the Upload response takes the user to the upload response page.
- Questions would be ordered by the most recent asked date on top in …
=> MCR-4480: states see distinct table for rate questions

.github/dependabot.yml
Removing this patch group from dependabot config as we've been getting groupings too aggressively lately.
=> Remove the npm minor patch group from dependabot

services/app-web/src/pages/QuestionResponse/QATable/CMSQuestionResponseTable.tsx, services/app-web/src/pages/QuestionResponse/QATable/StateQuestionResponseTable.tsx, services/app-web/src/pages/QuestionResponse/RateQuestionResponse.test.tsx, services/app-web/src/testHelpers/apolloMocks/rateDataMock.ts
[MCR-4480](https://jiraent.cms.gov/browse/MCR-4480)
- CMS Rate Q&A table
- Fix questions in rounds not being sorted by `createdAt` in descending order
- Fix test data to better test for question order
- State Rate Q&A table
- Reduce complexity of `answeredQuestions` and `unasnweredQuestions` array from `RoundData[][]` to `RoundData[]`. Essentially instead of an array of array of questions, it will now just be an array of questions.
- Sort `answeredQuestions` and `unasnweredQuestions` by `createdAt` in descending order
- Fix test data to better test for question order
- See Kelsey's [comment](https://jiraent.cms.gov/browse/MCR-4480?focusedId=3145878&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-3145878) for reproduction steps of the issue.
=> MCR-4480 FIX: Add sorting after organizing questions.

services/app-api/src/secrets/secrets.ts
The SFDC team was hitting our API and getting some internal service errors back on a few requests, which would succeed on retries. In the logs we found that the errors coming back were from throttling exceptions in Aurora. This tweaks the connection string to fail faster when a connection cannot be made, and limits the connection from a lambda to 1 (since many lambdas will be spun up for dealing with requests and Prisma manages pooling)
=> Tweak Prisma connection pooling

services/app-api/src/emailer/emails/sendRateQuestionCMSEmail.test.ts, services/app-api/src/emailer/emails/sendRateQuestionCMSEmail.ts, services/app-api/src/emailer/emails/sendRateQuestionResponseCMSEmail.test.ts, services/app-api/src/emailer/emails/sendRateQuestionResponseCMSEmail.ts
[MCR-4623](https://jiraent.cms.gov/browse/MCR-4623)
Adding the mmcratesetting mailbox to the `ccAddresses` field for new rate question and response CMS emails.
On dev, the parameter store for `dmcpSubmissionEmails` includes the following emails
`DMCP Submission Dev1 <mc-review-qa+DMCPsubmissiondev1@truss.works>`
`DMCP Submission Dev2 <mc-review-qa+DMCPsubmissiondev2@truss.works>`
- Updated test to also look for the expected `ccAddresses`.
=> MCR-4623: add mmcratesetting mailbox as cc on state rate question emails

services/app-web/src/components/Modal/ModalOpenButton/ModalOpenButton.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.module.scss, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.test.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx, services/app-web/src/testHelpers/apolloMocks/index.ts, services/app-web/src/testHelpers/apolloMocks/userGQLMock.ts
[MCR-4586](https://jiraent.cms.gov/browse/MCR-4586)
[Figma](https://www.figma.com/design/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=14836-39365&node-type=canvas)
- Add `Approve submission` button behind feature flag.
- Only `CMS_USER` and `CMS_APPROVER_USER` can see the approve button.
- Unlock button style appears as a secondary button (`outline`) when `submission-approvals` flag is toggled on
- If a submission is unlocked the `Approve submission` button is disabled
- Feature flag Unlock button style change
`SubmissionSummary.test.tsx`
- `'Submission approval tests'`
- `'renders approve submission button for $userRole'`
- `userRoles: 'CMS_USER', 'CMS_APPROVER_USER'`
- `'renders disabled approve submission button on unlocked submission'`
- `'does not render approve submission …
=> MCR-4586: CMS sees an approve submission button

services/app-api/src/emailer/emails/sendRateQuestionCMSEmail.test.ts, services/app-api/src/emailer/emails/sendRateQuestionCMSEmail.ts, services/app-api/src/emailer/emails/sendRateQuestionResponseCMSEmail.test.ts, services/app-api/src/emailer/emails/sendRateQuestionResponseCMSEmail.ts, services/app-api/src/emailer/emails/sendRateQuestionStateEmail.test.ts, services/app-api/src/emailer/emails/sendRateQuestionStateEmail.ts, services/app-api/src/testHelpers/emailerHelpers.ts
[MCR-4623](https://jiraent.cms.gov/browse/MCR-4623)
Fixed the CC of `mmcratesetting` ( `config.dmcpSubmissionEmails` in code ) to be only on new rate question for STATE email only.
Removed the CC from CMS emails for new rate question and responses.
=> MCR-4623: Fix cc address to be on only state email for new rate questions

services/app-api/src/resolvers/contract/indexContracts.test.ts, services/app-api/src/resolvers/contract/submitContract.test.ts, services/app-api/src/resolvers/contract/unlockContract.test.ts, services/app-api/src/resolvers/contract/updateDraftContractRates.test.ts, services/app-api/src/resolvers/contract/withdrawAndReplaceRedundantRate.test.ts, services/app-api/src/resolvers/rate/fetchRate.test.ts, services/app-api/src/resolvers/rate/indexRates.test.ts, services/app-api/src/resolvers/rate/submitRate.test.ts, services/app-api/src/resolvers/rate/unlockRate.test.ts, services/app-web/src/components/FileUpload/FileUpload.test.tsx
- Fixes issue with `FileUpload` tests not finding the text `Uploading`.
- Added a `50`ms timeout to `fakeRequest` to give vitest time to find the text.
- Fix API test imports of `testS3Client` from web common code to api common code
- We had removed `deleteFile` function from web `testS3Client`.
=> Fix flakey web-unit test and API testS3Client imports

services/app-api/src/emailer/emails/__snapshots__/sendQuestionStateEmail.test.ts.snap, services/app-api/src/emailer/emails/__snapshots__/sendRateQuestionStateEmail.test.ts.snap, services/app-api/src/emailer/etaTemplates/sendQuestionStateEmail.eta, services/app-api/src/postgres/contractAndRates/approveContract.test.ts, services/app-web/src/pages/QuestionResponse/UploadResponse/UploadResponseForm.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.test.tsx
[MCR-4624](https://jiraent.cms.gov/browse/MCR-4624)
- Add the following copy to the "Add responses" page for rate questions: 
- `"You must submit the response in a DOC or DOCX format. Appendices to the responses can be in PDF, CSV, DOC, DOCX, XLS, XLSX files."`
- See [Figma link ](https://www.figma.com/design/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=14541-53262&t=QZEn0JiVxA9oPXjV-1)for details. 
- Add the following copy to the State Rate Question Notification emails: 
- `"You must respond to the questions before CMS can continue their review. Responses should be submitted in DOC or DOCX format."`
- See [Figma link ](https://www.figma.com/design/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=14778-34327&t=WbyjwzwEiNL8FSmn-1) for details.
- Fix input error in 1 API unit test. …
=> MCR-4624: update copy on rate Q&A

services/app-web/src/pages/QuestionResponse/UploadResponse/UploadResponseForm.tsx
[MCR-4624](https://jiraent.cms.gov/browse/MCR-4624)
Fix the `FileUpload` hint for contract question response form.
=> Fix contract question response file upload hint.

services/app-web/src/components/ContractTable/ContractTable.tsx
We removed `UNDER_REVIEW` from `ConsolidatedContractStatus` because the API doesn't return it. Updating contract table status tag logic to remove checking for this status.
=> Fix type error on contract table

services/app-api/src/domain-models/HealthPlanPackageType.ts, services/app-api/src/emailer/emails/__snapshots__/resubmitPackageCMSEmail.test.ts.snap, services/app-api/src/emailer/emails/__snapshots__/resubmitPackageStateEmail.test.ts.snap, services/app-api/src/emailer/emails/__snapshots__/sendQuestionCMSEmail.test.ts.snap, services/app-api/src/emailer/emails/__snapshots__/sendQuestionResponseCMSEmail.test.ts.snap, services/app-api/src/emailer/emails/__snapshots__/sendQuestionResponseStateEmail.test.ts.snap, services/app-api/src/emailer/emails/__snapshots__/sendQuestionStateEmail.test.ts.snap, services/app-api/src/emailer/emails/__snapshots__/sendRateQuestionCMSEmail.test.ts.snap, services/app-api/src/emailer/emails/__snapshots__/sendRateQuestionResponseCMSEmail.test.ts.snap, services/app-api/src/emailer/emails/__snapshots__/sendRateQuestionResponseStateEmail.test.ts.snap, services/app-api/src/emailer/emails/__snapshots__/unlockContractCMSEmail.test.ts.snap, services/app-api/src/emailer/emails/__snapshots__/unlockContractStateEmail.test.ts.snap, services/app-api/src/emailer/emails/__snapshots__/unlockPackageCMSEmail.test.ts.snap, services/app-api/src/emailer/emails/__snapshots__/unlockPackageStateEmail.test.ts.snap, services/app-api/src/emailer/emails/resubmitPackageCMSEmail.test.ts, services/app-api/src/emailer/emails/resubmitPackageStateEmail.test.ts, services/app-api/src/emailer/emails/sendQuestionCMSEmail.test.ts, services/app-api/src/emailer/emails/sendQuestionResponseStateEmail.test.ts, services/app-api/src/emailer/emails/sendQuestionStateEmail.test.ts, services/app-api/src/emailer/emails/sendRateQuestionCMSEmail.test.ts, services/app-api/src/emailer/emails/sendRateQuestionResponseCMSEmail.test.ts, services/app-api/src/emailer/emails/sendRateQuestionResponseStateEmail.test.ts, services/app-api/src/emailer/emails/unlockContractCMSEmail.test.ts, services/app-api/src/emailer/emails/unlockContractStateEmail.test.ts, services/app-api/src/emailer/emails/unlockPackageCMSEmail.test.ts, services/app-api/src/emailer/emails/unlockPackageStateEmail.test.ts, services/app-api/src/postgres/contractAndRates/approveContract.test.ts
`app-api` was not building properly due to a change in the `HealthPlanPackageType`. This fixes that.
I also noticed our snapshots are out of date, so this updates that as well.
=> Fix HealthPlanPackageType import

.github/workflows/deploy.yml
The PR that broke common-code into modules need to reference itself in `deploy.yml` for CI changes. This moves that sha back to `main`.
=> Fix deploy.yml from previous PR

.github/workflows/deploy.yml, .github/workflows/promote.yml
Looks like the new common-code packages build is missing from the Cypress step in promote. This adds it.
=> Add codegen and package build to Cypress in Promote

services/app-api/src/handlers/apollo_gql.ts
We've been seeing some logs with payload sizes being too big (HTTP 413) from Apollo. It seems as if users are trying to paste long documents into form fields, and the middleware default in Express, which Apollo uses, is 100kb. This bumps the payload size to match API gateway limits.
https://jiraent.cms.gov/browse/MCR-4849
=> Bump body parser config size

dev_tool/src/local/graphql.ts, packages/mocks/src/apollo/contractPackageDataMock.ts, packages/mocks/src/apollo/rateDataMock.ts, services/app-api/prisma/migrations/20241220161611_add_withdrawn_rate_join_table/migration.sql, services/app-api/prisma/schema.prisma, services/app-api/src/domain-models/contractAndRates/contractTypes.ts, services/app-api/src/domain-models/contractAndRates/rateTypes.ts, services/app-api/src/postgres/contractAndRates/parseContractWithHistory.ts, services/app-api/src/postgres/contractAndRates/parseRateWithHistory.ts, services/app-api/src/postgres/contractAndRates/prismaFullContractRateHelpers.ts, services/app-api/src/postgres/contractAndRates/submitRate.ts, services/app-api/src/postgres/contractAndRates/withdrawRate.ts, services/app-api/src/resolvers/contract/submitContract.test.ts, services/app-api/src/resolvers/contract/submitContract.ts, services/app-api/src/resolvers/rate/withdrawRate.test.ts, services/app-api/src/resolvers/rate/withdrawRate.ts, services/app-api/src/testHelpers/gqlRateHelpers.ts, services/app-graphql/src/mutations/approveContract.graphql, services/app-graphql/src/mutations/submitContract.graphql, services/app-graphql/src/mutations/submitRate.graphql, services/app-graphql/src/mutations/unlockContract.graphql, services/app-graphql/src/mutations/unlockRate.graphql, services/app-graphql/src/mutations/withdrawRate.graphql, services/app-graphql/src/queries/fetchContract.graphql, services/app-graphql/src/queries/fetchContractWithQuestions.graphql, services/app-graphql/src/queries/fetchRate.graphql, services/app-graphql/src/queries/fetchRateWithQuestions.graphql, services/app-graphql/src/schema.graphql, services/cypress/integration/adminWorkflow/settings.spec.ts
[MCR-4847](https://jiraent.cms.gov/browse/MCR-4847)
Summary:
This work refactors the withdraw API to remove the withdrawn rates from a submitted submission. 
The API will:
- Find all contracts related to the rate that is being withdrawn.
- UNLOCKED and DRAFT contracts will be untouched
- If even one of the related submissions are APPROVED, it will return an error to the client, we do not want to withdraw a rate if it's a child or linked to a approved contract.
- SUBMITTED and RESUBMITTED contracts will be unlocked, rate being withdrawn will be removed, and then resubmitted.
- [🛑**READ THIS PLEASE**] Withdrawn rate is resubmitted, removing itself from an UNLOCKED or DRAFT contracts `draftRates`. This means in the UI any unlocked submission that had this rate, will no longer have it after …
=> MCR-4847: Refactor withdraw rate api to move contract to rate relationship

services/app-api/serverless.yml, services/app-api/src/handlers/bulk_download.ts, services/app-web/src/s3/s3Amplify.ts, services/cypress/integration/stateWorkflow/submissionSummary.spec.ts
A state made a submission with ~100 files in the contract section and the zip file download lambda started silently failing on this number of files. There were no logs in AWS indicating an error, just a silent shutdown of the lambda after a few dozen files were streamed into the zip, even after instrumenting the code a bunch.
This PR changes the approach of the zip lambda. Instead of reading from S3 and streaming the files into the zip, this just simply downloads everything to the temporary storage and then archives the files. I suspect that streaming all those files hit some limits and was causing the silent failures. This approach of just putting everything on to the filesystem first works fine and isn't noticeably slower for zip generation.
https://jiraent.cms.gov/browse/MCR-4852
=> Refactor lambda zip function to handle 100+ files at a time

.husky/pre-commit, services/app-api/src/emailer/emails/sendWithdrawnRateStateEmail.ts, services/app-api/src/postgres/contractAndRates/withdrawRate.ts, services/app-api/src/resolvers/contract/submitContract.test.ts, services/app-api/src/resolvers/rate/withdrawRate.test.ts
[MCR-4862](https://jiraent.cms.gov/browse/MCR-4862)
- Withdrawn rates on unlocked or draft submission are silently removed when calling the withdrawRate API
- Unlocked submissions with an withdrawn rate that was a part of its last recent submission is connected to the rate via the WithdrawnRatesJoinTable.
- `sendWithdrawnRateStateEmail` sends emails to unlocked submissions that had withdrawn rate (when it was not withdrawn) on its last submission.
Other work:
- Update `pre-commit` to work on vscode. Not sure if pre-commit hooks worked for everyone else, but it did not for me when using vscode. The error log for pre-commit said to delete the portion of the script.
`withdrawRate.test.ts`
- (UPDATED) `'does not update draft contract linked to withdrawn rate'` -> `'removes rate from DRAFT and …
=> MCR-4862: update-withdrawRate-api-to-drop-withdrawn-rates

services/app-web/src/pages/LinkYourRates/LinkRateSelect/LinkRateSelect.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.test.tsx
As a state user, 
I want to not even have the option to add a withdrawn rate to a new or unlocked submission 
so that I can't inadvertently add a withdrawn link rate to a submission that needs review. 
AC: 
1. If I am on the rate details page and I am adding a linked rate 
Then I do not see the withdrawn rate appear in the rate dropdown of existing rates. 
https://jiraent.cms.gov/browse/MCR-4770
RateDetails: withdrawn rate is omitted from the linked rates dropdown
=> MCR-4770: filter withdrawn rates out of linkedRateSelect component

services/app-api/src/postgres/contractAndRates/withdrawRate.ts, services/app-api/src/resolvers/rate/withdrawRate.test.ts
- Bug 1
- In the postgres function when it's collecting rates to keep on the contract, it was overwriting unlocked rates with its previously submitted revision form data.
- The fix was to use the draft rates draft form data for all of the rates we are keeping. This is because all the contracts are unlocked at this point of the code.
- I also added an assertion to make sure that kept rates did not have their formData modified after withdraw.
- Bug 2
- The initial query of the rate to get draft and submitted contracts it was linked to was incorrect. I had originally used `submissionPackages` to get the contracts it was submitted with, where the first in the array was the most recent submission. This was incorrect because I had used `ratePosition` for ordering which was a typo, but after …
=> Fix withdrawRate API bugs

packages/constants/src/index.ts, packages/constants/src/rate.ts, services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsDashboard.tsx, services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsTable.test.tsx, services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsTable.tsx
As a CMS user, I want to know when I am looking at the rate dashboard when a rate has a status of withdrawn so I know not to focus my attention on that rate. 
AC:
- If I am looking at the rate review dashboard I see a status column as the rightmost column on the dashboard
- If a rate's parent submission is unlocked then I see rate status of “unlocked” for that rate review
- If rate is withdrawn then I see rate status of “withdrawn"
- If a rate is not withdrawn and or unlocked then the rate has a status of "submitted" 
- note: "approved: rate status has been descoped for purposes of this ticket and will be added at a later date
https://jiraent.cms.gov/browse/MCR-4647
RateReviewsTable -> expect that the status field is present and as expected
=> MCR-4647: Add status column to rate dashboard 

services/app-api/prisma/migrations/20250106160752_add_create_at_timestamp_on_withdrawn_rates_join_table/migration.sql, services/app-api/prisma/schema.prisma, services/app-web/src/components/Banner/IncompleteSubmissionBanner/IncompleteSubmissionBanner.tsx, services/app-web/src/components/Banner/index.ts, services/app-web/src/components/Modal/UnlockSubmitModal.test.tsx, services/app-web/src/components/Modal/UnlockSubmitModal.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/RateDetailsSummarySection.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/ReviewSubmit.test.tsx, services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ReviewSubmitV2.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.test.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx, services/cypress/integration/stateWorkflow/stateSubmissionForm/submissionForm.spec.ts
[MCR-4665](https://jiraent.cms.gov/browse/MCR-4665)
[State View Figma](https://www.figma.com/design/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=5-7392&p=f)
[CMS View Figma](https://www.figma.com/design/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=16547-93337)
- If a contract and rate submission only contains rates that have a status of withdrawn and the submission is unlocked, 
The state user is required to add a rate on the Rate Details page and review/submit page or will see validation errors. ([See Figma file|https://www.figma.com/design/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=16540-87248&t=at7k9ONpopMPy07u-1)]
- As a State user, If the contract is in a submitted state with only withdrawn rate there is a error banner to direct me to contact CMS to unlock ([See …
=> MCR-4665: state is required to add new rate

services/github-oidc/serverless.yml
In order to get some of the resources for AWS CDK stood up we need to add  permissions for ECR to the github-oidc user. This adds it so that I can do some further testing in my branch.
https://jiraent.cms.gov/browse/MCR-4435
=> Add ECR permissions to github oidc

services/github-oidc/serverless.yml
This is another permission the github oidc user needs to bootstrap AWS CDK.
https://jiraent.cms.gov/browse/MCR-4435
=> Add tag to OIDC role

services/app-api/src/domain-models/contractAndRates/index.ts, services/app-api/src/domain-models/contractAndRates/rateReviewActionType.ts, services/app-api/src/domain-models/index.ts, services/app-api/src/emailer/emailer.ts, services/app-api/src/emailer/emails/__snapshots__/sendWithdrawnRateCMSEmail.test.ts.snap, services/app-api/src/emailer/emails/sendWithdrawnRateCMSEmail.test.ts, services/app-api/src/emailer/emails/sendWithdrawnRateCMSEmail.ts, services/app-api/src/emailer/emails/sendWithdrawnRateStateEmail.ts, services/app-api/src/emailer/etaTemplates/sendWithdrawnRateCMSEmail.eta, services/app-api/src/emailer/generateURLs.ts, services/app-api/src/postgres/contractAndRates/withdrawRate.ts, services/app-api/src/resolvers/rate/withdrawRate.test.ts, services/app-api/src/resolvers/rate/withdrawRate.ts
[MCR-4661](https://jiraent.cms.gov/browse/MCR-4661)
AC:
- If a rate is withdrawn, then withdrawal notification emails are sent to the following CMS inboxes:
- DMCO staff assigned to the state of the rate submission
- [MMCRatesetting@cms.hhs.gov](mailto:MMCRatesetting@cms.hhs.gov) (excluding PR state).
- [OACTMedicaidManagedCare@cms.hhs.gov](mailto:OACTMedicaidManagedCare@cms.hhs.gov) (excluding PR state)
Other work:
- Fixed another transaction in `withdrawRate` postgres function that needed to be thrown
- Added a summary for `withdraRate` postgres function.
- Refactored withdrawn rate email validation into a common function
- Abstracted out common code generating urls for emails.
- `sendWithdrawnRateCMSEmail.test.ts`
- Same tests as state email function, but looking for CMS emails.
- …
=> MCR-4661: CMS receives withdrawn rate email notification

services/app-api/src/postgres/contractAndRates/withdrawRate.ts, services/app-api/src/resolvers/rate/withdrawRate.test.ts, services/app-web/src/components/ChangeHistory/ChangeHistory.test.tsx
- This PR updates the submission and unlock entries in the change history table to display the withdrawal reason
https://jiraent.cms.gov/browse/MCR-4791
[Updated Designs](https://www.figma.com/design/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=16528-58296&t=1Qg2mXt2xAgZzvib-0)
ChangeHistory -> 'has expected text in the accordion titles and content for rate withdrawal'
- login as a CMS user and withdraw a rate
- Check the submission summary page has captured the unlock and resubmit actions for the rate withdraw
- login as a state user
- Confirm the submission summary page has captured the unlock and resubmit actions for the rate withdraw
=> MCR-4791: Add rate withdraw actions to change history table

packages/mocks/src/apollo/contractPackageDataMock.ts, services/app-graphql/src/schema.graphql, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.test.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.tsx, services/app-web/src/pages/StateSubmission/RateDetails/rateDetailsHelpers.ts
[MCR-4873](https://jiraent.cms.gov/browse/MCR-4873)
- After a rate is withdrawn the contract actions it was associated with should still appear in the contract actions section.
`SingleRateSummarySection.test.tsx`
- 'renders contract actions correctly after rate withdraw'
=> MCR-4873: update the contract actions section on rate summary page

services/app-api/src/resolvers/contract/submitContract.test.ts, services/app-api/src/resolvers/contract/submitContract.ts, services/app-api/src/resolvers/contract/unlockContract.ts, services/app-api/src/resolvers/contract/updateDraftContractRates.test.ts, services/app-api/src/resolvers/contract/updateDraftContractRates.ts, services/app-api/src/resolvers/questionResponse/createRateQuestion.test.ts, services/app-api/src/resolvers/questionResponse/createRateQuestion.ts, services/app-api/src/resolvers/rate/submitRate.test.ts, services/app-api/src/resolvers/rate/submitRate.ts, services/app-api/src/resolvers/rate/unlockRate.test.ts, services/app-api/src/resolvers/rate/unlockRate.ts, services/app-web/src/pages/QuestionResponse/QATable/CMSQuestionResponseTable.tsx, services/app-web/src/pages/QuestionResponse/QuestionResponseSummary/ContractQuestionResponse.tsx, services/app-web/src/pages/QuestionResponse/QuestionResponseSummary/RateQuestionResponse.tsx
- Restrict API endpoints to account for withdrawn rates
- updateDraftContractRates
- unlockRate
- submitRate
- createRateQuestion
- submitContract
- Remove `Add question` button on rate Q&A page if rate was withdrawn.
`submitContract.test.ts`
- `'submits a contract and removes existing rates on the contract'`
`updateDraftContractRatest.test.ts`
- `'doesnt allow linking a WITHDRAWN rate'`
`createRateQuestion.test.ts`
- `'returns an error if the rate is in invalid status for questions'`
`submitRate.test.ts`
- `'errors with invalid rate status'`
`unlockRate.test.ts`
- `'does not allow rates with wrong status to be unlocked'`
=> MCR-4751: restrict existing api for withdrawn rates

services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsTable.test.tsx, services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsTable.tsx
[MCR-4653](https://jiraent.cms.gov/browse/MCR-4653)
AC:
- If I hit my rate dashboard, withdrawn rates are filtered out by default
Other work:
- Simplify loading filters from URL when the URL had filters
- The original implementation was for some UI flickering. Seems like it's no longer an issue without it.
`RatesReviewTable.tsx`
- `'renders rates table correctly'`
- Updated to assert withdrawn rate was not visible.
=> MCR-4653: CMS does not see withdrawn rate reviews on dashboard by default

services/cypress/integration/cmsWorkflow/rateReview.spec.ts, services/cypress/support/commands.ts, services/cypress/support/loginCommands.ts, services/cypress/support/stateSubmissionFormCommands.ts
[4783](https://jiraent.cms.gov/browse/MCR-4783)
AC: 
- There is a end-to-end test for the withdraw rate workflow
=> MCR-4783: withdraw rate e2e test

services/app-api/prisma/migrations/20250122005954_add_application_and_email_settings_table/migration.sql, services/app-api/prisma/schema.prisma, services/app-api/src/postgres/prismaClient.ts
[MCR-4887](https://jiraent.cms.gov/browse/MCR-4887)
AC:
- Add `ApplicationSettings` table
- Add `EmailSettings` Table
- Add the following fields with default values from `dev`
- emailSource String
- devReviewTeamEmail String[]
- helpDeskEmail String[]
- cmsReviewHelpEmailAddress String[]
- cmsRateHelpEmailAddress String[]
- oactEmails String[]
- dmcpReviewEmails String[]
- dmcpSubmissionEmails String[]
- dmcoEmails String[]
- Insert 1 record for each table with a 1:1 relationship
- Restrict duplicate rows (Singleton table) for both tables.
- Restrict Prisma delete method from this table using Prisma [client-extensions](https://www.prisma.io/docs/orm/prisma-client/client-extensions#example-use-cases-for-extended-clients)
=> MCR-4887: add new application settings table

services/app-web/src/components/ErrorAlert/ContactSupportLink.tsx, services/app-web/src/pages/StateSubmission/RateDetails/SingleRateFormFields.tsx, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx
[MCR-4868](https://jiraent.cms.gov/browse/MCR-4868)
The two links above contract programs and rate program dropdown was suppose to be mailto links.
=> Fix program dropdown help link to mail to

services/app-api/src/emailer/emails/newContractStateEmail.test.ts, services/app-api/src/emailer/emails/newContractStateEmail.ts, services/app-api/src/emailer/etaTemplates/newContractStateEmail.eta
[MCR-4689](https://jiraent.cms.gov/browse/MCR-4689)
AC:
- The following section of the state submission confirmation email is REMOVED from CHIP-ONLY submissions: 
```html
What comes next:
1. Check for completeness: CMS will review all documentation submitted to ensure all required materials were received.
2. CMS review: Your submission will be reviewed by CMS for adherence to federal regulations.
3. Questions: You may receive questions via email from CMS as they conduct their review.
4. Decision: Once all questions have been addressed, CMS will contact you with their final recommendation.
```
CHIP-only submission email
All other submissions
`newContractStateEmail.test.ts`
- `'does not include information about what is next for CHIP-only submissions'`
=> MCR-4689: Chip only submission email copy change

packages/mocks/src/apollo/rateDataMock.ts, services/app-web/src/components/Modal/UnlockSubmitModal.tsx, services/app-web/src/hooks/useContractForm.ts, services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsDashboard.tsx, services/app-web/src/pages/CMSDashboard/SubmissionsDashboard/SubmissionsDashboard.tsx, services/app-web/src/pages/QuestionResponse/QuestionResponseSummary/ContractQuestionResponse.tsx, services/app-web/src/pages/QuestionResponse/QuestionResponseSummary/RateQuestionResponse.test.tsx, services/app-web/src/pages/QuestionResponse/QuestionResponseSummary/RateQuestionResponse.tsx, services/app-web/src/pages/RateSummary/RateSummary.test.tsx, services/app-web/src/pages/RateSummary/RateSummary.tsx, services/app-web/src/pages/RateWithdraw/RateWithdraw.test.tsx, services/app-web/src/pages/StateDashboard/StateDashboard.tsx, services/app-web/src/pages/SubmissionReleasedToState/ReleasedToState.test.tsx, services/app-web/src/pages/SubmissionSideNav/RateSummarySideNav.test.tsx, services/app-web/src/pages/SubmissionSideNav/RateSummarySideNav.tsx, services/app-web/src/pages/SubmissionSideNav/SubmissionSideNav.test.tsx, services/app-web/src/pages/SubmissionSideNav/SubmissionSideNav.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.test.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx
[MCR-5071](https://jiraent.cms.gov/browse/MCR-5071)
This work re-enables frontend caching on the CMS and State submission dashboard, CMS rate dashboard, and summary pages. In addition, the dashboard pages have a 5-minute polling interval to refetch data.
AC:
- Reduce use of the loading indicator as the user travels between **cms submissions dashboard** and **cms rates dashboard**
- Reduce use of the loading indicator as the user travels between **dashboard pages and summary pages**
- NOTE: discussing with design and product, we are ok with not notifying the user that the data is being re-fetched while the cached data is on screen
- This means on the dashboard page, new submissions or submission updates will update without any sort of loading indicator.
- We also are not showing any type …
=> MCR-5071: re-enable frontend caching between summary and dashboard

services/app-api/src/domain-models/contractAndRates/contractTypes.ts, services/app-api/src/domain-models/contractAndRates/rateTypes.ts, services/app-api/src/postgres/contractAndRates/findAllContractsWithHistoryBySubmitInfo.ts, services/app-api/src/postgres/contractAndRates/findAllRatesWithHistoryBySubmitInfo.ts, services/app-api/src/postgres/contractAndRates/parseContractWithHistory.ts, services/app-api/src/postgres/contractAndRates/parseRateWithHistory.ts, services/app-api/src/postgres/postgresStore.ts, services/app-api/src/resolvers/contract/indexContracts.ts, services/app-api/src/resolvers/rate/indexRates.ts
This PR:
- Use [zod's lazy](https://zod.dev/?id=recursive-types) method on the top level `contractSchema` and `rateSchema`
- Add `useZod` optional parameter,   and turn off parse for both indexContracts and indexRates
Note: I recorded the load time on prod for the submission and rate review dashboard times below. Once this merges, I will recheck the load times
Submission dashboard: 3444 ms
Rate review dashboard: 2557 ms 
https://jiraent.cms.gov/browse/MCR-5021
=> MCR-5021: Refactor zod parse in indexContracts and indexRates

.github/workflows/deploy.yml, .github/workflows/promote.yml, pnpm-lock.yaml
There were a couple places where promote was missing the Serverless v4 license injection. This also moves the git branch ref back to `main` from the previous branch.
=> Fix promote after Serverless v4 merge

.envrc, .github/workflows/deploy-infra-to-env.yml, .github/workflows/deploy.yml, .github/workflows/promote.yml, services/ui/serverless.yml
When #3136 landed there was an accidental change for the domain name configuration in the `ui` service, which sets the CloudFront distribution's alias. This is preventing our certificates from being attached properly in `promote`. This reverts the configuration change from #3136 and uses the proper config value for the domain alias.
These env variables are added to the GitHub Actions workflow and are in our secrets here in GitHub.
=> Fix ui service's domain alias

.github/workflows/deploy.yml
The last PR included changes for the infra workflow for deploy and promote. This moves the ref back to `main`.
=> Move deploy.yml git ref back to 'main'

services/app-api/src/postgres/contractAndRates/findAllRatesWithHistoryBySubmitInfo.ts, services/app-api/src/resolvers/rate/indexRates.ts
Was seeing in prod that the rate reviews dashboard wasn't sped up with the last PR that landed. I did see that there was missing passthrough of the `useZod` flag. That's been updated in this PR, and locally saw about a 15% improvement. Once this lands, I will check what improvements are seen in prod
https://jiraent.cms.gov/browse/MCR-5107
=> MCR-5107: Update useZod flag usage for indexRates

services/app-web/src/pages/UndoRateWithdraw/UndoRateWithdraw.test.tsx, services/app-web/src/pages/UndoRateWithdraw/UndoRateWithdraw.tsx
[MCR-4096](https://jiraent.cms.gov/browse/MCR-4906)
- If I am on the undo rate withdrawal page ([Figma](https://www.figma.com/design/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=17402-62380&t=FVfI0NKnbWJg5YLS-4))
then I see a single step form field with the label "Undo withdraw" and an open text form field with the label "Reason for change."
- If I do not enter a reason and I try to undo 
then I receive an inline error message "You must provide a reason for this change" 
- If I enter a reason and click undo withdraw
Then I'm taken back to the rate summary page, and the status is changed on the API and on the dashboard for the rate. 
- This last AC is also on [MCR-4095](https://jiraent.cms.gov/browse/MCR-4905) and more suitable for that PR. For now, this work will allow the user to …
=> MCR-4096: CMS must enter a reason for undoing a rate withdrawal

packages/mocks/src/apollo/withdrawRateGQLMock.ts, services/app-api/src/postgres/contractAndRates/prismaSharedContractRateHelpers.ts, services/app-web/src/pages/UndoRateWithdraw/UndoRateWithdraw.test.tsx, services/app-web/src/pages/UndoRateWithdraw/UndoRateWithdraw.tsx
[MCR-4095](https://jiraent.cms.gov/browse/MCR-4905)
- If I click on "undo withdrawal"
Then if I navigate to the Rate Summary page I see the undo button is deactivated (or removed, depending on design feedback) and I see the "unlock rate" and "withdraw rate" buttons reappear in the actions section 
- If I click on "undo withdrawal" and I navigate to the rate dashboard 
Then I see the rate appear with a status of "Submitted" on the dashboard
- If I click on "undo withdrawal" and I navigate to the submissions containing the rate 
Then I see the rate appear as active with full rate details on the submissions it is a part of. 
- If I click cancel
then I'm navigated back to rate summary page and the rate remains withdrawn. 
Other work:
- Fix undo withdraw button text from `Undo Withdraw` -> …
=> MCR-4095: Integration: CMS can undo a rate withdrawal

services/app-api/src/postgres/contractAndRates/undoWithdrawRate.ts
Updating the `undoWithdrawRate` Postgres function to skip contracts from `withdrawnFromContracts` that are now `CONTRACT_ONLY`.
Also split updating the Rate review status and its `withdrawnFromContracts` relationship. Updating the review status before anything else so we are not modifying a rate that is still in the `WITHDRAWN` status. 
We haven't ran into either of these issues and I doubt that we will, but it's good to make sure we account for it anyways.
=> Fix undoWithdrawRate to ignore contract only contracts

.github/dependabot.yml, .github/workflows/deploy-infra-to-env.yml, .github/workflows/deploy.yml, .github/workflows/promote.yml
This bumps the VM that our GHA workflows run on to the LTS Ubuntu 24.04. I also removed the grouping configs for dependabot in CI, as we've been unable to ignore some major version updates we have tickets for due to the groupings.
https://jiraent.cms.gov/browse/MCR-5095
=> Update GitHub Actions Ubuntu to 24.04

.github/workflows/deploy.yml
The last PR in #3195 needed a local branch ref for the two updated workflows. This points things back to `main` now that it is merged in.
=> Point branch ref in deploy.yml back to 'main'

services/postgres/serverless.yml
We're getting a lot of security alerts in our `dev` environment (~140) due to RDS snapshots not having encryption enabled. However, we really shouldn't even need snapshots in `dev`, as they're for the most part all review environments with test data from Cypress or manual testing. 
This disables all backups for review environments and sets regular intervals for the main `dev` account, as well as `val` and `prod`.
https://jiraent.cms.gov/browse/MCR-5048
=> Add backup retention check for rds

services/app-web/src/components/Banner/StatusUpdatedBanner/StatusUpdatedBanner.test.tsx, services/app-web/src/components/Banner/StatusUpdatedBanner/StatusUpdatedBanner.tsx, services/app-web/src/pages/RateSummary/RateSummary.test.tsx, services/app-web/src/pages/RateSummary/RateSummary.tsx, services/app-web/src/pages/UndoRateWithdraw/UndoRateWithdraw.tsx
[MCR-4909](https://jiraent.cms.gov/browse/MCR-4909)
https://github.com/user-attachments/assets/4da5b33c-a306-4deb-8ebd-c1c503e4716f
Added tests to check for banner rendering
1. Login as a CMS user
2. access the rate summary page and withdraw a rate
3. Should navigate back to the rate summary page and display the expected banner
4. The banner should disappear upon refresh or if you navigate away
5. sign out and sign in as the appropriate state user
6. Access the contract with the the withdrawn rate and the banner should display as expected
=> [MCR-4909] cms and state sees confirmation banner about status change

packages/hpp/package.json, pnpm-lock.yaml, services/app-api/package.json, services/app-web/package.json, services/uploads/package.json
As I've been going through the security vulnerability alerts I've just been pushing up easy changes for some intermediary dependencies. This bumps `vite-plugin-node-polyfills` and `serverless-offline`.
https://jiraent.cms.gov/browse/MCR-5132
https://jiraent.cms.gov/browse/MCR-1795
=> Bump vite-plugin-node-polyfills and serverless-offline

.github/workflows/deploy-app-to-env.yml, .github/workflows/deploy.yml, .github/workflows/sechub-jira-sync.yml, .github/workflows/validate-prs.yml
Looks like in #3195 I missed a few spots where the GHA runner was supposed to be bumped to Ubuntu 24.04. This takes care of the last remaining few.
=> Bump remaining GHA images to 24.04

.github/workflows/deploy.yml
This just moves the workflow ref back to `main` from the #3218  PR.
=> Move workflow ref back to 'main'

packages/hpp/package.json, pnpm-lock.yaml, services/app-web/package.json, services/app-web/vite.config.ts
As part of the security alert review/prioritization I noticed that `vite-plugin-node-polyfills` isn't needed any longer. This removes it.
=> Remove 'vite-plugin-node-polyfills'

services/app-api/serverless.yml
This adds additional services to the `dependsOn` clause in the `AWS::WAFv2::WebACLAssociation`. We were hitting issues in review branches that caused the WAF to fail it's attachment because the API Gateway wasn't fully deployed before the attachment was attempted. Previously we were able to just depend on the value in `ApiGatewayDeployment${sls:instanceId} `, which would mean we were waiting on the entire API Gateway deployment first. However, there is [a bug](https://github.com/serverless/serverless/issues/12894) in Serverless 4.2.3 that makes the `${sls:instanceId}` unpredictable within the same serverless deploy instantiation. Since versions `> 4.2.3` [break local development](https://github.com/serverless/serverless/discussions/12618) we are kinda stuck until we can finally ditch this …
=> Add more services to dependsOn in api gateway

services/app-api/src/postgres/contractAndRates/undoWithdrawRate.ts
There was a bug when a contract had only a single rate and it was withdrawn, then un-withdrawn. I had mistakenly put creating thew new review action type for the rate at the top of `undoWithdrawRateInsideTransaction`, which would not work because `unlockContractInsideTransaction` will see it as a submitted rate and try to unlock it again.
Moving this block code for creating review action to after the rates have been reattached to the contract fixes the code. I initially had this code block at the bottom, but I believe I was thinking it made more sense to un-withdrawal it before reattaching it.
=> Fix undoWithdraw API

packages/common-code/src/featureFlags/flags.ts, packages/mocks/src/apollo/contractPackageDataMock.ts, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.test.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx, services/cypress/support/submissionReviewCommands.ts
[MCR-4891](https://jiraent.cms.gov/browse/MCR-4891)
- If I am logged in as a CMS user and I am viewing a submission summary 
Then I see an Actions section at the top of the page with the "Unlock" and "Release to state" buttons nested within it 
- If there is a banner at the top of the submission summary (like the unlock or submission edited banner) 
Then the Actions section will appear below the banner. 
- If I have performed an action on a submission, (such as "released to state" or "withdrawn") 
Then the Actions section will appear below the banner with the following copy included in the section, "No action can be taken on this submission in it's current status."([See Figma](https://www.figma.com/design/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=17311-87315&t=MhLXEukOumzpDzDc-1)) …
=> MCR-4891: Action section on submission summary page and add new feature flag

services/app-api/src/handlers/cleanup.ts
We noticed a little while back that some older snapshots for RDS were not being cleaned out properly. It looks like it might be because I wrote the original cleanup script using a `forEach`, which might not finish before the lambda halts. This moves us to use a `Promise.all` approach so that we can make sure the lambda doesn't stop before the operations finish. 
https://jiraent.cms.gov/browse/MCR-5114
=> Refactor RDS snapshot lambda

.github/workflows/deploy-infra-to-env.yml, .github/workflows/deploy.yml, .github/workflows/destroy.yml, services/postgres/db-manager.sh, services/postgres/serverless.yml, services/postgres/src/logicalDatabaseManager.ts, services/postgres/src/secrets.ts
Up until now we've been deploying a fully unique environment for git branches and PRs, which includes standing up an individual Aurora Postgres instance just like we have in dev/val/prod. However, this approach causes an increase of resources in our `dev` AWS account (Aurora, networking, snapshots, etc.). 
This change will now have us deploy a logical DB that is a part of the main `dev` database and will not stand up a separate Aurora instance for review environments. It uses a lambda in the `postgres` service to add or delete the logical database. When a new branch is created, the `postgres` deploy step will create the infrastructure and then call the lambda to 1) generate a new AWS secrets manager secret 2) log into the `dev` db to create the new user 3) create the new database inside …
=> MCR-2645 Use logical DB for review environments

.github/workflows/deploy-infra-to-env.yml, .github/workflows/deploy.yml, .github/workflows/promote.yml, services/postgres/serverless.yml
Another cleanup from merging #3237. We need to have the ARNs be valid for the environment that serverless is deploying into, otherwise CloudFormation fails to promote. We need to use these for now since we can't easily exclude deploying this logical DB lambda from val/prod. We do have safeguard checks in place for higher environments though, which will exit the lambda if the stage matches val or prod.
=> Use different ARNs for dev/val/prod when deploying logical DBs

packages/dates/src/calendarDate.ts, services/app-web/src/pages/StateSubmission/RateDetails/RateDetailsSchema.ts, services/app-web/src/pages/StateSubmission/RateDetails/SingleRateFormFields.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.tsx
[MCR-5000](https://jiraent.cms.gov/browse/MCR-5000)
- Add Yup validation for rate cert date so that the date cannot be after the current date..
=> MCR-5000: State cannot add rate cert date that is in the future.

packages/mocks/src/apollo/rateDataMock.ts, services/app-web/src/components/Banner/RateWithdrawBanner/RateWithdrawBanner.tsx, services/app-web/src/pages/RateSummary/RateSummary.test.tsx, services/app-web/src/pages/RateSummary/RateSummary.tsx, services/app-web/src/pages/RateWithdraw/RateWithdraw.test.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.test.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx, services/cypress/support/submissionReviewCommands.ts
[MCR-5164](https://jiraent.cms.gov/browse/MCR-5164)
AC:
- If I am logged in as a CMS user and I am viewing a rate summary that has been independently withdrawn or unlocked
Then the Actions section will appear below the banner with the following copy included in the section, "No action can be taken on this rate certification in it’s current status."
- If I am logged in as a CMS user and I am viewing a rate summary that has been withdrawn alongside a submission (dependent withdrawal)
Then the Actions section will appear below the banner with the following copy included in the section, "No action can be taken on this rate certification in it’s current status." (You will have to use graphql-explorer to use submission withdraw)
- If I am logged in as a CMS user and I am viewing a rate summary …
=> MCR-5164: cms sees empty actions on rate summary

services/app-api/src/postgres/contractAndRates/undoWithdrawRate.ts, services/app-api/src/postgres/contractAndRates/withdrawRate.ts
- [MCR-5209](https://jiraent.cms.gov/browse/MCR-5209)
We were hitting the Prisma default transaction timeout of 5s. I increased the timeout for both withdraw and undo withdraw to 30s. We don't anticipate a rate linked to more than 4 contracts, so 30s should be ok. You will hit another timeout if more submissions are linked to the rate.
Note: This is a quick solution, the long term fix here is to reduce the execution time of each prisma transaction function we use. Even then, this will be a long running query since we are performing unlock and resubmit on multiple contracts linked to a rate.
Test to make sure we don't hit timeout.
- Create a submission with a rate.
- Linked four other submissions to the rate
- Try to withdraw the rate
- Try to undo withdraw the rate
=> MCR-5209: Increase timeout for withdraw and undo withdraw rate transactions.

services/postgres/serverless.yml
The last PR hit an issue with the `postgres` writer instance in `main`. This adds a trivial tag to attempt to get it to run.
=> Use a tag to recreate postgres dev

services/postgres/serverless.yml
For some reason serverless via cloudformation is not waiting on the aurora cluster before creating the writer instance. That makes sense looking at the config -- there is no `DependsOn` between the two configs. I'm not sure why this worked before, but we do need this dependency there.
https://jiraent.cms.gov/browse/MCR-5220
=> Add DependsOn for Aurora

services/postgres/serverless.yml
Looks like there was a subtle bug in the config for how we were referencing the secrets manager attachment after moving to logical DBs. This moves us back to using the reference to the Aurora DB for the `TargetID` for the secrets manager attachment. This should get promotes working again, and I'll do a follow up to make sure review environments have the proper targetId set from the environment again once this promotes.
https://jiraent.cms.gov/browse/MCR-5220
=> Fix !Ref for postgres secrets manager

services/postgres/serverless.yml, services/postgres/src/logicalDatabaseManager.ts
When I was cleaning out dev resources I found a subtle bug in the serverless/cloudformation config for the logical review environment DBs. Merging #3277 fixed it, but also forced a DB run in dev, which gave us a new postgres DB instance. This uncovered a change in the way that Aurora Postgres sets it's default permissions now. 
This adds the new, proper permissions to the logical DB schema and user.
https://jiraent.cms.gov/browse/MCR-5220
=> Fix user permissions on Postgres Aurora logical DB

services/ui-auth/serverless.yml
We received a pen test result detailing that our Cognito setup in `dev` allowed for users with the identity pool values that are bundled with our front end could sign up for an account using the aws CLI. This was known, as we previously made an exception for `dev` for this functionality as we use test users in our review environments for things like Cypress tests. So a user could create an account for themselves, but that account has no privileges associated with it. This is enough to trip a pen test finding though.
Turns out that at some point our script that adds these test users in review environments stopped needing this unprivileged signup. I was able to just turn on the `AllowAdminCreateUserOnly: true` for all stages in our `AWS::Cognito::UserPool` setup. CI still works, I can log …
=> Require 'admin=true' for cognito signup

docs/architectural-decision-records/029-review-envs-use-logical-dbs.md
This just adds the (already decided) ADR for using logical DBs deployed inside a single Postgres Aurora instance in our `dev` AWS account.
https://jiraent.cms.gov/browse/MCR-5166
=> ADR on using logical DBs in Aurora

services/app-api/src/handlers/bulk_download.ts
We had a submission come in with a lot of ~25MB pdfs attached, which hit that upper limit of 500MB we have set for zip file generation. This bumps us up to 600MB in order to get this submission's zip file generated properly.
https://jiraent.cms.gov/browse/MCR-5227
=> Bump max file size for zip file generation

services/app-api/src/handlers/bulk_download.ts
I just merged a PR (#3300)  to bump the max file size for a zip to 600MB, as we were getting an error with one of our users that has a submission with > 500MB in files (the previous limit). Looks like error in our logs of attempting to zip 515MB was just the first value over the limit which caused the lambda to exit -- we're now getting one around the 600MB limit. 
This bumps us up to a full gig. I looked at the bulk dl request and it doesn't look like it'll exceed that.
https://jiraent.cms.gov/browse/MCR-5195
=> Bump bulk download to 1GB

services/app-api/src/postgres/contractAndRates/findAllRatesStripped.test.ts, services/app-api/src/postgres/contractAndRates/findRateRelatedContracts.test.ts, services/app-api/src/postgres/contractAndRates/findRateRelatedContracts.ts, services/app-api/src/postgres/contractAndRates/parseContractWithHistory.ts, services/app-api/src/postgres/contractAndRates/prismaSharedContractRateHelpers.ts, services/app-api/src/postgres/contractAndRates/prismaSubmittedRateHelpers.ts, services/app-api/src/postgres/contractAndRates/prismaToDomainModel.test.ts, services/app-api/src/postgres/contractAndRates/reassignParentContract.ts, services/app-api/src/postgres/contractAndRates/unlockContract.ts, services/app-api/src/postgres/contractAndRates/unlockRate.ts, services/app-api/src/postgres/contractAndRates/withdrawContract.ts, services/app-api/src/postgres/contractAndRates/withdrawRate.ts, services/app-api/src/resolvers/contract/fetchContract.test.ts, services/app-api/src/resolvers/contract/indexContracts.test.ts, services/app-api/src/resolvers/contract/submitContract.test.ts, services/app-api/src/resolvers/contract/withdrawContract.test.ts, services/app-api/src/resolvers/rate/submitRate.test.ts, services/app-api/src/resolvers/rate/undoWithdrawRate.test.ts, services/app-api/src/resolvers/rate/withdrawRate.test.ts, services/app-api/src/testHelpers/assertionHelpers.ts, services/app-api/vitest.config.ts
[MCR-5207](https://jiraent.cms.gov/browse/MCR-5207)
- Refactor `withdrawContract` postgres function to reassign child rates that cannot be withdrawn to new parent contracts.
- Child rates linked to other contracts that are `SUBMITTED`, `UNLOCKED` (but had been submitted with this linked rate), and `APPROVED` cannot be withdrawn.
- These rates will be reassigned a new parent contract. The contract will chosen from the contracts linked to this rate.
- The priority of the selected of the new parent contract is based on the status. From highest to lowest priority `SUBMITTED` -> `UNLOCKED` -> `APPROVED`.
- The `UNLOCKED` contract must have been submitted with this rate previously as a linked rate.
- `SUBMITTED` includes `RESUBMITTED`, but in the code we are just checking if the latest revision …
=> MCR-5207: reassign parent contract on withdrawn contracts child rates

services/app-api/serverless.yml, services/app-api/src/handlers/bulk_download.ts
We have a user that has a lot of medium sized pdf files in their submission. This is bumping into the max lambda timeout for a lambda attached to an API gateway (29s), which is causing the zip lambda to fail. This changes the compression level to 0 for the `zlib` library, which essentially is no compression at all. We also increase the batch size for downloading the files.
This has allowed the zip file to be created (~615MB) just shy of the 29s limit, but we'll need to refactor the way we're handling zips sometime soon (we've talked about this a couple times already). Zip file sizes are going to be larger for batch file downloads until this changes and we can put the zlib compression back up.
https://jiraent.cms.gov/browse/MCR-5195
=> Change compression size on zip lambda

services/cypress/integration/cmsWorkflow/rateReview.spec.ts, services/cypress/support/commands.ts
Cypress testing for undoing a withdrawn rate
[MCR-5015](https://jiraent.cms.gov/browse/MCR-5015)
1. CMS user should be able to successfully withdraw a rate
=> [MCR-5015] Undo withdraw cypress test

services/app-web/src/pages/SubmissionWithdraw/SubmissionWithdraw.tsx
This is a small PR to ensure the heading is updated on the submission withdraw page to match the submission being withdrawn
[See comment on ticket](https://jiraent.cms.gov/browse/MCR-4644?focusedId=3834411&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-3834411)
Visit the submission withdraw page as a CMS user and expect the heading to match
=> [MCR-4644] update heading

services/app-api/src/postgres/contractAndRates/findContractWithHistory.test.ts, services/app-api/src/postgres/contractAndRates/unlockContract.ts, services/app-api/src/postgres/contractAndRates/withdrawRate.ts, services/app-api/src/resolvers/rate/undoWithdrawRate.test.ts, services/app-api/src/resolvers/rate/undoWithdrawRate.ts, services/app-api/src/resolvers/rate/withdrawRate.test.ts, services/app-api/src/resolvers/rate/withdrawRate.ts, services/app-web/src/pages/RateSummary/RateSummary.test.tsx, services/app-web/src/pages/RateSummary/RateSummary.tsx
This work updates our `withdrawRate` and `undoWithdrawRate` for the submission withdraw feature which adds a new contract status of `WITHDRAWN` and parent contract reassignment.
**Notes**
- `unlockContract` postgres functions
- This one needed updated for rate withdraw/un-withdrawal feature because of parent contract reassignment. We still query the rate the same, but now we need to look at the latest 2 rate revisions to find the contract it was submitted with.
- We only want to unlock this child rate if the latest rate submission was submitted with this contract. If it wasn't then we know this rate was reassigned or withdrawn from this contract.
- `findContractWithHistory.test.ts`
- Skipping `matches correct rate revisions to contract revision with independent rate unlocks and submits`
- …
=> MCR-5146: update withdraw and undo withdraw rate api for submission withdraw

services/app-api/src/postgres/contractAndRates/prismaSharedContractRateHelpers.ts, services/app-api/src/postgres/contractAndRates/withdrawContract.ts
Withdrawing a submission linked to an unlocked rate results in a system error. The fix was to to move checking for an unlocked child rate further in the code were we know this is a child rate. I also updated `getContractID` function to be more versatile by narrowing the parameter type to only the data we need.
[MCR-5259](https://jiraent.cms.gov/browse/MCR-5259)
Steps to validate fix: 
- Create a contract and rate submission and submit it
- Create a second contract and rate submission, linking to the rate from the first submission and submit it.
- As a CMS user unlock the first submission.
- As a CMS user try to withdraw the second submission that is linked to the rate that is the child of the first submission.
- The second submission should successfully withdraw
=> MCR-5259: withdraw contract system error

services/app-api/prisma/migrations/20250418212330_migrate_redundant_rate_to_withdrawn_rate/migration.sql
**NOTE**: After approval I will NOT be merging this until after prod/design review of the `csv` files. I do not want to apply the migration until the submission migrations looks correct.
We are deprecating the replace redundant rate feature now that we have a withdraw rate feature that accomplishes the same thing. Before we deprecate the code for replace redundant rate, we need to migrate all the rates that had been replaced using this feature into a withdrawn rate.
The migration file will find all rates that have a `withdrawInfo`, this field signifies it was a redundant rate, and use the data in that to create a `reviewStatusActions` of `WITHDRAW` for the rate. Then delete the `withdrawInfo` relationship between `RateTable` and `UpdateInfoTable` on `withdrawInfo`.
There are 12 redundant …
=> MCR-4752: Migrate rate withdrawInfo into rate reviewStatusAction WITHDRAW

packages/common-code/src/featureFlags/flags.ts
This PR adds the Undo withdraw submission feature flag to codebase. It's already been added in LaunchDarkly
[MCR-5221](https://jiraent.cms.gov/browse/MCR-5221)
=> [MCR-5221] Undo withdraw submission feature flag

.github/workflows/destroy.yml
There was a copy/paste error in the license key environment variable name from the last PR for the `destroy` action. This just fixes that.
=> Fix destroy action environment variable

packages/common-code/src/featureFlags/flags.ts, services/app-web/src/pages/App/AppRoutes.tsx, services/app-web/src/pages/SubmissionReleasedToState/ReleasedToState.test.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.test.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx, services/cypress/integration/cmsWorkflow/submissionReview.spec.ts
This PR removes the `submission-approvals` feature flag - I'll remove the flag from LD after this is merged
[MCR-4792](https://jiraent.cms.gov/browse/MCR-4792)
=> [MCR-4792] Remove the submission-approvals feature flag

services/app-api/src/handlers/apollo_gql.ts
I was looking at the response sizes locally for the bug we have on a CA submission, but the sizes are actually under the Lambda/API Gateway size limit. I want to see what it actually looks like in prod, so this is just a minimal log for the time being.
=> Add response size logging

services/ui/serverless.yml
This updates the minimum TLS version in our CloudFront distribution to match more modern versions. The quickstart we branched off of had an old setting here.
https://jiraent.cms.gov/browse/MCR-5303
=> Bump TLS version in CloudFront distro

services/app-api/src/postgres/contractAndRates/undoWithdrawContract.ts, services/app-api/src/postgres/contractAndRates/withdrawContract.ts, services/app-api/src/postgres/postgresStore.ts, services/app-api/src/resolvers/configureResolvers.ts, services/app-api/src/resolvers/contract/undoWithdrawContract.test.ts, services/app-api/src/resolvers/contract/undoWithdrawContract.ts, services/app-api/src/resolvers/contract/withdrawContract.test.ts, services/app-api/src/resolvers/contract/withdrawContract.ts, services/app-api/src/testHelpers/gqlContractHelpers.ts, services/app-api/src/testHelpers/gqlRateHelpers.ts, services/app-api/src/testHelpers/storeHelpers.ts, services/app-graphql/src/mutations/undoWithdrawContract.graphql, services/app-graphql/src/schema.graphql
[MCR-5149](https://jiraent.cms.gov/browse/MCR-5149)
Adds `undoWithdrawContract` API. This will allow a `WITHDRAWN` submission (contract and child rates) to be un-withdrawn.
- The Postgres function here is pretty simple
- Validate contract is withdrawn by querying the contract's review status to check if latest action was `WITHDRAW`
- The resolver also checks for `WITHDRAWN` status, but since this is a transaction function that could be use elsewhere we want to validate the status again.
- Unlocked the contract with default withdraw text and append inputted reason.
- Gather all draft rates with this contracts ID as the `parentContractID`
- During a submission withdraw, linked child rates (child rate that is linked to another submission) are NOT withdrawn with the contract and are …
=> MCR-5149: complete undo withdraw api

services/app-web/src/pages/LinkYourRates/LinkYourRates.stories.tsx, services/app-web/src/pages/LinkYourRates/LinkYourRates.tsx, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.test.tsx, services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.tsx
As a state user, 
I want to be prevented from removing a submitted rate from a submission. 
so that I do not inadvertently close out a rate review that CMS is in the middle of reviewing. 
AC: 
- If I am a state user on an unlocked submission contains a submitted rate and "was this rate included on any other submissions" was answered as "no", Then I do NOT see the "was this rate included on any other submissions" form field as an editable form field (suggest that the question not appear at all). 
- If I am a state user on submission contains a draft, unsubmitted rate where "was this rate included on any other submissions" = "no", Then I continue to see the "was this rate included on any other submissions" form field and I can edit it. 
- If I am a state user on a submission contains an …
=> [MCR-5274] State cannot change answer from "no" to "yes" on "was this rate included on any other submissions"

packages/constants/src/routes.ts, services/app-web/src/pages/App/AppRoutes.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.test.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx, services/app-web/src/tealium/constants.ts
CMS sees an undo withdrawal button on submission summary
AC: 
1. If I am logged in as a CMS user and I go to a submission summary page for a withdrawn submission then I see an "Undo withdraw" button in the actions section
2. If I am logged in as a CMS user and I go to a submission summary page for a submission that is submitted then I do not see "Undo Withdraw" button included but I see "Unlock submission, Withdraw submission, Released to state"
3. If I am logged in as a CMS user and I go to a submission summary page for a submission that is approved or unlocked then I do not see "Undo Withdraw" button included but I see No actions available empty state message
[MCR-4915](https://jiraent.cms.gov/browse/MCR-4915)
1. Edited an old test case to check for the undo button
1. Withdraw a …
=> [MCR-4915] CMS sees undo withdraw button on submission summary

packages/mocks/src/apollo/contractPackageDataMock.ts, services/app-web/src/components/DataDetail/DataDetail.module.scss, services/app-web/src/components/DataDetail/DataDetail.tsx, services/app-web/src/components/DataDetail/DataDetailMissingField/DataDetailMissingField.tsx, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.tsx, services/app-web/src/pages/RateSummary/RateSummary.test.tsx, services/app-web/src/pages/RateSummary/RateSummary.tsx
[MCR-5293](https://jiraent.cms.gov/browse/MCR-5293)
[design](https://www.figma.com/design/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=20073-49379&t=hNsx53PRC20wAWJ4-4)
AC:
- The Contract Actions section on the rate summary page clearly labels the orphaned rate
- The contract action section matches this [design](https://www.figma.com/design/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=20073-49379&t=hNsx53PRC20wAWJ4-4)
- The value for the contract actions label displays a red error icon and error text that reads: Missing contract action
- There is an error alert at the top of the page that reads: Incomplete submission This rate certification is missing a contract action.
- Withdrawn orphaned rates will also show both banner and missing contract actions text.
Other work:
- …
=> MCR-5293: cms sees orphan rates label on rate summary page

services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.test.tsx, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx
[MCR-5276](https://jiraent.cms.gov/browse/MCR-5276)
- Add `If you need to change your response, contact CMS.` text below population question when CHIP-only radio is disabled.
- Updated unit test.
=> MCR-5276: Fix - Add text when CHIP-only is disabled and update test

services/app-api/src/handlers/apollo_gql.ts
This PR adds logging and alerting for when a API request's payload exceeds 5.5mb
https://jiraent.cms.gov/browse/MCR-5300
=> MCR-5300: add logging and alerting for large api payload

packages/mocks/src/apollo/contractPackageDataMock.ts, packages/mocks/src/apollo/rateDataMock.ts, packages/mocks/src/apollo/withdrawRateGQLMock.ts, services/app-api/src/domain-models/contractAndRates/formDataTypes.ts, services/app-api/src/postgres/contractAndRates/parseContractWithHistory.ts, services/app-api/src/postgres/contractAndRates/parseRateWithHistory.ts, services/app-api/src/postgres/contractAndRates/prismaContractRateAdaptors.ts, services/app-api/src/postgres/contractAndRates/prismaSharedContractRateHelpers.ts, services/app-api/src/resolvers/contract/submitContract.test.ts, services/app-api/src/resolvers/rate/indexRatesStripped.test.ts, services/app-api/src/resolvers/rate/undoWithdrawRate.test.ts, services/app-api/src/testHelpers/documentHelpers.ts, services/app-graphql/src/fragments/contractRevisionFragment.graphql, services/app-graphql/src/fragments/genericDocumentFragment.graphql, services/app-graphql/src/fragments/packageSubmissionsFragment.graphql, services/app-graphql/src/fragments/ratePackageSubmissionsFragment.graphql, services/app-graphql/src/fragments/rateRevisionFragment.graphql, services/app-graphql/src/fragments/submittableRevisionFieldsFragment.graphql, services/app-graphql/src/schema.graphql, services/app-web/src/components/SubmissionSummarySection/UploadedDocumentsTable/UploadedDocumentsTable.tsx, services/app-web/src/index.tsx, services/app-web/src/pages/QuestionResponse/QuestionResponseSummary/RateQuestionResponse.test.tsx, services/app-web/src/pages/RateSummary/RateSummary.test.tsx, services/app-web/src/pages/RateWithdraw/RateWithdraw.test.tsx, services/app-web/src/pages/SubmissionSummary/SubmissionSummary.test.tsx, services/app-web/src/pages/UndoRateWithdraw/UndoRateWithdraw.test.tsx
[MCR-5332](https://jiraent.cms.gov/browse/MCR-5332)
The "Date added" field on the submission summary page was not showing the document date added for some submission summaries and not others.
Bug:
- This bug is caused by 2 things; inconsistent document `dateAdded` calculations and Apollo caching
- We have 2 parsing functions `contractWithHistoryToDomainModelWithoutRates` and `rateWithoutDraftContractsToDomainModel`, both are inconsistently calculating `dateAdded` on the revisions contained in the return data. For example `packageSubmissions.contractRevision` has the date added, but `packageSubmission.submittedRevisions` does not. On the rate side, contractRevision doc date added were not added at all.
- With the parsing functions, it's not a big deal if deeply nested docs do not get the …
=> MCR-5332: date added field not showing for some submissions

.github/workflows/destroy.yml
We've been getting alerts that our destroy action fails each time a PR is merged. This is from the OTEL phase of the action, which honestly has never worked afaik. Removing that step from the destroy action to reduce the volume of un-actionable alerts.
=> Fix destroy action

services/app-api/src/resolvers/contract/updateContract.test.ts, services/app-api/src/resolvers/contract/updateContract.ts, services/app-graphql/src/mutations/updateContract.graphql, services/app-graphql/src/schema.graphql, services/app-web/src/pages/MccrsId/MccrsId.test.tsx, services/app-web/src/pages/MccrsId/MccrsId.tsx
This PR updates the Mccrs ID form page so that it no longer uses the old health plan API and types.
- Replaces `fetchHealthPlanPackage` with `fetchContract`
- updates the `updateContract` to no longer use hpp 
https://jiraent.cms.gov/browse/MCR-4191
- Existing `updateContract` resolver and `MccrsId` page test updated to use contract API 
- As a CMS user, select a submission and navigate to the submission summary page 
- Click the 'Add MCCRS record number' link and add a new number
- Clicking save, as well going back and updating the number should work
=> MCR-4191: MCCRS ID page refactored to use contract api

pnpm-lock.yaml, services/app-web/package.json
This updates react-select, the dependabot [PR](https://github.com/Enterprise-CMCS/managed-care-review/actions/runs/15880243334/job/44778999572?pr=3433) for this was failing CI at `deploy-app` - `app-api` with the error `AWS WAF couldn?t perform the operation because your resource doesn?t exist.`. Rerunning did not help, so manually creating a update PR to get CI passing.
The update had pretty minor changes and nothing breaking. Our Cypress tests would have caught issues with the library if there were any.
=> Update react select from 5.8.0 to 5.10.1

services/app-web/src/components/FileUpload/FileUpload.tsx
This PR changes the `# files added` text within the file upload component from a header to body text to satisfy accessibility requirements
[MCR-5312](https://jiraent.cms.gov/browse/MCR-5312)
=> [MCR-5312] File upload body text is coded as h5

services/app-api/src/zip/generateZip.ts
There is a contract in val that is causing the migration script to fail, as it is right on the edge of the max filesize. This bumps the value to 1.5GB in order to get us under that for this one CA contract. 
Note: val uses a bunch of generated test documents, so I think that's why this particular contract is so big. The submission that corresponds to this in prod is a little bit smaller.
=> Bump max file size for zips

services/app-web/src/pages/Help/Help.tsx, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.test.tsx, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.tsx, services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetailsSchema.ts, services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx, services/cypress/support/stateSubmissionFormCommands.ts
Add a new required field to the Contract Details form that displays conditionally when a triggering waiver is selected. The field asks whether the contract is associated with a Dual-Eligible Special Needs Plan (D-SNP) that covers Medicaid benefits.
Acceptance Criteria:
- Field displays if user selects any of the triggering waivers. 
- Question: “Is this contract associated with a Dual-Eligible Special Needs Plan (D-SNP) that covers Medicaid benefits?”
- Response options: Yes / No (radio buttons)
- Update the [help page](https://www.figma.com/design/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=20786-5084&t=SJBmfDxZxSY4CBcH-4) and add link under field per designs
- Field is required when shown.
[MCR-5363](https://jiraent.cms.gov/browse/MCR-5363) …
=> [MCR-5363] State indicates if a contract is associated with a D-SNP

API_Changelog.md, services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.test.tsx, services/app-web/src/pages/StateSubmission/RateDetails/SingleRateFormFields.tsx, services/app-web/src/pages/StateSubmission/StateSubmissionForm.module.scss
This PR addresses design feedback. Things changed:
- Vertical alignment of the checkboxes on the rate medicaid populations question
- Ally change to have the label read out that the help link opens in a new tab
- "Medicare-Medicaid dually eligible individuals not enrolled through a D-SNP "checkbox item: the not is semi-bold rather than bold
- Field label copy updated to: "Which Medicaid populations are included in this rate certification?"
https://jiraent.cms.gov/browse/MCR-5364
=> MCR-5364: Styling and ally fixes

services/app-web/src/components/ContractTable/ContractTable.tsx, services/app-web/src/components/SubmissionSummarySection/UploadedDocumentsTable/UploadedDocumentsTable.tsx, services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsTable.tsx, services/app-web/src/pages/QuestionResponse/QATable/QuestionDisplayTable.tsx
- Fixes a reoccurring A11y issue with our tables so that the read out for each cell includes the correct row association
This PR for  https://jiraent.cms.gov/browse/MCR-5307: also covers
- documents table https://jiraent.cms.gov/browse/MCR-5310
- CMS submissions dashboard https://jiraent.cms.gov/browse/MCR-5308
- CMS rate reviews dashboard https://jiraent.cms.gov/browse/MCR-5309
- Use ANDI to check the tables on the state submission, CMS submission, CMS rate review and documents tables. Expected output is specified in each ticket
=> MCR-5307: A11y Table row-cell association fixes

services/app-web/src/pages/App/AppRoutes.tsx
[MCR-5448](https://jiraent.cms.gov/browse/MCR-5448)
Edit state assignment page was move into admin routes. This moves it back so any CMS user can edit state assignments.
- Test that CMS usr has access to the edit state assignment page.
=> MCR-5448: 404 Error When Editing State Assignments in MC-Review Portal

services/postgres/package.json, services/postgres/serverless.yml, services/postgres/src/db_import.ts
The Salesforce team was trying to test on a submission in val (mimicking prod), but the dummy document there was missing in the val environment. It turns out that when I wrote the val data import lambda I forgot that we have a separate bucket for Q&A documents. That means when the lambda generated the fake document for the test environment it placed it in the regular `uploads` bucket, whereas the link points to the `qa` bucket. 
This adds the Q&A bucket and places any Q&A document records into that separate s3 bucket. We probably should refactor this to have a single bucket for all documents, but for the time being this should fix that bug. 
We'll need to re-run the export/import once this promotes.
https://jiraent.cms.gov/secure/RapidBoard.jspa?rapidView=6115
=> Fix val import of Q&A documents

packages/hpp/src/data/statePrograms.json
Michigan is making their first MC-Review submission this September. None of their programs are rate programs.
Acceptance Criteria
Update the programs.json and the [State programs spreadsheet](https://docs.google.com/spreadsheets/d/138HHJTs4sGZucyffNFDe2dlSvYxPRSrP/edit?gid=687010743#gid=687010743) using [these instructions](https://github.com/Enterprise-CMCS/managed-care-review/blob/main/docs/technical-design/howto-update-state-programs.md)
Managed Care Health Plan Comprehensive Health Care Program's nickname is updated to MCHP
[MCR-5470](https://jiraent.cms.gov/browse/MCR-5470)
=> [MCR-5470] Updated Michigan program nickname

services/app-api/src/postgres/contractAndRates/unlockRate.ts, services/app-api/src/resolvers/rate/undoWithdrawRate.test.ts
[MCR-5480](https://jiraent.cms.gov/browse/MCR-5480)
Unlocking submission was not copying over the DNSP answer to the new rate revision.
- Create a D-SNP contract and rate submissions
- Make sure `Medicaid populations included in this rate certification` is answered on the rate details page.
- Submit the submission
- Unlock the submission
- `Medicaid populations included in this rate certification` should retain answers.
=> MCR-5480: Rate DSNP question not retaining answer on unlock

packages/hpp/src/healthPlanPackages.ts, services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummary/RateDetailsSummarySection.test.tsx, services/app-web/src/pages/StateSubmission/RateDetails/SingleRateFormFields.tsx
[MCR-5453](https://jiraent.cms.gov/browse/MCR-5453)
Update rate details/summary `Medicaid populations included in this rate certification` section.
- `Medicare-Medicaid dually eligible individuals enrolled through a Dual-Eligible Special Needs Plan (D-SNP)` -> `Medicare-Medicaid dual eligibles enrolled through a D-SNP (on summary page)`
- `Medicare-Medicaid dually eligible individuals not enrolled through a D-SNP` -> `Medicare-Medicaid dual eligibles not enrolled through a D-SNP`
Fix `Which Medicaid populations are included in this rate certification?` on rate details page. Check box selections should not be the same as the summary descriptions of the selections
Current Copy
Updated Copy
=> MCR-5453: Rate details D-SNP content fix

pnpm-lock.yaml, services/uploads/package.json
Dependabot wanted to update `ts-loader`, but Jason noticed we likely don't use it anymore. Looks like he's right, this just removes it.
=> Remove ts-loader
