.github/workflows/deploy.yml

Restore workflow to main

---

.github/workflows/deploy-to-env.yml
.github/workflows/deploy.yml

revert deploy-to-env to main and fix storybook promote

---

.github/workflows/deploy-app-to-env.yml
.github/workflows/deploy.yml
services/infra-api/serverless.yml

fix acl dependency

---

.github/workflows/deploy-app-to-env.yml
.github/workflows/deploy.yml

Revert both workflows to main

---

.github/workflows/deploy.yml

Restore deploy.yml to use main branch

---

.github/workflows/deploy.yml

Moving the sha so that we point to `main` again.

Move deploy sha to 'main'

---

services/app-web/src/pages/StateSubmission/Contacts/Contacts.test.tsx
services/app-web/src/pages/StateSubmission/Contacts/Contacts.tsx
tests/cypress/integration/stateWorkflow/stateSubmissionForm/contacts.spec.ts

Update "Add state/actuary contacts" buttons to: "Add another state contact" and "Add another actuary contact"

update add state and actuary contacts buttons

---

services/app-web/src/pages/StateSubmission/ReviewSubmit/ReviewSubmit.tsx

Fix bug discussed in frontend/design checkin with review and submit button looking different than other pages. It should be be styled as a link.

Make Save as draft an unstyled button on ReviewSubmit

---

services/app-web/src/pages/Dashboard/Dashboard.module.scss
services/app-web/src/pages/StateSubmission/StateSubmissionForm.module.scss
services/app-web/src/styles/theme/_color.scss

Updated tag styling based on accessibility needs and to better match OneMAC styling.

Update tag styling

---

.github/workflows/promote.yml

My last PR #770 had a syntax error. This should fix that.

Fix syntax on promote

---

services/app-web/src/pages/Help/Help.tsx
services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.tsx
services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx

New sections of help page include:
- Effective date guidance
- Rate certification type definitions
Links to those sections were also added to the contract details and rate details page.

Add updated help docs and links

---

services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.test.tsx
services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.tsx
services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.tsx
services/app-web/src/pages/StateSubmission/StateSubmissionForm.module.scss
services/app-web/src/styles/custom.scss

- Made a quick copy changes to the federal operating authority question
- Updated some form styling for better responsiveness

update federal operating authority and fix some responsive styling

---

services/app-web/src/s3/s3Amplify.ts

Closes [15896](https://qmacbis.atlassian.net/browse/OY2-15896)
Shoulda [listened to](https://github.com/CMSgov/managed-care-review/pull/752#discussion_r783384777) @haworku

Fix filename bug

---

.github/workflows/deploy.yml
.github/workflows/promote.yml

This swaps out the sha in #808 to use `main`.

Swap out sha

---

.github/workflows/deploy.yml

Just puts the deploy workflow back to `main`.

Fix workflow pointer

---

.github/workflows/promote.yml

Fixes a broken promote artifact download from #836.

Fix migration layer upload

---

services/app-api/data/statePrograms.json

Add Arizona to list of supported states. Add AZ programs

Add Arizona programs

---

services/app-api/emailer/emailer.ts
services/app-api/emailer/index.ts
services/app-api/emailer/templates.test.ts
services/app-api/emailer/templates.ts
services/app-api/resolvers/unlockStateSubmission.ts
services/app-api/testHelpers/emailerHelpers.ts
services/app-web/src/common-code/domain-models/index.ts

Adding template for CMS and State unlock email.

Add cms and state unlock email template

---

.github/workflows/deploy.yml
otel-collector-config.yml

Fixes up the sha change for the deploy GHA workflow.

Point deploy app to main

---

services/app-web/src/pages/Dashboard/Dashboard.tsx

See bug description, this was a styling regression over the last couple months. Fixed it a bit with #854 but realized the container element was not quite right.
https://qmacbis.atlassian.net/browse/OY2-17030 
This is the new updated error display

Fix dashboard page error display

---

docs/submissionDiagram.md

Updated diagrams. Welcome all comments.
https://qmacbis.atlassian.net/browse/OY2-16465

Update diagrams to include Revisions and use native github mermaid display

---

services/app-web/src/pages/StateSubmission/StateSubmissionContainer.tsx
services/app-web/src/pages/StateSubmission/StateSubmissionForm.module.scss

I saw this one in the pilot backlog and realized it was a pretty quick fix.

Make supporting documents page responsive width

---

services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx

We are done with this epic. The button should be available on all environment (only for CMS users)
https://qmacbis.atlassian.net/browse/OY2-17338

OY2-17338: Reveal unlock button on all environments

---

services/app-web/src/components/DownloadButton/DownloadButton.test.tsx
services/app-web/src/components/DownloadButton/DownloadButton.tsx
services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.test.tsx
services/app-web/src/components/SubmissionSummarySection/ContractDetailsSummarySection/ContractDetailsSummarySection.tsx
services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.tsx
services/app-web/src/s3/s3Amplify.ts

"Download all" zip file on submission summary should include relevant supporting docs
https://qmacbis.atlassian.net/browse/OY2-16619
We still don't have tests around file uploads
Add a variety of supporting docs and contract or rate specific docs. Check that zips are puled together correctly.

OY2-16619  "Download all" zip file on submission summary should include relevant supporting docs

---

.github/workflows/deploy.yml

Points the workflow file to main. Cleans up last merge.

Fix the sha on main

---

services/app-api/serverless.yml

This fixes the missing env variable for OTEL in `app-api`

Add correct env var to app-api

---

services/app-web/src/components/ChangeHistory/ChangeHistory.test.tsx
services/app-web/src/components/ChangeHistory/ChangeHistory.tsx
services/app-web/src/pages/SubmissionRevisionSummary/SubmissionRevisionSummary.test.tsx
services/app-web/src/pages/SubmissionRevisionSummary/SubmissionRevisionSummary.tsx
tests/cypress/integration/cmsWorkflow/unlockResubmit.spec.ts

Change versions of submissions to start at 1

Submission revisions start from 1 instead of 0

---

README.md

Adds login information for New Relic to our README.

Add new relic login instructions

---

services/app-web/public/index.html
services/app-web/src/hooks/useScript.ts
services/app-web/src/pages/App/App.tsx

Repeat of #872 after having trouble merging
https://qmacbis.atlassian.net/browse/OY2-16868

OY2-16868: Add Jira Issue Collector Feedback Tab to Dev Environment

---

services/app-web/src/pages/SubmissionRevisionSummary/SubmissionRevisionSummary.test.tsx

I command-z'ed this test away before I pushed up my last PR.  Just need an approval so I can merge it in.  🤕

re-add missing test

---

services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx

[MR-2090](https://qmacbis.atlassian.net/browse/MR-2090)
Make two copy changes on Submission type page
- Change “Program(s)” to “Programs”
- Change “Choose submission type” to “Submission type”

MR-2090: Make two copy changes on Submission type page

---

services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.tsx

Just noticed a couple of console logs I left behind.

remove console logs

---

services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx

Update unlock button copy from "submit" to "unlock"

Update unlock button copy

---

docs/ADRs/017-feature-flag-lifecycles.md

This adds some guidance around what sort of things are fine to put behind flags, how to go about adding them, and how to remove them.
https://qmacbis.atlassian.net/browse/MR-397

Add the ADR on flag usage

---

services/app-web/src/pages/Landing/Landing.tsx

Remove test banner from homepage
e

Remove test banner from homepage

---

.github/workflows/deploy.yml

Revert deplay-app uses to main branch

---

services/app-api/prisma/migrations/20220610124242_drop_pre_pilot_data_again/migration.sql

Wipe the db, now that we’ve modified the proto again
https://qmacbis.atlassian.net/browse/MR-2226

Drop all submission data again

---

.github/workflows/deploy.yml

revert deploy app to main

---

services/app-web/src/components/Form/FieldCheckbox/FieldCheckbox.tsx

This addresses the issue where the checkboxes weren’t rendering as checked on a reload. The problem was I deleted some manual state mangement code without fixing the field component to have Formik manage that state.
https://qmacbis.atlassian.net/browse/MR-2290
This works locally but I couldn’t figure out how to write a test that would have caught this yet.

[MR-2290] Fix checkbox not checked bug without a test

---

services/app-web/src/formHelpers/formatters.ts

We were correctly writing the dates in UTC to protobuf but not reading them the same way. The real fix will be to use calendar dates everywhere. 
https://qmacbis.atlassian.net/browse/MR-2289

[MR-2289] Bad Dates

---

services/app-api/src/emailer/templates.ts

Meghan found some formatting errors in validating 2179
https://qmacbis.atlassian.net/browse/MR-2179

[MR-2179] un-nest what comes next instructions

---

services/app-web/src/components/Footer/Footer.tsx
services/app-web/src/components/Header/UserLoginInfo/UserLoginInfo.test.tsx
services/app-web/src/components/Header/UserLoginInfo/UserLoginInfo.tsx

[MR-2358](https://qmacbis.atlassian.net/browse/MR-2358)
Add mc-review-team@truss.works to hardcoded feedback mailto links in footer and header. Added mc-review-team@truss.works to reviewer list in prod.
**NOTE** Updated `PROD_SES_REVIEW_TEAM_EMAIL_ADDRESSES` to include mc-review-team@truss.works.

[MR-2358]Add mc-review-team@truss.works email to mailto links and reviewer list

---

services/app-web/src/contexts/AuthContext.tsx
services/app-web/tsconfig.json
tests/cypress/integration/stateWorkflow/stateSubmissionForm/contacts.spec.ts
tests/cypress/support/stateSubmissionFormCommands.ts

Also seeing some type errors in cypress that the tsconfig change fixes.

Getting a typescript error on the LD client

---

.github/workflows/deploy-app-to-env.yml
.github/workflows/deploy.yml
.github/workflows/promote.yml

Re-adds the NR license key. Webpack needs it in the environment to do a proper replacement.

Fix NR license key for webpack

---

.github/workflows/deploy-app-to-env.yml

#1076 pasted it in the wrong service. Needs to go to `app-api`.

Put the nr key into app-api

---

services/app-api/src/data/statePrograms.json

[MR-2137](https://qmacbis.atlassian.net/browse/MR-2137)
Add new program `ACC-RBHA` to AZ programs.

[MR-2137] Update Arizona program list

---

.github/workflows/deploy.yml
services/uploads/src/antivirus.js
services/uploads/src/clamav.js
services/uploads/src/constants.js

This pulls in the changes from the quickstart repository to mitigate against potential injection attacks in the `uploads` service.
https://qmacbis.atlassian.net/browse/MR-2499

Fix vulnerability in uploads service

---

.github/workflows/deploy.yml

Print put story book endpoint in `Finish Prep`

Print storybook endpoint

---

docs/technical-design/launchDarklyTestingApproach.md

Fix LaunchDarkly testing doc markup

Fix LaunchDarkly testing doc markup

---

docs/technical-design/creatingEndpoints.md
docs/technical-design/endpoints.md

Added a doc to walk someone through creating endpoints, either in GraphQL or AWS.
Does it make sense?  Too much or not enough info?  Anything I missed or got wrong?

MR-2613: endpoint docs

---

.github/workflows/codeql.yml
README.md

This adds CodeQL support to our repository. 
https://qmacbis.atlassian.net/browse/MR-2520

Draft: Add CodeQL to MC-Review

---

.github/actions/setup_env/action.yml
services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.tsx

Meghan says that the name isn't showing up for old data.  I added a fallback to generating the name when it's not already on the submission.

MR-2698: Fix for old data

---

docs/technical-design/form-data-flow.md
services/app-web/README.md

Adds mermaid diagrams for the form data flow, from ui to db, and back again.
Let me know if I missed a step anywhere.

MR-2755: Add data flow diagrams

---

services/app-web/src/pages/Help/Help.tsx

More copy tweaks as per [discussion](https://qmacbis.atlassian.net/browse/MR-416?focusedCommentId=115417&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-115417
)
https://qmacbis.atlassian.net/browse/MR-416

Copy changes from product for help page

---

.vscode/settings.json
docs/technical-design/howto-health-plan-form-data-changes.md

This is a follow on from the versioning versus migrations technical design doc.

Add how to change HealthPlanFormData doc

---

services/app-api/src/data/statePrograms.json

updated the NM program name, added some new texas ones we didn’t have before. 
https://qmacbis.atlassian.net/browse/MR-2719

[MR-2719] Update to latest programs for NM

---

services/app-api/src/data/statePrograms.json
services/app-web/src/common-code/data/statePrograms.json

Just noticed that we made some updates to the statePrograms file in app-api.  But we also have a copy of that file in app-web 🤦 .  This just brings app-web up to date.

Sync statePrograms copies

---

.github/workflows/promote.yml

This is a follow on to #1375 -- Promote seems to need the same fix in the Cypress run.

Cypress fix in promote

---

.github/workflows/deploy.yml
services/app-web/package.json
yarn.lock

#1378 was having CI issues due to an error with lerna. This reopens that in a clean branch.

Bump react-select from 5.4.0 to 5.7.0

---

.github/workflows/deploy.yml
.github/workflows/promote.yml

While we're dealing with these Cypress issues (gpu, geo-ip) I'd like us to log out IP address information on every run. This should give us a little more data while I'm fixing this.
https://qmacbis.atlassian.net/browse/MR-2874

Add a IP check on CI runs

---

services/app-web/src/components/HealthPlanPackageTable/HealthPlanPackageTable.module.scss
services/app-web/src/components/HealthPlanPackageTable/HealthPlanPackageTable.tsx
services/app-web/src/pages/CMSDashboard/CMSDashboard.test.tsx
tests/cypress/integration/cmsWorkflow/unlockResubmit.spec.ts

[MR-2872](https://qmacbis.atlassian.net/browse/MR-2872)
Missed this AC from the previous PR for this ticket.

Add screen reader announcement when entering table.

---

.envrc
services/app-web/serverless.yml
services/uploads/serverless.yml

This adds the s3 bucket, bucket policy, and virus scanning invoke permissions to support QA.
https://qmacbis.atlassian.net/browse/MR-2792

Add QA s3 bucket

---

services/postgres/serverless.yml

The promote on #1462 has thrown some errors. Reverting this while I investigate what is happening.
https://qmacbis.atlassian.net/browse/MR-2577

Revert Postgres 11 version pin

---

services/uploads/src/clamav.js

This is a small fix of a typo in MacRae's patch of the uploads service https://github.com/CMSgov/managed-care-review/pull/1483
https://qmacbis.atlassian.net/browse/MR-3027
N/A
N/A

Fix typo in uploads service patch

---

services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx
services/app-web/src/pages/StateSubmission/StateSubmissionForm.module.scss

Add some directions per [figma](https://www.figma.com/file/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=0-1&t=NPTMaYVFHPLBggf0-0)
https://qmacbis.atlassian.net/browse/MR-3190

[MR-3190] Add directions to only upload a single rate at a time

---

services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.test.tsx
services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.tsx
services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.tsx
services/app-web/src/pages/StateSubmission/StateSubmissionForm.module.scss
tests/cypress/integration/stateWorkflow/questionResponse/questionResponse.spec.ts

Copy changes. Synced styles between contract and rate file uploads.  Also discussed in slack, with screenshots.
https://qmacbis.atlassian.net/browse/MR-2141

MR-2141 Copy updates to contract and rate file uploads

---

services/app-web/src/constants/healthPlanPackages.ts
services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.test.tsx
services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx

Fix some minor UI things from this jira comment [MR-3173](https://qmacbis.atlassian.net/browse/MR-3173?focusedCommentId=119432)

MR-3173: Fix minor UI changes.

---

docs/technical-design/howto-update-state-programs.md
scripts/import-programs.ts
services/app-web/src/common-code/data/statePrograms.json

Update Missouri program and write documentation about how the process is working. 
https://qmacbis.atlassian.net/browse/MR-3155
The linked ticket shows what programs should change and the CSV programs list that we draw from.

MR-3155 Update MO programs and document

---

services/app-web/src/pages/QuestionResponse/QuestionResponse.test.tsx
services/app-web/src/pages/QuestionResponse/QuestionResponse.tsx

Punctuation fix on the Q&A page

Punctuation fix

---

.github/workflows/deploy.yml

This is recommended in the Cypress Dashboard interface based on number of tests we are running and current times 
Tests should still run.

Add more containers for Cypress

---

.github/workflows/promote.yml

Forgot to update the cypress config and env's in promote.

Update cypress in promote

---

.github/workflows/deploy-app-to-env.yml
.github/workflows/deploy.yml
scripts/destroy_stage.ts
services/app-api/scripts/invoke-migrate-lambda.sh
services/app-api/src/handlers/postgres_migrate.ts

This fixes up our `postgres_migrate` lambda to return errors consistently to the client. It also adds OTEL to record exceptions.
https://qmacbis.atlassian.net/browse/MR-2692

Refactor postgres_migrate return values and add OTEL.

---

services/app-api/src/handlers/cleanup.ts

Minor fix on the cron cleanup lambda.
https://qmacbis.atlassian.net/browse/MR-3292

Fix up snapshot cleanup cron lambda

---

docs/technical-design/code_coverage.md

The way we generate our combined code coverage report is not obvious, so I wrote up this explainer.
Is it clear?  Do you now understand our process?

MR-3373: Code coverage explainer

---

.github/workflows/deploy.yml
services/app-web/src/common-code/data/statePrograms.json

Prep for new states coming into MC-Review 
https://qmacbis.atlassian.net/browse/MR-3244

Add CA and TX programs

---

.github/workflows/deploy.yml

This just puts the pointer for the last PR merge (#1711)  back to `main`.

Cleanup workflow branch

---

.github/workflows/deploy-app-to-env.yml
.github/workflows/promote.yml

We need the `gen` folders for Cypress in promote.

Generate `gen` folders in Cypres promote.

---

.github/workflows/deploy-app-to-env.yml
.github/workflows/promote.yml

Copy `gen` folders in Promote Cypress job.

Copy gen folders in Promote Cypress job.

---

.vscode/launch.json
services/app-api/src/postgres/contractAndRates/submitContract.test.ts
services/app-api/src/postgres/contractAndRates/submitContract.ts

A couple of tests for submitContract.  One to make sure submit works, and one for invalidation of prior revisions.

MR-3411: submitContract tests

---

dev_tool/src/dev.ts
dev_tool/src/local/api.ts
dev_tool/src/local/graphql.ts
dev_tool/src/local/postgres.ts
dev_tool/src/local/proto.ts
dev_tool/src/local/s3.ts
dev_tool/src/local/storybook.ts
dev_tool/src/local/web.ts

Running the dev tool was not working because of the Lerna upgrade. Just needed to add `npx` whenever the tool uses Lerna.

Fix dev tool.

---

services/app-web/src/contexts/TraceContext.tsx

MR-3452: add second url

---

services/app-web/src/common-code/featureFlags/flags.ts
services/app-web/src/components/Banner/GenericApiErrorBanner/GenericApiErrorBanner.tsx
services/app-web/src/components/Banner/UserAccountWarningBanner/UserAccountWarningBanner.stories.tsx
services/app-web/src/components/Banner/UserAccountWarningBanner/UserAccountWarningBanner.tsx
services/app-web/src/components/ErrorAlert/ErrorAlert.tsx
services/app-web/src/components/ErrorAlert/ErrorAlertFailedRequest.tsx
services/app-web/src/components/Footer/Footer.tsx
services/app-web/src/components/Header/UserLoginInfo/UserLoginInfo.test.tsx
services/app-web/src/components/Header/UserLoginInfo/UserLoginInfo.tsx
services/app-web/src/constants/errors.ts
services/app-web/src/constants/index.ts
services/app-web/src/hooks/useString.ts
services/app-web/src/hooks/useStringConstants.ts
services/app-web/src/pages/QuestionResponse/QuestionResponse.tsx

Made a custom hook to serve up strings, because this way we can use LaunchDarkly in a central spot to control a string throughout the app.

MR-3404: email address change

---

services/app-web/src/components/Form/ErrorSummary/ErrorSummary.tsx
services/app-web/src/pages/StateSubmission/RateDetails/SingleRateCert/SingleRateCert.tsx

Follow on from product/design review
https://qmacbis.atlassian.net/browse/MR-3282
https://qmacbis.atlassian.net/browse/MR-3545

Fix issue with ErrorSummary focus, and add new rate focus

---

services/app-api/src/handlers/migrate_rate_documents.ts

Further fix for for loop bug (which we introduced 😆 fixing the other issues with how we skip contract only)
#1789

Supporting docs migration: Add even more consoles for context

---

.github/workflows/deploy.yml
.github/workflows/promote.yml
services/postgres/scripts/uploadScripts.ts
services/postgres/serverless.yml

This fixes the `deploy` and `promote` scripts after the VM PR merge. It also cleans out the old branch that was merged in and does not exist anymore.

Fix deploy & promote for vm merge

---

services/app-api/src/resolvers/healthPlanPackage/submitHealthPlanPackage.test.ts
services/app-api/src/resolvers/healthPlanPackage/submitHealthPlanPackage.ts

[MCR-3569](https://qmacbis.atlassian.net/browse/MCR-3569)
In `submitHealthPlanPacakge` resolver, after we update the contract, we still use `contractWithHistory` to submit rates. `contractWithHistory` is now old data, so those disconnected rates are getting submitted when a user changes to a contract-only submission either by manually selecting `contract-only` or switching to a Chip only submission.
The fix was to use the updated contract data to submit the rates. If this were a contract-only submission, the updated contract data would have removed them.
**Steps to reproduce**:
1. Unlock and edit a contract and rates submission
2. Resubmit
3. Look at revision history
[MCR-3567](https://qmacbis.atlassian.net/browse/MCR-3567)
This was also the cause for MCR-3567: Contract only submissions …

MCR-3569 & MCR-3567: CHIP only submissions crash rates dashboard

---

services/app-web/src/components/HealthPlanPackageTable/HealthPlanPackageTable.test.tsx
services/app-web/src/components/SectionHeader/SectionHeader.module.scss
services/app-web/src/components/SectionHeader/SectionHeader.tsx
services/app-web/src/components/SubmissionSummarySection/ContactsSummarySection/ContactsSummarySection.tsx
services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/RateDetailsSummarySection.tsx
services/app-web/src/components/SubmissionSummarySection/SubmissionSummarySection.module.scss
services/app-web/src/pages/CMSDashboard/CMSDashboard.tsx
services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsDashboard.tsx
services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsTable.test.tsx
services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsTable.tsx
services/app-web/src/pages/StateDashboard/StateDashboard.module.scss
services/app-web/src/pages/SubmissionSummary/RateSummary.tsx
services/app-web/src/pages/SubmissionSummary/SubmissionSummary.module.scss

Go ahead and turn on simple filters for rate type and state. Want to turn this on to allow beginning design/product review for filters that already work before the sprint ends.
https://qmacbis.atlassian.net/browse/MCR-2686
None yet. Tests will be an additional PR, I am working on Cypress stuff.

Get basic filters working

---

services/app-web/src/pages/MccrsId/MccrsId.module.scss
services/app-web/src/pages/MccrsId/MccrsId.tsx

This PR makes the design changes called out in the image below 
https://qmacbis.atlassian.net/browse/MCR-3547

[MCR-2547] Requested design changes

---

services/app-api/src/resolvers/attributeHelper.ts
services/app-api/src/resolvers/healthPlanPackage/indexHealthPlanPackages.ts

We're not seeing the traces I expect in New Relic, this adds some logging to try and figure out why.

Fix trace name for indexHPP and add some prospective logging

---

services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.test.tsx
services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.tsx

Add rate submission date
https://qmacbis.atlassian.net/browse/MCR-3598
- Add assertion that checks for new field 
Field is present on all rates

MCR-3598 rate submission date

---

services/app-web/src/components/HealthPlanPackageTable/HealthPlanPackageTable.tsx
services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsTable.tsx

[MCR-3751](https://qmacbis.atlassian.net/browse/MCR-3751)
- Sort state filter options.

MCR-3571: Sort state filter options in alphabetical order.

---

services/app-web/src/constants/statutoryRegulatoryAttestation.ts
services/cypress/support/stateSubmissionFormCommands.ts

This follows another copy change [PR](https://github.com/Enterprise-CMCS/managed-care-review/pull/2063) to adjust the copy further in line with this ticket [comment](https://qmacbis.atlassian.net/browse/MCR-3601?focusedCommentId=125758)
https://qmacbis.atlassian.net/browse/MCR-3601

[MCR-3601] copy tweak for attestation field

---

docs/technical-design/howto-update-state-programs.md
services/app-web/src/common-code/data/statePrograms.json

Changes to MT and OR state programs for onboarding. 1 addition, 2 deletions
https://qmacbis.atlassian.net/browse/MCR-3815
Make sure there are UUIDs for new programs and no additions,deletions beyond the states being edited.

MCR-3815 Adjust programs for OR and MT

---

services/app-api/src/emailer/emails/__snapshots__/sendQuestionResponseStateEmail.test.ts.snap
services/app-api/src/emailer/etaTemplates/sendQuestionResponseStateEmail.eta

Design updated the email they want to display to the response notification emails. Please see this [comment ](https://qmacbis.atlassian.net/browse/MCR-2540?focusedCommentId=126288)for context 
https://qmacbis.atlassian.net/browse/MCR-2540

MCR-2540 update contact email in email template

---

docs/architectural-decision-records/025-use-clamavd-for-uploads-scanning.md

This pulls in the ADR that was up for review into our repo.
https://qmacbis.atlassian.net/browse/MCR-2648

Add ADR for AV Scanning decision

---

services/app-web/src/common-code/data/statePrograms.json

Follow on task 
https://qmacbis.atlassian.net/browse/MCR-3815?focusedCommentId=126354&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-126354

Adjust display name further after product design discussion

---

.github/workflows/deploy-app-to-env.yml
.github/workflows/deploy.yml

Point back to main

---

services/app-web/src/common-code/featureFlags/flags.ts

Adds new feature flag. Also moved permanent flags to all be in the same section.
https://qmacbis.atlassian.net/browse/MCR-3800

Add edit and unlock rate flag

---

services/app-api/serverless.yml

I broke dev by leaving a hard coded secret name in the code.

Fix hard coded secret name that broke dev

---

docs/templates/technical-design-discussion-template.md

Updating tech design/discovery to look more like the MM discovery doc. This is to prepare for DTBM next week, I want to propose a more concrete experiment with this stuff.

Update tech design discovery doc template

---

services/app-web/src/components/Select/Select.module.scss
services/app-web/src/pages/LinkYourRates/LinkRateSelect.tsx

This PR resolves the following:
https://jiraent.cms.gov/browse/MCR-3889

[MCR-3889] addressing notes from design review

---

services/app-web/src/common-code/ContractType.ts
services/app-web/src/common-code/ContractTypeProvisions.ts
services/app-web/src/gqlHelpers/contractsAndRates.ts
services/app-web/src/hooks/useTealium.ts
services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.test.tsx
services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ContactsSummarySectionV2.tsx
services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ContractDetailsSummarySectionV2.stories.tsx
services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ContractDetailsSummarySectionV2.test.tsx
services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ContractDetailsSummarySectionV2.tsx
services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/RateDetailsSummarySectionV2.stories.tsx
services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/RateDetailsSummarySectionV2.test.tsx
services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/RateDetailsSummarySectionV2.tsx
services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ReviewSubmitV2.test.tsx
services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ReviewSubmitV2.tsx
services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/SubmissionTypeSummarySectionV2.tsx
services/app-web/src/testHelpers/apolloMocks/contractPackageDataMock.ts
services/app-web/src/testHelpers/apolloMocks/index.ts
services/app-web/src/testHelpers/jestHelpers.tsx

Other work: 
- Contract mocks and test utilities, fixed those for now by adding `__typename`
- Because I changed the contract mocks, rate details tests with those mocks started failing. 
- I think this is a good clean up, those tests had many more API requests than they needed likely because contracts API mocks weren't returning expected data. 
- Cleaned up lingering references to the document date table in submission summary - new implementation uses API `dateAdded values` 
https://jiraent.cms.gov/browse/MCR-4027
- Skipped tests in review submit work now

MCR-4027 Update Review Submit tests

---

services/app-api/src/postgres/contractAndRates/unlockContract.ts
services/app-api/src/postgres/contractAndRates/unlockRate.ts
services/app-api/src/postgres/postgresStore.ts
services/app-api/src/resolvers/configureResolvers.ts
services/app-api/src/resolvers/contract/submitContract.test.ts
services/app-api/src/resolvers/healthPlanPackage/unlockHealthPlanPackage.ts

This PR feature flags some of the logic for unlock contract, no longer assuming that contracts have submission packages
None, but prod is broken.

Fix Prod Crash: Link Rate FF for unlock contract

---

services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ContractDetailsSummarySectionV2.test.tsx
services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/SubmissionTypeSummarySectionV2.test.tsx
services/app-web/src/pages/SubmissionRevisionSummary/SubmissionRevisionSummaryV2.test.tsx
services/app-web/src/testHelpers/apolloMocks/contractPackageDataMock.ts

This PR adds back test that were skipped in the PR for https://jiraent.cms.gov/browse/MCR-4075
https://jiraent.cms.gov/browse/MCR-4096

Reimplement skipped test related to SubmissionRevisionSummary changes

---

services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.tsx
services/app-web/src/pages/StateSubmission/RateDetails/V2/SingleRateFormFields.tsx
services/app-web/src/pages/StateSubmission/StateSubmissionForm.module.scss

[MCR-4113](https://jiraent.cms.gov/browse/MCR-4113)
[JIRA](https://www.figma.com/file/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?type=design&node-id=12474-67689&mode=design&t=RlVYLESkNaOpscTn-0)
- Update the `Add a certifying actuary` button styling to an outlined button.
- Fixed "Remove certifying actuary" and "Remove rate certification" button color.

MCR-4113: Additional certifying actuary styling tweaks

---

services/app-api/prisma/migrations/20240517195439_create_state_program_table/migration.sql
services/app-api/prisma/migrations/20240520225931_create_relation_to_stateCode_on_state_programs_table/migration.sql
services/app-api/prisma/schema.prisma

- Creates migration for creating a table to represent state programs
https://jiraent.cms.gov/browse/MCR-4045

MCR-4045: Create table for state programs

---

.github/dependabot.yml

This is a small change to see if we can get dependabot to group updates for some of the packages that need to be updated all at the same time. We unfortunately won't know how this works for us until we merge it and see how dependabot reacts.
https://jiraent.cms.gov/browse/MCR-4164

Group some dependabot updates

---

services/app-web/src/common-code/data/statePrograms.json

Update north carolina and virginia programs
https://jiraent.cms.gov/browse/MCR-4207

Update NC and VA programs

---

services/app-web/src/pages/SubmissionSummary/V2/SubmissionSummaryV2.tsx

MCCRS links broke when the site changed. Update to new site address.
https://jiraent.cms.gov/browse/MCR-4079
- link should not 503

Update MCCRS links on summary page 

---

docs/architectural-decision-records/027-vite-for-web-build.md

Document why we are switching to Vite
https://jiraent.cms.gov/browse/MCR-4204
Please read ADR and let me know if I missed anything

ADR on Vite

---

docs/technical-design/howto-update-state-programs.md
services/app-api/src/resolvers/user/fetchCurrentUser.test.ts
services/app-web/src/common-code/data/statePrograms.json

Update programs list.
https://jiraent.cms.gov/browse/MCR-4241
manually check state program json briefly - things should make sense

Update programs list

---

services/app-web/src/pages/StateSubmission/Contacts/Contacts.tsx
services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.tsx
services/app-web/src/pages/StateSubmission/Documents/Documents.tsx
services/app-web/src/pages/StateSubmission/New/NewStateSubmissionForm.tsx
services/app-web/src/pages/StateSubmission/RateDetails/V2/RateDetailsV2.tsx
services/app-web/src/pages/StateSubmission/ReviewSubmit/V2/ReviewSubmit/ReviewSubmitV2.tsx
services/app-web/src/pages/StateSubmission/StateSubmissionForm.module.scss
services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx
services/cypress/integration/cmsWorkflow/unlockResubmit.spec.ts

Step indicator should be centered and bug with banner on unlocked submission  being edited should no longer be present.
follow on to #2551 
BEFORE
AFTER
No tests but we sure do need visual regression tests automation. Forthcoming... 
Go through all interations of the form
Draft
Submitted on summary page
Unlocked on review and submit page
Unlocked and on a form page being edited

Fix: step indicator and banner placement

---

services/cypress/support/stateSubmissionFormCommands.ts

Follow on to #2579  - extend that `.check` fix to even more checkbox fields in case it helps
Follow on to #2579  
If Cypress passes, we can merge.

fix: cypress checkbox behavior - handle actuary firm the same 

---

dev_tool/package.json
dev_tool/src/dev.ts
package.json
scripts/package.json
services/app-api/package.json
services/app-web/package.json
services/cypress/package.json
services/uploads/package.json

The only one I saw that didn't work was `./dev clean` because of no node_modules where the old model had them. edited to just call the root level clean

Testing dev scripts

---

services/app-web/src/pages/LinkYourRates/LinkRateSelect.tsx
services/app-web/src/pages/ReplaceRate/ReplaceRate.test.tsx
services/app-web/src/pages/ReplaceRate/ReplaceRate.tsx
services/app-web/src/pages/ReplaceRate/ReplaceRateSchema.ts
services/app-web/src/pages/StateSubmission/RateDetails/RateDetails.test.tsx
services/app-web/src/testHelpers/apolloMocks/contractGQLMock.ts
services/app-web/src/testHelpers/apolloMocks/index.ts
services/app-web/src/testHelpers/apolloMocks/replaceRateGQLMocks.ts

[MCR-4131](https://jiraent.cms.gov/browse/MCR-4131)
- Add inline and summary errors for `Withdraw and replace rate on contract` text input.
- Add inline and summary errors for `Select a replacement rate` selection.
- Fix the `Select a replacement rate` clear selection button.
`ReplacementRate.test.tsx`
- `'shows errors when required fields are not filled in'`

MCR-4131: Admin must add an update reason

---

.github/workflows/send-dso-metrics.yml

Unfortunately this isn't a workflow we can test without merging, so here's another pass at fixing the ARN for exporting the metrics. This approach works in some of our other workflows, so hoping it gets us closer to this working.

Reformat role ARN for DSO Metrics Integration

---

docs/technical-design/howto-update-state-programs.md
scripts/import-programs.ts
services/app-api/src/common-code/data/statePrograms.json
services/app-web/src/common-code/data/statePrograms.json

- Updated state programs. Noticed we now have statePrograms.json in app-api as well as app-web so I updated both
- Some documentation updates 
https://jiraent.cms.gov/browse/MCR-4409

MCR-4409: update state programs

---

services/app-web/src/tealium/tealium.ts

I hope I interpreted the instructions correctly to change the domain to tealium-tags.cms.gov in the tealium.ts inline script
https://jiraent.cms.gov/browse/MCR-4451

MCR-4451: update tealium script

---

services/app-api/src/resolvers/contract/indexContracts.ts
services/app-web/src/components/HealthPlanPackageTable/HealthPlanPackageTable.module.scss
services/app-web/src/components/HealthPlanPackageTable/HealthPlanPackageTable.stories.tsx
services/app-web/src/components/HealthPlanPackageTable/HealthPlanPackageTable.test.tsx
services/app-web/src/components/HealthPlanPackageTable/HealthPlanPackageTable.tsx
services/app-web/src/components/HealthPlanPackageTable/index.ts
services/app-web/src/components/index.ts
services/app-web/src/pages/App/AppRoutes.test.tsx
services/app-web/src/pages/CMSDashboard/CMSDashboard.test.tsx
services/app-web/src/pages/CMSDashboard/SubmissionsDashboard/SubmissionsDashboard.tsx
services/app-web/src/pages/StateDashboard/StateDashboard.tsx
services/cypress/support/loginCommands.ts

Reverts Enterprise-CMCS/managed-care-review#2759

Revert "MCR-4140 CMS submissions dashboard uses contract api"

---

docs/technical-design/tealium-logging.md
services/app-web/src/common-code/data/dataUtilities.test.ts
services/app-web/src/common-code/data/dataUtilities.ts
services/app-web/src/common-code/data/index.ts
services/app-web/src/components/ChangeHistory/ChangeHistoryV2.tsx
services/app-web/src/components/ContractTable/ContractTable.tsx
services/app-web/src/components/DataDetail/DataDetailContactField/DataDetailContactField.tsx
services/app-web/src/components/FilterAccordion/FilterAccordion.tsx
services/app-web/src/components/Modal/UnlockSubmitModal.tsx
services/app-web/src/components/PoliteErrorMessage/PoliteErrorMessage.tsx
services/app-web/src/components/TealiumLogging/Link.tsx
services/app-web/src/hooks/useTealium.ts
services/app-web/src/pages/App/App.tsx
services/app-web/src/pages/CMSDashboard/RateReviewsDashboard/RateReviewsTable.tsx
services/app-web/src/pages/Settings/SettingsTables/StateAssignmentTable.tsx
services/app-web/src/pages/StateDashboard/SubmissionSuccessMessage.tsx
services/app-web/src/tealium/constants.ts
services/app-web/src/tealium/index.ts
services/app-web/src/tealium/tealium.ts
services/app-web/src/tealium/tealiumHelpers.ts
services/app-web/src/tealium/types.ts
services/app-web/src/testHelpers/tealiumHelpers.ts

- Get production tealium upgraded to new hostname now that they are ready for us
- Address random issues in [this ticket](https://jira.cms.gov/browse/BLSTANALYT-7663) as much as possible. 
- Turn console logging in dev so we don't flood cypress console. 
- moved types to their own file
- stopped bothering with section subsection and component type since I found out its required asked that this be excluded from our build
https://jira.cms.gov/browse/BLSTANALYT-7663
https://jiraent.cms.gov/browse/MCR-4301
n/a
n/a
Things I added logging around that should show up locally
- accordion open and close logs something (its accordion_opened always)
-  form submit logs  (just did main form for now, ran out of steam)
- filters pass all the the various filters set with their values
- a bunch of other …

Analytics bugfix

---

services/app-web/src/pages/Settings/SettingsTables/StateAssignmentTable.tsx

[MCR-4522](https://jiraent.cms.gov/browse/MCR-4522)
[Figma](https://www.figma.com/design/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=13344-80274&node-type=frame&t=5Iwsk7CazXS6iXsp-0)

MCR-4522: FIx copy change on state assignment page

---

services/app-api/serverless.yml
services/app-api/src/domain-models/DocumentType.ts
services/app-api/src/domain-models/index.ts
services/app-api/src/handlers/audit_s3.ts
services/app-api/src/postgres/documents/findAllDocuments.ts
services/app-api/src/postgres/documents/index.ts
services/app-api/src/postgres/postgresStore.ts

This adds a lambda that compares all the documents stored in our database against what exists in s3.
https://jiraent.cms.gov/browse/MCR-4543

Add audit s3 files lambda

---

services/app-api/src/common-code/data/statePrograms.json
services/app-web/src/common-code/data/statePrograms.json

https://jiraent.cms.gov/browse/MCR-4538

update state programs october 2024

---

services/app-graphql/src/fragments/questionListFragment.graphql
services/app-graphql/src/fragments/questionsEdgeFragment.graphql
services/app-graphql/src/queries/fetchContractWithQuestions.graphql
services/app-graphql/src/queries/fetchHealthPlanPackageWithQuestions.graphql
services/app-graphql/src/queries/fetchRateWithQuestions.graphql
services/app-web/src/gqlHelpers/mutationWrappersForUserFriendlyErrors.ts
services/app-web/src/pages/QuestionResponse/QATable/CMSQuestionResponseTable.tsx
services/app-web/src/pages/QuestionResponse/QATable/QATable.test.tsx
services/app-web/src/pages/QuestionResponse/QATable/QuestionResponseRound.tsx
services/app-web/src/pages/QuestionResponse/QuestionResponseHelpers/index.ts
services/app-web/src/pages/QuestionResponse/QuestionResponseHelpers/questionResponseHelpers.ts
services/app-web/src/pages/QuestionResponse/RateQuestionResponse.test.tsx
services/app-web/src/pages/QuestionResponse/RateQuestionResponse.tsx
services/app-web/src/pages/QuestionResponse/UploadQuestions/UploadContractQuestions.tsx
services/app-web/src/pages/QuestionResponse/UploadQuestions/UploadQuestionsForm.tsx
services/app-web/src/pages/QuestionResponse/UploadQuestions/UploadRateQuestions.test.tsx
services/app-web/src/pages/QuestionResponse/UploadQuestions/UploadRateQuestions.tsx
services/app-web/src/pages/SubmissionSideNav/RateSummarySideNav.tsx
services/app-web/src/testHelpers/apolloMocks/rateDataMock.ts
services/app-web/src/testHelpers/apolloMocks/rateGQLMocks.ts

[MCR-4425](https://jiraent.cms.gov/browse/MCR-4425): CMS can submit or cancel rate questions to state
- If I have uploaded a question document and click "submit"
Then I am redirected to the Q&A page for that rate review and see a confirmation banner ( see [designs](https://www.figma.com/design/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=14220-63121&t=kw3zXaDgNH0ShxwH-1) ).
- If I uploaded a question document for a rate review and I click cancel 
Then I am routed from the upload page back to the Q&A page for the rate review and I do NOT see the question document displayed there
- If I have uploaded a question document for a rate review but I do not click "submit" and I exit the page 
Then when I revisit the Q&A page I do not see the question doc I uploaded 
- If I try to submit a …

MCR-4425 & MCR-4291: cms can submit or cancel rate questions and display submitted rate questions

---

docs/technical-design/contract-rate-non-revision-design.md

Add description of Questions and Responses to the revision-less docs
https://jiraent.cms.gov/browse/MCR-4575

Add Q&A to revision-less docs

---

services/app-api/src/emailer/emails/__snapshots__/sendRateQuestionResponseStateEmail.test.ts.snap
services/app-api/src/emailer/emails/sendRateQuestionResponseStateEmail.test.ts
services/app-api/src/emailer/emails/sendRateQuestionResponseStateEmail.ts
services/app-api/src/emailer/etaTemplates/sendRateQuestionResponseStateEmail.eta

[MCR-4427](https://jiraent.cms.gov/browse/MCR-4427)
Fix template to reflect [designs](https://www.figma.com/design/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=15562-84188&t=moPBumsOpWzDbt41-1).

Fix state rate question response email template.

---

services/app-api/src/resolvers/questionResponse/createRateQuestionResponse.test.ts

I missed some incorrect tests from a previous PR review. It is concerning that they were not picked up in CI API tests.

Fixing createRateQuestionResponse emailer tests

---

services/app-api/src/common-code/featureFlags/flags.ts
services/app-web/src/common-code/featureFlags/flags.ts

[MCR-4598](https://jiraent.cms.gov/browse/MCR-4598)
Add feature flag `submission-approvals` for the submission approvals epic.
- Add `submission-approvals` flag to LaunchDarkly.
- Add `submission-approvals` flag to codebase.

MCR-4598: Add feature flag for submission approval

---

services/app-web/src/components/Banner/Banner.module.scss
services/app-web/src/components/Banner/DocumentWarningBanner/DocumentWarningBanner.tsx
services/app-web/src/components/Banner/PreviousSubmissionBanner/PreviousSubmissionBanner.tsx
services/app-web/src/components/Banner/QuestionResponseSubmitBanner/QuestionResponseSubmitBanner.tsx
services/app-web/src/components/Banner/UserAccountWarningBanner/UserAccountWarningBanner.tsx
services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx

Adding more top and bottom spacing for the text in our informational banners: unlocked. This is to address comments in this ticket [MCR-4590](https://jiraent.cms.gov/browse/MCR-4590)

Fix spacing in our informational banners

---

services/app-web/src/pages/SubmissionSummary/SubmissionSummary.tsx

[MCR-4746](https://jiraent.cms.gov/browse/MCR-4746)
[Figma](https://www.figma.com/design/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=16271-63429&node-type=frame&t=PxOeRhJVVOgZr8Jv-0)
- Change `Approve submission` --> `Release to state` on submission summary page and modal
- Update copy on submission approval modal

MCR-4746: Change CTA copy from "Approved" to "Released to state"

---

services/app-api/src/common-code/featureFlags/flags.ts
services/app-web/src/common-code/featureFlags/flags.ts

[MCR-4656](https://jiraent.cms.gov/browse/MCR-4656)https://jiraent.cms.gov/browse/MCR-4656
Add new `withdraw-rate` flag to codebase and LaunchDarkly

MCR-4656: Add withdraw rate flag

---

services/app-web/src/components/Header/Header.module.scss
services/app-web/src/components/Header/UserLoginInfo/UserLoginInfo.tsx
services/app-web/src/hooks/useStringConstants.ts

[MCR-4446](https://jiraent.cms.gov/browse/MCR-4446)
- Remove mc-review email from all helpdesk email links.
- Fix header navigation orientation on smaller screens (1280px).

MCR-4446: remove mc review email from helpdesk mailto link

---

services/app-api/src/postgres/contractAndRates/withdrawRate.ts
services/app-api/src/resolvers/rate/withdrawRate.test.ts

Cleaning up a couple things in the refactor work.

Clean up withdrawRate api refactor work.

---

.envrc
docs/Configuration.md
services/app-api/serverless.yml
services/app-api/src/handlers/apollo_gql.ts

- This PR removes the code for IP address checks we have decided are no longer necessary 
- The parameter store field for allowed_ip_addressses will be removed after this ticket is merged 
https://jiraent.cms.gov/browse/MCR-4825
- sign in to review app as a CMS user
- navigate to /dev/api-access
- Generate a JWT and copy the provided code sample to hit the indexRates API
- Paste code sample into terminal. Should get back a successful API response

MCR-4825: remove references to ip address restriction for third party access

---

services/app-web/src/pages/Help/Help.tsx
services/app-web/src/pages/StateSubmission/RateDetails/SingleRateFormFields.tsx
services/app-web/src/pages/StateSubmission/SubmissionType/SubmissionType.tsx

[MCR-4868](https://jiraent.cms.gov/browse/MCR-4868)
AC:
- Add helper text on Submission Type page > programs field ([see Figma](https://www.figma.com/design/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=10355-75170&t=pd2kJIYQtrOCzO1b-1))
- Add helper text on Rate Details page > rates included in this rate certification field ([see Figma](https://www.figma.com/design/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=9627-31925&t=pd2kJIYQtrOCzO1b-1)) 
- Add help text on Help page ([see Figma](https://www.figma.com/design/frKNnm6lkcpdjJ2eVJE8Bj/Managed-Care-Review?node-id=16749-20668&t=pd2kJIYQtrOCzO1b-1))

MCR-4868: copy change program dropdown helper text

---

dev_tool/src/dev.ts
dev_tool/src/local/api.ts
dev_tool/src/local/packages.ts
dev_tool/src/local/web.ts
package.json

This PR adds a new script to watch package files and trigger the build command
[MCR-4677](https://jiraent.cms.gov/browse/MCR-4677)
Make a change in one of the files found in the packages directory (I used constants) - you should see the change reflected in the corresponding js files

[MCR-4677] updated dev tool to auto-build packages

---

packages/common-code/src/featureFlags/flags.ts

- Adds flag to codebase
- Adds flag to LD
https://jiraent.cms.gov/browse/MCR-5014
Enables undo withdraw rate feature

MCR-5014: create flag for undo withdraw-rate

---

.github/workflows/deploy-infra-to-env.yml

Fix id in infra deploy yml

---

docs/Technologies.md

Updated the tools we use for Cypress accessibility tests.

Update accessibility tools in the technology doc

---

README.md

These are just some small documentation changes for things that are now different in Serverless v4.
https://jiraent.cms.gov/browse/MCR-5063

Update docs for latest Serverless v4

---

services/app-api/src/emailer/emails/__snapshots__/sendUndoWithdrawnRateStateEmail.test.ts.snap
services/app-api/src/emailer/etaTemplates/sendUndoWithdrawnRateStateEmail.eta

Small template change regarding [this comment](https://jiraent.cms.gov/browse/MCR-4908?focusedId=3754233&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-3754233)

[MCR-4908] updated eta file

---

docs/example-code/api-sample.ts
docs/example-code/sample.prisma

Add code samples. 

---

.github/workflows/validate-prs.yml
docs/architectural-decision-records/004-use-dynamodb-for-now.md
docs/architectural-decision-records/005-frontend-a11y-toolset.md
docs/architectural-decision-records/007-move-to-postgres.md
docs/architectural-decision-records/008-form-data-serialization.md
docs/architectural-decision-records/009-data-serialization-framework.md
docs/architectural-decision-records/010-prisma-for-postgres.md
docs/architectural-decision-records/030-use-pnpm-as-package-manager.md
docs/technical-design/code_coverage.md
docs/technical-design/creating-and-testing-endpoints.md
services/cypress/README.md

ADR for previous work moving to pnpm, also cleaned up some references between ADRS overriding eachother.
I _think_ I caught a couple places that still need to use the pnpm script also? Maybe? There is a small code change here please review. 
https://jiraent.cms.gov/browse/MCR-4307
https://jiraent.cms.gov/browse/MCR-4315
Read these docs and directly suggest any changes or edits for things I mistated.

ADR for pnpm as build tool 

---

README.md
docs/technical-design/howto-migrations.md
services/app-api/src/dataMigrations/dataMigrator.ts

Update migrations doc, remove references to outdated approaches 
https://jiraent.cms.gov/browse/MCR-3843

Update migrations doc

---

docs/technical-design/how-cicd-works.md

Write down the basics to help guide new folks if needed.
https://jiraent.cms.gov/browse/MCR-2656
Direct edits welcome

Add basic CI/CD technical doc

---

services/app-api/src/emailer/emails/__snapshots__/sendWithdrawnSubmissionCMSEmail.test.ts.snap
services/app-api/src/emailer/emails/__snapshots__/sendWithdrawnSubmissionStateEmail.test.ts.snap
services/app-api/src/emailer/etaTemplates/sendWithdrawnSubmissionCMSEmail.eta
services/app-api/src/emailer/etaTemplates/sendWithdrawnSubmissionStateEmail.eta

Small PR to list rates in the withdraw email whether its only one or multiple
[MCR-4650](https://jiraent.cms.gov/browse/MCR-4650)

[MCR-4650] Updated eta files

---

packages/hpp/src/data/statePrograms.json

Add a new program `BHAI` for the state of CA
[MCR-5277](https://jiraent.cms.gov/browse/MCR-5277)

MCR-5277: Add new state program

---

.github/workflows/deploy.yml
.github/workflows/promote.yml
pnpm-lock.yaml
services/postgres/esbuild.config.js
services/postgres/package.json
services/postgres/serverless.yml

This fixes up the github actions workflow files for deploy and promote after the #3328 PR merged for aurora data exports.

Fix deploy and promote workflows

---

services/app-web/src/components/Modal/UnlockSubmitModal.tsx

[MCR-4865](https://jiraent.cms.gov/browse/MCR-4865)
The `UnlockSubmitModal` `textarea` was not in the tab order of the interactive elements of the modal. When we place nested interactive elements inside a `react-uswds` modal it seems to lose tab order. Adding a `tabIndex={1}` to the `form` element allows the form fields inside to be in the tab order.
Open a unlock or resubmit modal and tab through. The `textarea` should be the first interactive element focused.

MCR-4865: Modal form fields not in tab order

---

packages/common-code/src/featureFlags/flags.ts

- Adds flag to codebase
- Adds flag to LD
https://jiraent.cms.gov/browse/MCR-5374

MCR-5374: Create dsnp flag

---

.github/pull_request_template.md
API_Changelog.md
README.md

This PR
- Creates API changelog and includes API schema changes since May
- Adds link to the changelog from the README
- Updates the PR template to have a checklist for updating the changelog and checking for accessibilty 
https://jiraent.cms.gov/browse/MCR-5368

MCR-5368: create changelog and update PR template

---

services/app-web/.eslintrc
services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.test.tsx
services/app-web/src/pages/StateSubmission/ContractDetails/ContractDetails.tsx

Small pr to address [design feedback](https://jiraent.cms.gov/secure/RapidBoard.jspa?rapidView=6115&projectKey=MCR&view=detail&selectedIssue=MCR-5363&quickFilter=34435#:~:text=I%20have%20a,have%20a%20reference.)
[MCR-5363](https://jiraent.cms.gov/browse/MCR-5363)

[MCR-5363] added andi output to link

---

services/app-api/src/handlers/__tests__/apollo_status_codes.test.ts
services/app-api/src/handlers/__tests__/apollo_v3_v4_status_summary.test.ts

This pull request introduces several updates to workflows, documentation, and dependencies, with a focus on improving deployment processes, API changelog tracking, and migrating error handling for Apollo Server v4 compatibility. Below are the most important changes grouped by theme.
* [`.github/workflows/deploy-infra-to-env.yml`](diffhunk://#diff-654600def8f5a17035081a5861aeb557df98a68c52ed3f0ff16b4a2f4bbac8c4R23-R26): Added new secrets (`prod_aws_account_id`, `val_aws_account_id`) and updated job dependencies to include `uploads`. Introduced steps to download and unzip Prisma client layers for Postgres deployment. [[1]](diffhunk://#diff-654600def8f5a17035081a5861aeb557df98a68c52ed3f0ff16b4a2f4bbac8c4R23-R26) [[2]](diffhunk://#diff-654600def8f5a17035081a5861aeb557df98a68c52ed3f0ff16b4a2f4b …

MCR-4985 apollo status code test

---

services/app-web/src/components/Spinner/Spinner.module.scss
services/app-web/src/components/SubmissionSummarySection/RateDetailsSummarySection/SingleRateSummarySection.tsx
services/app-web/src/components/SubmissionSummarySection/UploadedDocumentsTable/UploadedDocumentsTable.module.scss
services/app-web/src/components/SubmissionSummarySection/UploadedDocumentsTable/UploadedDocumentsTable.tsx
services/app-web/src/components/Tabs/Tabs.module.scss
services/app-web/src/pages/APIAccess/APIAccess.module.scss
services/app-web/src/pages/StateSubmission/ReviewSubmit/ContactsSummarySection.tsx
services/app-web/src/pages/StateSubmission/ReviewSubmit/RateDetailsSummarySection.tsx
services/app-web/src/pages/StateSubmission/ReviewSubmit/ReviewSubmit.module.scss
services/app-web/src/pages/StateSubmission/ReviewSubmit/SubmissionTypeSummarySection.tsx
services/app-web/src/styles/custom.scss

[MCR-5452](https://jiraent.cms.gov/browse/MCR-5452)
Fixes the list item element spacing on submission summary page.
Additional fixes:
- Fix state contacts list to be 2 columns instead of 1.
- <img width="500" alt="Screenshot 2025-08-27 at 9 09 47 AM" src="https://github.com/user-attachments/assets/0bbed3b9-7087-4dac-bb62-5943694f680d" />
- Fix the top margin of previous submission summary pages.
- Current UI 
- <img width="500" alt="Screenshot 2025-08-27 at 12 32 25 AM" src="https://github.com/user-attachments/assets/b48afdae-cebe-4116-a727-e80377add262" />
- Fixed UI
- <img width="500" alt="Screenshot 2025-08-27 at 12 30 35 AM" src="https://github.com/user-attachments/assets/6106a8a9-af94-4947-a891-3be2470790db" />
- Fix some stylelint issues.

MCR-5452: Fix d-snp rate question spacing
